MOD=bossrace.bl3hotfix
EXE=ixoraspawners.py
SEED ?= 42
GENDIR=bossrace-seeds-0.2
DISTFILES=$(MOD) bossrace.rand.bl3hotfix \
	$(GENDIR)/bossrace.1.bl3hotfix.txt \
	$(GENDIR)/bossrace.2.bl3hotfix.txt \
	$(GENDIR)/bossrace.3.bl3hotfix.txt \
	$(GENDIR)/bossrace.4.bl3hotfix.txt \
	$(GENDIR)/bossrace.5.bl3hotfix.txt \
	$(GENDIR)/bossrace.6.bl3hotfix.txt \
	$(GENDIR)/bossrace.7.bl3hotfix.txt \
	$(GENDIR)/bossrace.8.bl3hotfix.txt \
	$(GENDIR)/bossrace.9.bl3hotfix.txt \
	$(GENDIR)/bossrace.10.bl3hotfix.txt \
	$(GENDIR)/bossrace.11.bl3hotfix.txt \
	$(GENDIR)/bossrace.12.bl3hotfix.txt \
	$(GENDIR)/bossrace.13.bl3hotfix.txt \
	$(GENDIR)/bossrace.14.bl3hotfix.txt \
	$(GENDIR)/bossrace.15.bl3hotfix.txt \
	$(GENDIR)/bossrace.16.bl3hotfix.txt \
	$(GENDIR)/bossrace.17.bl3hotfix.txt \
	$(GENDIR)/bossrace.18.bl3hotfix.txt \
	$(GENDIR)/bossrace.19.bl3hotfix.txt \
	$(GENDIR)/bossrace.20.bl3hotfix.txt \
	$(GENDIR)/bossrace.21.bl3hotfix.txt \
	$(GENDIR)/bossrace.22.bl3hotfix.txt \
	$(GENDIR)/bossrace.23.bl3hotfix.txt \
	$(GENDIR)/bossrace.24.bl3hotfix.txt \
	$(GENDIR)/bossrace.25.bl3hotfix.txt \
	$(GENDIR)/bossrace.26.bl3hotfix.txt \
	$(GENDIR)/bossrace.27.bl3hotfix.txt \
	$(GENDIR)/bossrace.28.bl3hotfix.txt \
	$(GENDIR)/bossrace.29.bl3hotfix.txt \
	$(GENDIR)/bossrace.30.bl3hotfix.txt \
	$(GENDIR)/bossrace.31.bl3hotfix.txt \
	$(GENDIR)/bossrace.32.bl3hotfix.txt \
	$(GENDIR)/bossrace.33.bl3hotfix.txt \
	$(GENDIR)/bossrace.34.bl3hotfix.txt \
	$(GENDIR)/bossrace.35.bl3hotfix.txt \
	$(GENDIR)/bossrace.36.bl3hotfix.txt \
	$(GENDIR)/bossrace.37.bl3hotfix.txt \
	$(GENDIR)/bossrace.38.bl3hotfix.txt \
	$(GENDIR)/bossrace.39.bl3hotfix.txt \
	$(GENDIR)/bossrace.40.bl3hotfix.txt \
	$(GENDIR)/bossrace.41.bl3hotfix.txt \
	$(GENDIR)/bossrace.42.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.43.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.44.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.45.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.46.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.47.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.48.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.49.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.50.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.51.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.52.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.53.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.54.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.55.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.56.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.57.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.58.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.59.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.60.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.61.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.62.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.63.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.64.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.65.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.66.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.67.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.68.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.69.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.70.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.71.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.72.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.73.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.74.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.75.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.76.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.77.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.78.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.79.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.80.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.81.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.82.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.83.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.84.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.85.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.86.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.87.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.88.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.89.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.90.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.91.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.92.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.93.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.94.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.95.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.96.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.97.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.98.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.99.bl3hotfix.txt \
# 	$(GENDIR)/bossrace.100.bl3hotfix.txt 

seeds:
	mkdir seeds

$(GENDIR):
	mkdir $(GENDIR)

default: mod

mod: $(MOD)

$(MOD): $(EXE) ixorabosses.py
	python3 $(EXE) --seed $(SEED)
clean:
	rm -f bossrace.bl3hotfix
	rm -f $(DISTFILES)

bossrace.rand.bl3hotfix: $(EXE)
	python3 $(EXE) --output bossrace.rand.bl3hotfix

mitosis.bossrace.bl3hotfix: $(EXE)
	python3 $(EXE) --output mitosis.bossrace.bl3hotfix --seed $(SEED) --mitosis

mitosis.bl3hotfix: $(EXE)
	python3 $(EXE) --output mitosis.bl3hotfix --seed $(SEED) --justmitosis

bossrace.%.bl3hotfix: $(EXE) ixorabosses.py
	python3 $(EXE) --seed $* --output bossrace.$*.bl3hotfix

bossrace.%.bl3hotfix.txt: bossrace.%.bl3hotfix
	mv $< $@

$(GENDIR)/bossrace.%.bl3hotfix.txt: bossrace.%.bl3hotfix.txt
	mv $< $@

dist: seeds $(GENDIR) $(DISTFILES) $(EXE) ixorabosses.py

doublemurdertime.bl3hotfix: murdertime.py doublemurdertime.csv
	python3 murdertime.py --csv doublemurdertime.csv --output doublemurdertime.bl3hotfix

fastmurdertime.bl3hotfix: murdertime.py fastmurdertime.csv
	python3 murdertime.py --csv fastmurdertime.csv --output fastmurdertime.bl3hotfix

growmurdertime.bl3hotfix: murdertime.py growmurdertime.csv
	python3 murdertime.py --csv growmurdertime.csv --output growmurdertime.bl3hotfix

murdertime: growmurdertime.bl3hotfix fastmurdertime.bl3hotfix doublemurdertime.bl3hotfix

gen:
	rm -f $(MOD)
	make $(MOD)

