        ("Crater's Edge", 'CraterBoss_P', [
            ]),
        ("Bloodsun Canyon", 'Facility_P', [
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge__2.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge__1.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__2.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__8.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__7.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Facility/Facility_Dynamic.Facility_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__6.BP_CrewChallengeComponent_Geranium',
            ]),
        ("Obsidian Forest", 'Forest_P', [
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge__1.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Forest/Forest_Dynamic.Forest_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            ]),
        ("The Blastplains", 'Frontier_P', [
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__3.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge__1.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__5.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__4.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Frontier/Frontier_Dynamic.Frontier_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            ]),
        ("Ashfall Peaks", 'Lodge_P', [
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_Tannery_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__1.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Lodge/Lodge_Dynamic.Lodge_Dynamic:PersistentLevel.BP_IO_CemeteryOpportunity_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            ]),
        ("Vestige", 'Town_P', [
            '/Geranium/Maps/Town/Town_Dynamic.Town_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__3.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Town/Town_Dynamic.Town_Dynamic:PersistentLevel.BP_IO_JakobsJournal_CrewChallenge__0.BP_CrewChallengeComponent_Geranium',
            '/Geranium/Maps/Town/Town_Dynamic.Town_Dynamic:PersistentLevel.BP_IO_CreatureFeature_CrewChallenge_.BP_CrewChallengeComponent_Geranium',
            ]),
