#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Copyright 2021 Christopher J. Kucera
# <cj@apocalyptech.com>
# <http://apocalyptech.com/contact.php>
#
# This Borderlands 3 Hotfix Mod is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This Borderlands 3 Hotfix Mod is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this Borderlands 3 Hotfix Mod.  If not, see
# <https://www.gnu.org/licenses/>.

import sys
import argparse
sys.path.append('../../../python_mod_helpers')
from bl3data.bl3data import BL3Data
from bl3hotfixmod.bl3hotfixmod import Mod, BVC

parser = argparse.ArgumentParser(
        description='Generates Mega TimeSaver XL',
        )
parser.add_argument('-v', '--verbose',
        action='store_true',
        help='Be verbose about what we\'re processing',
        )
args = parser.parse_args()
verbose = args.verbose

mod = Mod('mega_timesaver_xl.bl3hotfix',
        'Mega TimeSaver XL',
        'Apocalyptech',
        [
            "Speeds up animations throughout the game.",
            "",
            "THIS IS A WORK IN PROGRESS!  Please report any game-breaking bugs",
            "to me, but some animations are bound to remain at their original",
            "speed.",
        ],
        lic=Mod.CC_BY_SA_40,
        v='0.9.1',
        cats='qol',
        )

# AnimSequence objects have two attributes of note:
#  1) SequenceLength - total amount of time the sequence is supposed to take.  It
#     looks like just shortening this value works great, but JWP can't currently
#     serialize AnimSequence objects, so we can't automatically pull current values
#     from data.  (FModel *can* serialize them, but we can't automate that like we
#     can with JWP.)
#  2) RateScale - almost certainly this is always just `1`, and this can be set to
#     scale things up easily, to.  So that's what we're going to be using, mostly!

# How much to improve speed
global_scale = 5

# Character movement speed
global_char_scale = 1.4

# Vehicle-animation movement speed
global_vehicle_scale = 2

# Eridian tool speedups
global_eridian_scale = 2

# Minimum serialization version to allow.  Stock JWP doesn't serialize CurveFloats
# correctly, so the mod'll be invalid unless using apocalyptech's fork, of at least
# this version.
min_apoc_jwp_version = 19

# Data obj
data = BL3Data()

mod.header('Item Pickups')

# Defaults:
#  /Game/GameData/GameplayGlobals
#  - MassPickupMaxDelay: 0.075
#  - MassPickupMaxPullAmount: 6
#  - MassPickupMaxTotalDelay: 1.5
#  - MassPickupMinDelay: 0.06
#  - MassPickupRadius: 400
#  /Game/Pickups/_Shared/_Design/AutoLootContainerPickupFlyToSettings
#  - MaxLifetime: 2.5
#  - SpinSpeed: (pitch=0, yaw=200, roll=200)
#  - LinearSpeed: 750
#  - LinearAcceleration: 650

mod.comment('Mass Pickup Delay (honestly not sure if these have much, if any, effect)')
for var, value in [
        ('MassPickupMaxDelay', 0.075/3),
        ('MassPickupMaxTotalDelay', 1.5/3),
        ('MassPickupMinDelay', 0.06/3),
        ]:
    mod.reg_hotfix(Mod.PATCH, '',
            '/Game/GameData/GameplayGlobals',
            var,
            round(value, 6))
mod.newline()

mod.comment('Pickup flight speeds (likewise, I suspect many of these don\'t actually do much)')
mod.comment('The `AutoLootContainer` ones definitely do help, at least.')
for obj_name in [
        'AutoLootContainerPickupFlyToSettings',
        'ContainerEchoLogPickupFlyToSettings',
        'ContainerPickupFlyToSettings',
        'DroppedEchoLogPickupFlyToSettings',
        'DroppedPickupFlyToSettings',
        ]:
    full_obj_name = f'/Game/Pickups/_Shared/_Design/{obj_name}'
    obj_data = data.get_exports(full_obj_name, 'PickupFlyToData')[0]
    if 'LinearSpeed' in obj_data:
        speed = obj_data['LinearSpeed']
    else:
        # This seems to be the default
        speed = 1000
    mod.reg_hotfix(Mod.PATCH, '',
            full_obj_name,
            'LinearSpeed',
            speed*2)
    mod.reg_hotfix(Mod.PATCH, '',
            full_obj_name,
            'LinearAcceleration',
            obj_data['LinearAcceleration']*2)
mod.newline()

# Direct animation speedups
mod.header('Containers: Simple Animation Speedups')

# Initial object list generated by:
#     find $(find . -type d -name Lootables) -name "AS_*.uasset" | sort -i | cut -d. -f2 | grep -vE '(Idle|Flinch|_Closed|_Opened)'
# ... while at the root of a data unpack
for obj_name in [
        '/Alisma/Lootables/Hyperion/AmmoCase/Animation/AS_Open_In',
        '/Alisma/Lootables/Hyperion/LootCase/Animation/AS_Hyp_Misc2_Opening',
        '/Alisma/Lootables/Hyperion/PortaPotty/Animation/AS_Open_IN_Poor',
        '/Alisma/Lootables/Hyperion/PortaPotty/Animation/AS_Open_IN',
        '/Alisma/Lootables/Hyperion/PortaPotty/Animation/AS_Open',
        '/Alisma/Lootables/Hyperion/RedChest/Animation/AS_HypRedChest_Open',
        '/Alisma/Lootables/Hyperion/SingleCase/Animation/AS_SingleCase_In',
        '/Alisma/Lootables/Hyperion/WeaponBox/Animation/AS_HypWeaponLocker_Open',
        '/Dandelion/Lootables/Hyperion/AmmoCase/Animation/AS_Open_In',
        '/Dandelion/Lootables/Hyperion/BlackJackChest/Animation/AS_Open_Draw_card_01',
        '/Dandelion/Lootables/Hyperion/BlackJackChest/Animation/AS_Open_Draw_card_03',
        '/Dandelion/Lootables/Hyperion/BlackJackChest/Animation/AS_Open_Draw_card_04',
        '/Dandelion/Lootables/Hyperion/BlackJackChest/Animation/AS_Open_In',
        '/Dandelion/Lootables/Hyperion/LootCase/Animation/AS_Hyp_Misc2_Opening',
        '/Dandelion/Lootables/Hyperion/PortaPotty/Animation/AS_Open_IN',
        '/Dandelion/Lootables/Hyperion/RedChest/Animation/AS_HypRedChest_Open',
        '/Dandelion/Lootables/Hyperion/SingleCase/Animation/AS_SingleCase_In',
        '/Dandelion/Lootables/Hyperion/WeaponBox/Animation/AS_HypWeaponLocker_Open',
        '/Game/Lootables/Atlas/Chest_Red/Animation/AS_Open',
        '/Game/Lootables/Atlas/Crate_Ammo/Animation/AS_Open',
        '/Game/Lootables/COV/Bandit_CardboardBox/Animation/AS_Open_Fast',
        '/Game/Lootables/COV/Bandit_CardboardBox/Animation/AS_Open_Slow',
        '/Game/Lootables/COV/Chest_Red/Animation/AS_Open_v1',
        '/Game/Lootables/COV/Chest_White/Animations/AS_Open',
        '/Game/Lootables/COV/Crate_Ammo/Animation/AS_Open_v1',
        '/Game/Lootables/COV/Crate_OfferingBox/Animation/AS_Open_v1',
        '/Game/Lootables/Eridian/Chest_Red/Animation/AS_Open',
        '/Game/Lootables/Eridian/Chest_White/Animation/AS_Open',
        '/Game/Lootables/Eridian/Crate_Ammo/Animation/AS_Open',
        '/Game/Lootables/_Global/Chest_Gold/Animation/AS_Close',
        '/Game/Lootables/_Global/Chest_Gold/Animation/AS_Open',
        '/Game/Lootables/_Global/Chest_Trials/Animation/AS_Open',
        '/Game/Lootables/_Global/Chest_Trials/Animation/AS_Open_v2',
        '/Game/Lootables/_Global/Chest_Typhon/Animation/AS_Open',
        '/Game/Lootables/_Global/Crate_Ammo/Animations/AS_Open',
        '/Game/Lootables/_Global/Dumpster_Small/Animation/AS_Open',
        '/Game/Lootables/_Global/Locker_Generic/Animation/AS_Open_Misnamed',
        '/Game/Lootables/_Global/Locker_Generic/Animation/AS_Open',
        '/Game/Lootables/Industrial/Cash_Register/Animation/AS_Open',
        '/Game/Lootables/Industrial/Lock_Box/Animations/AS_Open',
        '/Game/Lootables/Industrial/Machine_Washing/Animation/AS_Open',
        '/Game/Lootables/Industrial/PortaPotty/Animation/AS_BlastOff',
        '/Game/Lootables/Industrial/PortaPotty/Animation/AS_Open_v1',
        '/Game/Lootables/Industrial/Refrigerator/Animation/AS_Open',
        '/Game/Lootables/Industrial/Safe/Animation/AS_Open',
        '/Game/Lootables/Industrial/Strong_Box/Animation/AS_Open',
        '/Game/Lootables/Industrial/Toilet/Animations/AS_Open',
        '/Game/Lootables/Industrial/Trunk_Car/Animation/AS_Open_Backfire',
        '/Game/Lootables/Industrial/Trunk_Car/Animation/AS_Open',
        '/Game/Lootables/Jakobs/Chest_Red/Animation/AS_Open',
        '/Game/Lootables/Jakobs/Chest_White/Animation/AS_Open',
        '/Game/Lootables/Jakobs/GunRack/Animation/AS_Open',
        '/Game/Lootables/Jakobs/Lockbox/Animation/AS_Open',
        '/Game/Lootables/Jakobs/MusicBox/Animation/AS_Open',
        '/Game/Lootables/Maliwan/Ammo/Animation/AS_Open_v1',
        '/Game/Lootables/Maliwan/Chest_Red/Animation/AS_Open',
        '/Game/Lootables/Maliwan/Chest_White/Animation/AS_Open',
        '/Game/Lootables/Mission_Specific/Rock_HideAKey/Animation/AS_Open',
        '/Game/Lootables/Pandora/Mailbox/Animation/AS_Open_v1',
        '/Game/Lootables/Pandora/Mailbox/Animation/AS_Open_v2',
        '/Game/Lootables/Pandora/TrashCan/Model/Animation/AS_Open_v1',
        '/Game/Lootables/Pandora/TrashCan/Model/Animation/AS_Open_v2',
        # This one doesn't show up in the find command above...
        '/Game/Lootables/Pandora/TrashCan/Model/Animation/Open_v3',
        '/Game/Lootables/Pandora/Varkid_Lootable/_Shared/Animation/AS_Open_Burst',
        '/Game/Lootables/Pandora/Varkid_Lootable/_Shared/Animation/AS_Open',
        '/Game/Lootables/Promethea/Cooler/Animation/AS_Open',
        '/Game/Lootables/Promethea/Gashapon/Animations/AS_Open',
        '/Game/Lootables/Promethea/Ratch_pile/Animation/Ratch_Pile_Large/AS_Open',
        '/Game/Lootables/Promethea/Ratch_pile/Animation/Ratch_Pile_Large_Open/AS_Open',
        '/Game/Lootables/Promethea/Ratch_pile/Animation/Ratch_Pile_Small/AS_Open',
        '/Game/Lootables/Promethea/Ratch_pile/Animation/Ratch_Pile_Small_Open/AS_Open',
        '/Game/Lootables/Promethea/Toilet/Animation/AS_Open_v1',
        '/Geranium/Lootables/CashRegister/Animation/AS_Open',
        '/Geranium/Lootables/Chest_DeadDrop/Model/Anims/AS_Open_Ger',
        '/Geranium/Lootables/_Design/Classes/AS_Open_MoneyBack',
        '/Geranium/Lootables/Machine_Washing/Animation/AS_Close',
        '/Geranium/Lootables/Outhouse/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/Carcass/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/Cultists/AmmoCrate/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/Cultists/RedChest/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/Cultists/UniqueChest/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/Cultists/WhiteChest/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/FishingNet/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/FrostBiters/AmmoCrate/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/FrostBiters/RedChest/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/FrostBiters/TreasureBox/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/FrostBiters/WhiteChest/Animation/AS_Open',
        '/Hibiscus/InteractiveObjects/Lootables/SingingFish/Animation/AS_Sing_Sing',
        '/Hibiscus/InteractiveObjects/Lootables/SingingFish/Animation/AS_Sing_Spit',
        '/Hibiscus/InteractiveObjects/Lootables/SingleMushroom/AS_Mush_Open',
        '/Hibiscus/InteractiveObjects/Lootables/TentacleToilet/Animation/AS_TentacleToilet_OpenAndDropWeapon',
        ]:

    mod.reg_hotfix(Mod.LEVEL, 'MatchAll',
            obj_name,
            'RateScale',
            global_scale)

mod.newline()

mod.header('Eridian Tools')

for anim_obj in [
        '/PlayerCharacters/_Shared/Animation/Skills/VaultRewards/1st/AS_Analyzer_Use',
        '/PlayerCharacters/_Shared/Animation/Skills/VaultRewards/1st/AS_Eridian_Melee_Small',
        '/PlayerCharacters/_Shared/Animation/Skills/VaultRewards/1st/Eridian_Analyzer/AS_Analyzer_Use',
        '/PlayerCharacters/Beastmaster/_Shared/Animation/Skills/VaultRewards/3rd/AS_Analyzer_Use',
        '/PlayerCharacters/Beastmaster/_Shared/Animation/Skills/VaultRewards/3rd/AS_Eridian_Melee_Small',
        '/PlayerCharacters/Gunner/_Shared/Animation/Skills/VaultRewards/3rd/AS_Analyzer_Use',
        '/PlayerCharacters/Gunner/_Shared/Animation/Skills/VaultRewards/3rd/AS_Eridian_Melee_Small',
        '/PlayerCharacters/Operative/_Shared/Animation/Skills/VaultRewards/3rd/AS_Analyzer_Use',
        '/PlayerCharacters/Operative/_Shared/Animation/Skills/VaultRewards/3rd/AS_Eridian_Melee_Small',
        '/PlayerCharacters/SirenBrawler/_Shared/Animation/Skills/VaultRewards/3rd/AS_Analyzer_Use',
        '/PlayerCharacters/SirenBrawler/_Shared/Animation/Skills/VaultRewards/3rd/AS_Eridian_Melee_Small',
        ]:

    mod.reg_hotfix(Mod.PATCH, '',
            anim_obj,
            'RateScale',
            global_eridian_scale)

mod.newline()

# Vehicles!
#
# Command for these: find $(find . -name Vehicles -o -name Vehicle) -name "AS_*.uasset" | sort -i | cut -d. -f2 | grep -vE '(Idle|Flinch|Death|Land|Emperor)'
# ... though it's been trimmed quite heavily and reorganized quite a bit.
for vehicle_cat, hf_trigger, vehicle_scale, sequencelength_scale, obj_names in [
        ('Player Basic Interactions (always loaded objects)', Mod.PATCH, global_vehicle_scale, global_vehicle_scale, [
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Entry',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_R',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Exit',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_FB',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_LR',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_UD',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Shared/AS_Base_Pose',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Enter',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Exit',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Entry',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_R',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Exit',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_FB',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_LR',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_UD',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Shared/AS_Base_Pose',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Enter',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Exit',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/CraneConsole/AS_Console_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Entry',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_R',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Exit',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_FB',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_LR',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_UD',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Shared/AS_Base_Pose',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Enter',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Exit',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Crane/AS_Console_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Crane/AS_Console_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Entry',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/GunnersNest/AS_GunnersNest_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Standing_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_Exit_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Turret_to_Driver',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_Exit_R',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Enter_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/RollerCoaster/AS_RollerCoaster_Exit',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_FB',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_LR',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Shared/AS_ADD_UD',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Shared/AS_Base_Pose',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_BL_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_BR_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_to_Turret',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel_Backward',
            #'/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Driver_TurnWheel',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Enter',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_Exit',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Turret_to_Driver',
            ]),
        ('Player Basic Interactions (level-based objects)', Mod.LEVEL, global_vehicle_scale, global_vehicle_scale, [
            '/Dandelion/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Enter',
            '/Dandelion/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Exit',
            '/Dandelion/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Enter',
            '/Dandelion/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Exit',
            '/Dandelion/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Enter',
            '/Dandelion/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Hyperhoop/AS_Hyperhoop_Exit',
            '/Dandelion/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicle/Hyperhoop/AS_Hyperhoop_Enter',
            '/Dandelion/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicle/Hyperhoop/AS_Hyperhoop_Exit',
            #'/Dandelion/Vehicles/Hyperloop/Animation/AS_Banking_Left',
            #'/Dandelion/Vehicles/Hyperloop/Animation/AS_Banking_Right',
            ]),
        ('Hijack Interactions - Player', Mod.PATCH, global_vehicle_scale, global_vehicle_scale, [
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Hijack_Driver_L',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Revolver/AS_Hijack_Driver_R',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Beastmaster/_Shared/Animation/Generic/Vehicles/Technical/AS_Hijack_Driver',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_HiJack_Driver_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_HiJack_Driver_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_HiJack_Driver_L',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Revolver/AS_HiJack_Driver_R',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Gunner/_Shared/Animation/Generic/Vehicles/Technical/AS_HiJack_Driver',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_HiJack_Driver_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Hijack_Driver_L',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Revolver/AS_Hijack_Driver_R',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/Operative/_Shared/Animation/Generic/Vehicles/Technical/AS_HiJack_Driver',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_HiJack_Driver_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_HiJack_Driver_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_HiJack_Driver_L',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Revolver/AS_HiJack_Driver_R',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/PlayerCharacters/SirenBrawler/_Shared/Animation/Generic/Vehicles/Technical/AS_HiJack_Driver',
            ]),
        ('NPC Basic Interactions', Mod.CHAR, global_vehicle_scale, global_vehicle_scale, [
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_L',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Exit_L',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Exit_R',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Driver_TurnWheel',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapB_Attack',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapB_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapB_Unstable',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapF_Attack',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapF_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapF_Unstable',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_L',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_L',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Driver_Exit_L',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Driver_TurnWheel',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_Base_Pose',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_VehicleLeap_Enter',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_BL_Enter',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_BL_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_BR_Enter',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_BR_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Driver_Enter',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Driver_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Driver_TurnWheel',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFL_Attack',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFL_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFL_Unstable',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFR_Attack',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFR_Exit',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFR_Unstable',
            #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Turret_Enter',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Turret_Exit',
            #'/Game/Enemies/Punk_Male/_Shared/Animation/Vehicles/Technical/AS_BL_Enter',
            '/Game/Enemies/Punk_Male/_Shared/Animation/Vehicles/Technical/AS_BL_Exit',
            #'/Game/Enemies/Punk_Male/_Shared/Animation/Vehicles/Technical/AS_BR_Enter',
            '/Game/Enemies/Punk_Male/_Shared/Animation/Vehicles/Technical/AS_BR_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_L',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Exit_L',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Driver_TurnWheel',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_L',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_L',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_Driver_Exit_L',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_Driver_Exit_R',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_Driver_TurnWheel',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Shared/AS_Base_Pose',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_BL_Enter',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_BL_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_BR_Enter',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_BR_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Driver_Enter',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Driver_Exit',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Driver_TurnWheel',
            #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Turret_Enter',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Turret_Exit',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/MannedTurret/AS_Standing_Exit',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Shared/AS_Base_Pose',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_BL_Enter',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_BL_Exit',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_BR_Enter',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_BR_Exit',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_Driver_Enter',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_Driver_Exit',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_Driver_TurnWheel',
            #'/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_Turret_Enter',
            '/Game/NonPlayerCharacters/AtlasSoldier/Animation/Vehicles/Technical/AS_Turret_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_L',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Enter_R',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_L',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Exit_R',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_L',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Enter_R',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Driver_Exit_L',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Driver_TurnWheel',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_L',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Enter_R',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_L',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Revolver/AS_Driver_Enter_R',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Revolver/AS_Driver_Exit_L',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Revolver/AS_Driver_TurnWheel',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Shared/AS_Base_Pose',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_AllyDriver_Brace',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_AllyDriver_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_AllyDriver_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_BL_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_BL_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_BR_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_BR_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_Driver_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_Driver_Exit',
            #'/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_Driver_TurnWheel',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_Turret_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/AS_Turret_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/Passive/AS_BL_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/Passive/AS_BL_Exit',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/Passive/AS_BR_Enter',
            '/Game/NonPlayerCharacters/_Generic/_Shared/Animation/Vehicles/Technical/Passive/AS_BR_Exit',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Revolver/AS_Driver_Enter_L',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Revolver/AS_Driver_Enter_R',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Revolver/AS_Driver_Exit_L',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Revolver/AS_Driver_TurnWheel',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/NonPlayerCharacters/Lilith/Animation/Vehicles/Shared/AS_Base_Pose',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Shared/AS_ADD_FB',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Shared/AS_ADD_LR',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Shared/AS_ADD_UD',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Shared/AS_AllyPassenger_BasePose',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Attack',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_CC',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_CD',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_CU',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_LC',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_LD',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_LU',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_RC',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_RD',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_AO_RU',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_BackLeft_Attack',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Brace',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Charge_In',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Enter',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Exit',
            #'/Game/NonPlayerCharacters/Maya/Animation/Vehicle/Technical/AS_AllyPassenger_Shield',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Shared/AS_ADD_FB',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Shared/AS_ADD_LR',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Shared/AS_ADD_UD',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Shared/AS_AllyPassenger_BasePose',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Technical/AS_AllyDriver_Brace',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Technical/AS_AllyDriver_Enter',
            #'/Game/NonPlayerCharacters/Vaughn/Animation/Vehicles/Technical/AS_AllyDriver_Exit',
            ]),
        ('Hijack Interactions - Enemies', Mod.CHAR, global_vehicle_scale, global_vehicle_scale, [
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_HiJack_Driver_L',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_HiJack_Driver_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Hijack_Driver_L',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Revolver/AS_Hijack_Driver_R',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_HiJacked_Ejected',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Hijack_Driver',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Sitting_L',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Sitting_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Hijack_Standing',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_HiJack_Driver_L',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_HiJack_Driver_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Hijack_Driver_to_Turret',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_HiJack_Driver_L',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Revolver/AS_HiJack_Driver_R',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Hijack_Driver_to_Turret',
            '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_HiJack_Driver',
            ]),
        #('Other (unused, currently)', Mod.LEVEL, global_vehicle_scale, global_vehicle_scale, [
        #    '/Game/Vehicles/Carnivora/Animation/AS_Entry_drop',
        #    '/Game/Vehicles/Carnivora/Animation/AS_Entry_idle',
        #    '/Game/Vehicles/Carnivora/Animation/AS_Magnet_Drop',
        #    '/Game/Vehicles/Outrunner/Animation/AS_Outrunner_GearShift_Down',
        #    '/Game/Vehicles/Outrunner/Animation/AS_Outrunner_GearShift_Up',
        #    '/Game/Vehicles/Outrunner/Animation/AS_Vehicle_Spawn_DoorCargoSplit',
        #    '/Game/Vehicles/Revolver/Animation/AS_Gunner_Enter_L',
        #    '/Game/Vehicles/Revolver/Animation/AS_Gunner_Exit_L',
        #    '/Game/Vehicles/Revolver/Animation/AS_Revolver_GearShift_Down',
        #    '/Game/Vehicles/Revolver/Animation/AS_Revolver_GearShift_Up',
        #    '/Game/Vehicles/Revolver/Animation/AS_Vehicle_Spawn_DoorCargoSplit',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_BrakeBounce_B',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_BrakeBounce_F',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_GearShift_Down',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_GearShift_Up',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_Gunner_Driver_Enter',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_Gunner_Driver_Exit',
        #    '/Game/Vehicles/Technical/Animation/AS_Technical_Hit_HoodDown',
        #    '/Game/Vehicles/Technical/Animation/AS_Vehicle_Spawn_DoorCargoSplit',
        #    '/Game/Vehicles/Technical/Parts/JetBooster/AS_JetBooster_Anim',
        #    '/Game/Vehicles/Technical/Parts/MeatGrinder/AS_Veh_Techincal_MeatGrinder',
        #    '/Game/Vehicles/Technical/Parts/ToxicBooster/AS_Veh_Technical_ToxicBooster',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/BouncingLasers/AS_BouncingLasers_Shoot',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/Catapult/AS_Launch',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/Catapult_TireBombs/AS_Launch',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/DualFlakCanon/AS_Veh_Turret_DualFlakCanon_Shoot_Primary',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/HeavyMissile/AS_HeavyMissile_Shoot',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/MachineGun/AS_MachineGun_Shoot_Heavy',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/MachineGun/AS_MachineGun_Shoot',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/PulseRifle/Animation/AS_PulseRifle_DualTurrets_Deploy_In',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/PulseRifle/Animation/AS_PulseRifle_DualTurrets_Deploy_Out',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/PulseRifle/Animation/AS_PulseRifle_DualTurrets_Retracted',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/PulseRifle/Animation/AS_PulseRifle_Shoot',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/RodLauncher/AS_Veh_Turret_RodLauncher_Shoot_Primary',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/SawBlade/AS_Veh_Turret_SawBlade_Shoot_Primary',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/ShotgunMissile/AS_ShotgunMissile_Shoot',
        #    '/Game/Vehicles/VehicleWeapons/_Shared/WeaponModels/SwarmerMissile/AS_SwarmerMissile_Shoot',
        #    '/Geranium/NonPlayerCharacters/Dakota/Animation/Vehicles/JetBeast/AS_Driver_Exit_L',
        #    '/Geranium/Vehicles/Horse/Animation/Cannon/AS_Fire',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapB_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_LeapF_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Idle',
        #    #'/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_ADD_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Shared/AS_VehicleLeap_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFL_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_LeapFR_Idle',
        #    '/Game/Enemies/Psycho_Male/_Shared/Animation/Vehicles/Technical/AS_Turret_Idle',
        #    '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Sitting_Idle',
        #    '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/MannedTurret/AS_Standing_Idle',
        #    '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Outrunner/AS_Turret_Idle',
        #    #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Shared/AS_ADD_Idle',
        #    #'/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_BL_Idle',
        #    '/Game/Enemies/Trooper/_Shared/Animation/Vehicles/Technical/AS_Turret_Idle',
        #    ]),
        ]:

    mod.header('Vehicle Speedups: {}'.format(vehicle_cat))

    if hf_trigger == Mod.PATCH:
        hf_target = ''
    else:
        hf_target = 'MatchAll'

    for obj_name in obj_names:

        if verbose:
            print('Processing {}'.format(obj_name))

        # First the RateScale; happens regardless of AnimSequence contents
        mod.comment(obj_name)
        mod.reg_hotfix(hf_trigger, hf_target,
                obj_name,
                'RateScale',
                vehicle_scale)

        # Now we get into AnimSequence specifics.  This'll happen so long as there's
        # data which makes sense to alter (ie: non-`0` values)
        as_data = data.get_exports(obj_name, 'AnimSequence')[0]
        if 'Notifies' in as_data:
            for idx, notify in enumerate(as_data['Notifies']):
                for var in ['SegmentBeginTime', 'SegmentLength', 'LinkValue']:
                    if var in notify and notify[var] != 0:
                        mod.reg_hotfix(hf_trigger, hf_target,
                                obj_name,
                                'Notifies.Notifies[{}].{}'.format(idx, var),
                                round(notify[var]/vehicle_scale, 6))

                # If we have targets inside EndLink, process that, too.  (So far, it doesn't
                # look like any animations we touch actually have anything here.)
                endlink = notify['EndLink']
                if 'export' not in endlink['LinkedMontage'] \
                        or endlink['LinkedMontage']['export'] != 0 \
                        or 'export' not in endlink['LinkedSequence'] \
                        or endlink['LinkedSequence']['export'] != 0:
                    for var in ['SegmentBeginTime', 'SegmentLength', 'LinkValue']:
                        if var in endlink and endlink[var] != 0:
                            mod.reg_hotfix(hf_trigger, hf_target,
                                    obj_name,
                                    'Notifies.Notifies[{}].EndLink.{}'.format(idx, var),
                                    round(endlink[var]/vehicle_scale, 6))

        # Finally: SequenceLength.  This one's a bit weird, which is why we're letting categories
        # decide if they want to use alt scalings.  For player animations for entering/leaving vehicles
        # (or for changing seats), if SequenceLength is scaled at the same scale as the rest of the
        # animations, the animation "freezes" before it's fully complete, and the player just jerks
        # to their final spot once the appropriate time has elapsed.  Contrariwise, if we *don't*
        # scale SequenceLength down, you end up with a period of time where you can't interact with
        # the vehicle at all, like driving, leaving, or changing seats again.  In the end, I settled
        # on just using the global vehicle scale for all categories here, but if I want to tweak
        # something in the future, at least it's easy enough to do so.
        if 'SequenceLength' in as_data:
            mod.reg_hotfix(hf_trigger, hf_target,
                    obj_name,
                    'SequenceLength',
                    round(as_data['SequenceLength']/sequencelength_scale, 6))

        # ... aaaand we're done.
        mod.newline()

# Default here is 2.36; not gonna bother dynamically reading it for a single object.
# This honestly doesn't really do much for you -- the vehicle is basically fully
# operable as soon as it starts, anyway.  Still, it makes things look a little
# snappier.
mod.header('Catch-A-Ride Digistruct Time')
mod.reg_hotfix(Mod.LEVEL, 'MatchAll',
        '/Game/GameData/StatusEffects/CoordinatedEffects/Vehicles/BP_CE_Veh_Digistruct_In.Default__BP_CE_Veh_Digistruct_In_C',
        'Duration',
        0.5)
mod.newline()

checked_ver = False
for category, obj_names in [
        ('Doors', [
            # find $(find . -name Doors) -name "IO_*.uasset" | sort -i | cut -d. -f2 | grep -v Parent
            '/Alisma/InteractiveObjects/General/Doors/IO_Door_130x250_SlideLeft_Hyperion',
            '/Alisma/InteractiveObjects/General/Doors/IO_Door_130x250_SlideUp_Prison',
            '/Alisma/InteractiveObjects/General/Doors/IO_Door_400x400_SlideDown_Hyp',
            '/Alisma/InteractiveObjects/General/Doors/IO_DoubleDoor_SlideUp_Hyp',
            # This one's just part of a cutscene; stays open otherwise
            #'/Dandelion/InteractiveObjects/Doors/IO_Door_800x600_SlideUp_TrashTownMainEntry',
            '/Dandelion/InteractiveObjects/Doors/IO_Door_Hyperion_DoubleGlass',
            '/Dandelion/InteractiveObjects/Doors/IO_Door_Hyperion_Double',
            '/Dandelion/InteractiveObjects/Doors/IO_Door_Hyperion_Single_TricksyNickLoot',
            '/Dandelion/InteractiveObjects/Doors/IO_Door_Hyperion_Single',
            # No timing parameters on these two
            #'/Dandelion/InteractiveObjects/Doors/PrizeDoors/IO_Door_Hyperion_Single_Prize',
            #'/Dandelion/InteractiveObjects/Doors/PrizeDoors/IO_Switch_Hyp_Button_V1_Prize',
            '/Game/InteractiveObjects/Doors/Atlas/_Design/IO_Door_130x250_Atlas_ShelfDoor',
            '/Game/InteractiveObjects/Doors/Atlas/_Design/IO_Door_400x400_SlideLeftAndRight_AtlasHQ_Generic',
            '/Game/InteractiveObjects/Doors/Atlas/_Design/IO_Door_AtlasHQ_Elevator_Exterior',
            '/Game/InteractiveObjects/Doors/Atlas/_Design/IO_Door_AtlasHQ_Elevator_Interior_Short',
            '/Game/InteractiveObjects/Doors/Atlas/_Design/IO_Door_AtlasHQ_Elevator_Interior_Tall',
            # No timing parameters
            #'/Game/InteractiveObjects/Doors/City/_Design/IO_Door_1630x600_MeltHole_GiantDoor',
            '/Game/InteractiveObjects/Doors/City/_Design/IO_Door_1630x600_SlideUp_GiantDoor',
            '/Game/InteractiveObjects/Doors/CoV/_Design/IO_Door_CoV_SwingingGate_V1',
            '/Game/InteractiveObjects/Doors/Default/1000x600/IO_Door_1000x600_SlideLeftAndRight',
            '/Game/InteractiveObjects/Doors/Default/800x600/IO_Door_800x600_SlideUp',
            '/Game/InteractiveObjects/Doors/Eden_6/_Design/IO_Door_130x250_Rotate_Watership',
            '/Game/InteractiveObjects/Doors/Eden_6/_Design/IO_Door_400x400_SlideLeftAndRight_Eden6_Generic_IronBear',
            '/Game/InteractiveObjects/Doors/Eden_6/_Design/IO_Door_Custom_Watership_RotateUp',
            '/Game/InteractiveObjects/Doors/Eden_6/_Design/IO_Door_Marshfields_Custom_HiddenSpyDoor',
            '/Game/InteractiveObjects/Doors/Eden_6/_Design/IO_Door_Watership_Custom_LabDoor',
            '/Game/InteractiveObjects/Doors/Eridian/_Design/IO_Door_1000x600_SlideLeftAndRight_Eridian_Generic',
            '/Game/InteractiveObjects/Doors/Eridian/_Design/IO_Door_400x400_SlideUp_Eridian_Generic',
            '/Game/InteractiveObjects/Doors/Eridian/_Design/IO_Door_Large_SlideUp_Eridian_Generic1',
            '/Game/InteractiveObjects/Doors/Global/_Design/IO_Door_ScalableForcefield',
            '/Game/InteractiveObjects/Doors/Industrial/_Design/IO_Door_1000x600_SlideUp_Industrial_Generic',
            '/Game/InteractiveObjects/Doors/Industrial/_Design/IO_Door_400x400_SlideUp_Industrial_Generic',
            '/Game/InteractiveObjects/Doors/Maliwan/_Design/IO_Door_Custom_Rotate_2Piece_Maliwan',
            # No timing parameters for these two
            #'/Game/InteractiveObjects/Doors/Maliwan/_Design/IO_Door_Maliwan_Shield_Large',
            #'/Game/InteractiveObjects/Doors/Maliwan/_Design/IO_Door_Maliwan_Shield',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_130x250_Rotate_Mansion_NoFrame',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_130x250_Rotate_Mansion',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_400x400_2Piece_Atrium_IronBearDoor',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_400x400_Rotate_2Piece_BustOpenMansionDoor',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_400x400_Rotate_2Piece_Generic_IronBearDoor',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_CustomSize_Rotate_2Piece_IronGate',
            '/Game/InteractiveObjects/Doors/Mansion/_Design/IO_Door_Mansion_Bookcase_500x500_SlideRight',
            # No timing parameters
            #'/Game/InteractiveObjects/Doors/Mine/_Design/IO_Door_400x400_SlideUp_MinerDetails_DestroyableDoor',
            '/Game/InteractiveObjects/Doors/Monastery/_Design/IO_Door_130x250_SlideDown_Monastery',
            '/Game/InteractiveObjects/Doors/Monastery/_Design/IO_Door_400x400_LeftAndRight_Monastery_1',
            '/Game/InteractiveObjects/Doors/Monastery/_Design/IO_Door_400x400_LeftAndRight_Monastery_SpecialTitleCard',
            # No timing parameters
            #'/Game/InteractiveObjects/Doors/Monastery/_Design/IO_Door_400x400_SlideUp_Monastery_TombDoor',
            '/Game/InteractiveObjects/Doors/Monastery/_Design/IO_Door_800x600_SlideUp_Monastery_Courtyard',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_130x250_Rotate_Motorcade_OrphanageDoor',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_130x250_SlideUp_Motorcade_BanditHideoutDoor',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_400x400_Motorcade_RotateUp',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_800x600_Motorcade_Rotate',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_800x600_SlideLeftAndRight_Motorcade_BarnDoor',
            '/Game/InteractiveObjects/Doors/Motorcade/_Design/IO_Door_SkagFarm_400x400_RotateUp',
            # Leave this one alone, doesn't ever impede movement.
            #'/Game/InteractiveObjects/Doors/Nekro/_Design/IO_Door_Custom_CloakedRock',
            # No timing parameters for these two
            #'/Game/InteractiveObjects/Doors/Nekro/_Design/IO_Door_Custom_Nekro_Crypt_Small',
            #'/Game/InteractiveObjects/Doors/Nekro/_Design/IO_Door_Custom_Nekro_Crypt',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_1000x600_SlideLeftAndRight_Pandora',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_1000x600_SlideUp_Pandora_Generic',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_130x250_Lynchwood_SlideLeft1',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_1630x1200_SlideUp_SecretGarageDoor',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_400x400_SlideUp_Pandora_Generic',
            # No timing parameters
            #'/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_CustomSize_Rotate_2Piece_CovRecruitmentDoor_Small',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_CustomSize_Rotate_2Piece_CovRecruitmentDoor',
            # Only main TimelineLength found; skip it for now...
            #'/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_CustomSize_Rotate_2Piece_MagnetDoor',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_CustomSize_RotateUp_Pandora_TunnelCap',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_CustomSize_SlideUp_Pandora_CarHook',
            '/Game/InteractiveObjects/Doors/Pandora/_Design/IO_Door_Pandora_130x250_Rotate',
            '/Game/InteractiveObjects/Doors/Prison/_Design/IO_Door_130x250_SlideUp_PrisonBars',
            '/Game/InteractiveObjects/Doors/Prison/_Design/IO_Door_130x250_SlideUp_PrisonMetal',
            '/Game/InteractiveObjects/Doors/Prison/_Design/IO_Door_400x400_SlideUpAndDown_Prison',
            '/Game/InteractiveObjects/Doors/Prison/_Design/IO_Door_400x400_SlideUp_Prison',
            '/Game/InteractiveObjects/Doors/Promethea/_Design/IO_Door_1000x600_SlideUp_Promethea_Generic',
            # No timing parameters
            #'/Game/InteractiveObjects/Doors/Promethea/_Design/IO_Door_1000x600_SlideUp_Promethea_Vehicle2',
            '/Game/InteractiveObjects/Doors/Promethea/_Design/IO_Door_400x400_SlideUp_Promethea_Generic',
            '/Game/InteractiveObjects/Doors/SpaceShips/_Design/IO_Door_130x250__SlideUp_Spaceships_Generic',
            '/Game/InteractiveObjects/Doors/SpaceShips/_Design/IO_Door_400x400_SlideDown_Spaceships_Generic',
            '/Game/InteractiveObjects/Doors/SpaceShips/_Design/IO_Door_400x400_SlideRight_Spaceships_Generi',
            '/Game/InteractiveObjects/Doors/SpaceShips/_Design/IO_Door_400x400_SlideUp_Spaceships_Generic',
            '/Game/PatchDLC/BloodyHarvest/InteractiveObjects/Doors/_Design/IO_Door_BloodyHarvest_Rotate_2Piece_IronGate',
            # No timing parameters for these two
            #'/Game/PatchDLC/Event2/InteractiveObjects/Doors/_Design/IO_Door_400x400_Rotate_2Piece_Generic_IronBearDoor_Cartels',
            #'/Game/PatchDLC/Event2/InteractiveObjects/Doors/_Design/IO_Door_CustomSize_Rotate_2Piece_IronGate_CartelsVar',
            '/Game/PatchDLC/Ixora/InteractiveObjects/Doors/IO_Door_130x250_SlideUp_Motorcade_BanditHideoutDoor_GearUp',
            # No timing parameters
            #'/Game/PatchDLC/Ixora/InteractiveObjects/Doors/IO_Door_400x400_SlideUp_Industrial_Generic_GearUp',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_130x250_SlideUp_FacilityPlayerDoor1',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_400x400_SlideLeftAndRight_FacilityIBDoor2',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_400x400_SlideUp_FacilityIBDoor1',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_800x600_SlideUpAndDown_FacilitySmallVehicleDoor2',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_800x600_SlideUp_FacilitySmallVehicleDoor',
            '/Geranium/InteractiveObjects/Doors/Facility/_Design/IO_Door_800x800_Rotate_IBArenaDoor',
            # No timing parameters
            #'/Geranium/InteractiveObjects/Doors/Forest/_Design/IO_Door_Forest_TrainCrash',
            '/Geranium/InteractiveObjects/Doors/Frontier/_Design/IO_Door_130x250_SlideUp_FrontierPlayerDoor',
            '/Geranium/InteractiveObjects/Doors/Frontier/_Design/IO_Door_400x400_SlideLeftAndRight_FrontierIBDoor',
            '/Geranium/InteractiveObjects/Doors/Frontier/_Design/IO_Door_400x400_VaultDoor',
            '/Geranium/InteractiveObjects/Doors/IO_Door_130x250_SaloonDoor',
            '/Geranium/InteractiveObjects/Doors/Lodge/_Design/IO_Door_400x400_Rotate_2Piece_Lodge_IronBear',
            '/Geranium/InteractiveObjects/Doors/Lodge/_Design/IO_Door_Lodge_TreasureRoom',
            '/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Factory/IO_Hib_Door_800x600_Factory',
            # No timing parameters for these two
            #'/Hibiscus/InteractiveObjects/Systems/Doors/_Design/MansionReskin/IO_Hib_Door2_400x400',
            #'/Hibiscus/InteractiveObjects/Systems/Doors/_Design/MansionReskin/IO_Hib_Door_400x400',
            # This one can't be serialized currently, for some reason.
            #'/Hibiscus/InteractiveObjects/Systems/Doors/_Design/MansionReskin/IO_Hib_Door_Bookcase',
            # No timing parameters
            #'/Hibiscus/InteractiveObjects/Systems/Doors/_Design/MansionReskin/IO_Hib_DoorFrame_130x250',
            '/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Venue/IO_Hib_Door_Venue_BossGate',
            # No timing parameters
            #'/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Village/IO_Hib_Door_130x250_Village',
            '/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Village/IO_Hib_Door_IronGate',
            '/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Woods/IO_Hib_Door_400x400_SlideDoor',
            '/Hibiscus/InteractiveObjects/Systems/Doors/_Design/Woods/IO_Hib_Door_800x600_SlideDoor',
            ]),
        ('Switches', [
            # find $(find . -name Switches) -name "IO_*.uasset" | sort -i | cut -d. -f2
            '/Game/InteractiveObjects/Switches/Circuit_Breaker/_Design/IO_Switch_Circuit_Breaker_V1',
            # No timing parameters
            #'/Game/InteractiveObjects/Switches/ControlPanel_Crane/_Design/IO_Switch_ControlPanel_Crane',
            '/Game/InteractiveObjects/Switches/CoV/IO_Switch_CoV_SkullSwitch_V1',
            '/Game/InteractiveObjects/Switches/CoV/Kitbash/_Design/IO_Switch_CoV_Kitbash_V1',
            # No timing parameters
            #'/Game/InteractiveObjects/Switches/CoV/Target/IO_SwitchDamagable_CoV_TargetCeiling_V1',
            '/Game/InteractiveObjects/Switches/CoV/Target/IO_SwitchDamagable_CoV_Target_V2',
            '/Game/InteractiveObjects/Switches/Detonator/_Design/IO_Switch_Detonator_V1',
            '/Game/InteractiveObjects/Switches/Eridian/_Design/IO_Switch_EridianSwitch_V1',
            '/Game/InteractiveObjects/Switches/Industrial/Button/_Design/IO_Switch_GenericButton_V1',
            # No timing parameters
            #'/Game/InteractiveObjects/Switches/Industrial/Keyboard/_Design/IO_Switch_Industrial_Keyboard_V1',
            '/Game/InteractiveObjects/Switches/Lever/Design/IO_Switch_Industrial_FloorLever_V1',
            '/Game/InteractiveObjects/Switches/Lever/Design/IO_Switch_Industrial_Prison',
            '/Game/InteractiveObjects/Switches/Promethea/_Design/IO_Switch_Promethea_Generic_V1',
            # No timing parameters
            #'/Game/InteractiveObjects/Switches/_Shared/_Design/IO_ChangeOfHeart_DoorbellButton',
            '/Game/InteractiveObjects/Switches/Switch/Design/IO_Switch_IndustrialSwitch_V1',
            '/Game/InteractiveObjects/Switches/WheelValve/Design/IO_Switch_Industrial_WheelValve_V1',
            '/Game/PatchDLC/BloodyHarvest/InteractiveObjects/Switches/_Design/IO_Switch_SkullSwitch',
            ]),
        ('Mission-Specific Machines', [
            # There's two animations involved here: one to read in the posters, and another to generate
            # the statues.  This speeds up those animations individually (or at least it speeds up the
            # first bit, honestly not totally sure about the second) but doesn't get rid of the delay
            # between them.  I have not yet figured out how to get the delay shorter, and I *suspect*
            # it might require blueprint bytecode tweaking, so that might be a bit of a journey.  So
            # as-is, it's not really worth speeding this up yet, until I can figure it out.
            #('Golden Calves Statue Scanner/Printer', 'Sacrifice_P', '/Game/InteractiveObjects/MissionScripted/_Design/IO_MissionScripted_StatueManufacturingMachine'),
            ]),
        ('Other Machines', [
            # This *does* speed up nearly all the slot machine animations, but the machine doesn't actually
            # spit out loot (or reset, in the event of no loot) until its sound effects are done, so there's
            # some other timing thing going on here, too.  No point speeding up the first bits if the last
            # ones still have to wait.
            #'/Game/InteractiveObjects/SlotMachine/_Shared/_Design/BPIO_SlotMachine',
            ]),
        ]:

    mod.header(category)

    for base_obj_name in obj_names:

        if type(base_obj_name) == tuple:
            label, level_name, base_obj_name = base_obj_name
        else:
            label = None
            level_name = 'MatchAll'

        if verbose:
            print('Processing {}'.format(base_obj_name))

        last_bit = base_obj_name.split('/')[-1]
        if label:
            mod.comment(label)
        else:
            mod.comment(last_bit)
        last_bit = '{}_C'.format(last_bit)
        full_obj_name = '{}.{}'.format(base_obj_name, last_bit)

        obj = data.get_data(base_obj_name)
        if not obj:
            print('WARNING - Could not be serialized: {}'.format(base_obj_name))
            continue

        if not checked_ver:
            if '_apoc_data_ver' not in obj[0] or obj[0]['_apoc_data_ver'] < min_apoc_jwp_version:
                raise RuntimeError('In order to generate a valid mod, you MUST use Apocalyptech\'s JWP fork which serializes to version {}'.format(min_apoc_jwp_version))
            checked_ver = True

        found_primary = False
        did_main = False
        did_curve = False
        for export in obj:
            if export['_jwp_object_name'] == last_bit:
                found_primary = True
                if 'Timelines' in export:
                    for timeline_idx, timeline_ref in enumerate(export['Timelines']):
                        timeline_exp = timeline_ref['export']
                        if verbose:
                            print(' - Processing timeline {} (export {})'.format(timeline_idx, timeline_exp))
                        if timeline_exp != 0:
                            timeline = obj[timeline_exp-1]

                            # This one's not actually required (and doesn't seem to do anything), but I feel weird *not* specifying it.
                            if 'TimelineLength' in timeline and timeline['TimelineLength'] != 0:
                                did_main = True
                                mod.reg_hotfix(Mod.LEVEL, level_name,
                                        full_obj_name,
                                        f'Timelines.Timelines[{timeline_idx}].Object..TimelineLength',
                                        round(timeline['TimelineLength']/global_scale, 6))

                            # Now process all our various curves
                            for trackname, curve_var in [
                                    ('EventTracks', 'CurveKeys'),
                                    ('FloatTracks', 'CurveFloat'),
                                    # I think VectorTracks is generally not needed; more used for
                                    # rotation+position info, perhaps?
                                    ('VectorTracks', 'CurveVector'),
                                    ]:
                                if trackname in timeline:
                                    if verbose:
                                        print('   - Processing {}'.format(trackname))
                                    for track_idx, track_ref in enumerate(timeline[trackname]):
                                        track_exp = track_ref[curve_var]['export']
                                        if verbose:
                                            print('     - On curve {} (export {})'.format(track_idx, track_exp))
                                        if track_exp != 0:
                                            curve = obj[track_exp-1]
                                            for inner_curve_var in ['FloatCurve', 'FloatCurves']:
                                                if inner_curve_var in curve:
                                                    for key_idx, key in enumerate(curve[inner_curve_var]['Keys']):
                                                        if key['time'] != 0:
                                                            did_curve = True
                                                            mod.reg_hotfix(Mod.LEVEL, level_name,
                                                                    full_obj_name,
                                                                    f'Timelines.Timelines[{timeline_idx}].Object..{trackname}.{trackname}[{track_idx}].{curve_var}.Object..{inner_curve_var}.Keys.Keys[{key_idx}].Time',
                                                                    round(key['time']/global_scale, 6))


        if not found_primary:
            raise RuntimeError('Could not find main export for {}'.format(base_obj_name))

        if not did_main and not did_curve:
            print('NOTICE - No timing parameters found for {}'.format(base_obj_name))
            mod.comment('(no timing parameters found to alter)')
        elif not did_main:
            # This honestly hardly matters; it doesn't look like this attr's really used
            # for much, anyway.
            print('NOTICE - No main TimelineLength found for {}'.format(base_obj_name))
        elif not did_curve:
            print('NOTICE - No curve timings found for {}'.format(base_obj_name))

        mod.newline()

# Honestly not sure yet if I want to put this in here, but I'm doing it for now...
# Can split it out later if I want.
mod.header('NPC Walking Speeds')

for charname, obj_name, scale in [
        ('Claptrap', '/Game/NonPlayerCharacters/Claptrap/_Design/Character/BpChar_Claptrap', global_char_scale),
        ('Lilith', '/Game/NonPlayerCharacters/Lilith/_Design/Character/BPChar_Lilith', global_char_scale),
        ]:

    last_bit = obj_name.split('/')[-1]
    default_name = 'Default__{}_C'.format(last_bit)
    full_obj_name = '{}.{}'.format(obj_name, default_name)

    found_main = False
    char_data = data.get_data(obj_name)
    speed = None
    have_slowdown = False
    for export in char_data:
        if export['_jwp_object_name'].lower() == default_name.lower():
            found_main = True
            if 'OakCharacterMovement' in export:
                if export['OakCharacterMovement']['export'] != 0:
                    move_export = char_data[export['OakCharacterMovement']['export']-1]
                    if 'MaxWalkSpeed' in move_export:
                        raise RuntimeError('{} actually has a MaxWalkSpeed; check this out!'.format(obj_name))
                    else:
                        # The default
                        speed = 600
                    if 'NavSlowdownOptions' in move_export and 'SlowdownSpeed' in move_export['NavSlowdownOptions']:
                        have_slowdown = True
                else:
                    raise RuntimeError('Could not find OakCharacterMovement export in {}'.format(obj_name))
            else:
                raise RuntimeError('Could not find OakCharacterMovement in {}'.format(obj_name))
            break
    if not found_main:
        raise RuntimeError('Could not find {} in {}'.format(default_name, obj_name))

    mod.comment(charname)
    mod.reg_hotfix(Mod.CHAR, last_bit,
            full_obj_name,
            'OakCharacterMovement.Object..MaxWalkSpeed',
            '(Value={},BaseValue={})'.format(
                speed*scale,
                speed*scale,
                ),
            )
    if have_slowdown:
        mod.reg_hotfix(Mod.CHAR, last_bit,
                full_obj_name,
                'OakCharacterMovement.Object..NavSlowdownOptions.bSlowdownNearGoal',
                'False',
                )
        mod.reg_hotfix(Mod.CHAR, last_bit,
                full_obj_name,
                'OakCharacterMovement.Object..NavSlowdownOptions.SlowdownSpeed.Value',
                1,
                )
    mod.newline()

# Some attempts to make loot-spewing pickups (bone piles, trash cans, etc) pick up more quickly.
# No luck yet!
if False:

    # The default for this attr (found in droppedinventoryitempickup objects) is 1.  I suspect this
    # *might* be something we could go for?  It feels like these items start auto-picking-up after
    # about 1sec.  I assume that the var means something like "if the item hasn't had a collision after
    # this many seconds, stop applying physics" or somesuch, at which point they're pick-upable.
    # I could be wrong about that, though.  At any rate, this statement looks okay to me but it never
    # seems to change the reported `getall` values.  Could be this is dynamically assigned or something.
    for hftype in [Mod.LEVEL, Mod.EARLYLEVEL]:
        for notify in [True, False]:
            mod.reg_hotfix(hftype, 'MatchAll',
                    '/Game/Pickups/_Shared/_Design/BP_OakConsumableItemPickup.Default__BP_OakConsumableItemPickup_C',
                    'NextImpactTimeThreshold',
                    0.1,
                    notify=notify)

    # Bit of a test to see how these things behave if we set them to attach their loot rather than spew
    # it out, but this doesn't actually change the `getall` results either, so no idea.
    mod.reg_hotfix(Mod.LEVEL, 'MatchAll',
            '/Game/Lootables/_Design/Classes/Global/BPIO_Lootable_BonePile.Default__BPIO_Lootable_BonePile_C',
            'ShouldAttachLoot',
            'True')

if False:

    elev_scale=2

    # these don't do anything
    if False:
        for thing in [Mod.LEVEL, Mod.EARLYLEVEL]:

            mod.reg_hotfix(thing, 'AtlasHQ_P',
                    '/Game/Missions/Plot/Ep06_OfficeSpaceInvaders/Elevator_Ep06_AtlasHQ_V2.Default__Elevator_Ep06_AtlasHQ_V2_C',
                    'ElevatorSpeed',
                    250*elev_scale)

            mod.reg_hotfix(thing, 'AtlasHQ_P',
                    '/Game/Missions/Plot/Ep06_OfficeSpaceInvaders/Elevator_Ep06_AtlasHQ_V2.Default__Elevator_Ep06_AtlasHQ_V2_C',
                    'ElevatorTravelTime',
                    47/elev_scale)

    # This does, but the one that moves just has the value get overwritten dynamically.  blueprinty things, I'm guessing.  ><
    for num in [0, 2]:

        mod.reg_hotfix(Mod.LEVEL, 'AtlasHQ_P',
                f'/Game/Maps/Zone_1/AtlasHQ/AtlasHQ_M_EP06OfficeSpaceInvaders.AtlasHQ_M_EP06OfficeSpaceInvaders:PersistentLevel.Elevator_Ep06_AtlasHQ_V_{num}',
                'ElevatorSpeed',
                #250*elev_scale)
                2000)

        mod.reg_hotfix(Mod.LEVEL, 'AtlasHQ_P',
                f'/Game/Maps/Zone_1/AtlasHQ/AtlasHQ_M_EP06OfficeSpaceInvaders.AtlasHQ_M_EP06OfficeSpaceInvaders:PersistentLevel.Elevator_Ep06_AtlasHQ_V_{num}',
                'ElevatorTravelTime',
                47/elev_scale)

mod.close()
