from bl3hotfixmod.bl3hotfixmod import Mod

mod = Mod('less_guaranteed_gun_accessoires.bl3hotfix',
        'Less Guaranteed Gun Accessoires',
        'Jalokin333',
        [
            'Changes the minimum amount of accessoires for a given slot to zero for every gun.',
            'This will make guns worse on average, but give you more variety.',
            'Thanks to Grimm and apocalyptech',
        ],
        lic=Mod.CC_BY_SA_40,
        v='1.0.0',
        cats='gear-general',
        )


for (label,  partsets, part_inds) in [
    ('Atlas Assault Rifles', [
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/Carrier/Balance/PartSet_ATL_AR_Carrier',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/Portal/Balance/PartSet_ATL_AR_Portals',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/RebellYell/Balance/PartSet_ATL_AR_RebelYell',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/PartSets/PartSet_ATL_AR_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/PartSets/PartSet_ATL_AR_02_UnCommon',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/PartSets/PartSet_ATL_AR_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/PartSets/PartSet_ATL_AR_04_VeryRare',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/OPQ/Balance/PartSet_ATL_AR_OPQ'
        ], [1,3]),
    ('COV Assault Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/COV/Balance/InvPartSet_AR_COV_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/COV/Balance/InvPartSet_AR_COV_ETech_VeryRare',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/_Unique/KriegAR/Balance/InvPartSet_AR_COV_KriegeAR',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/_Unique/Sawbar/Balance/InvPartSet_AR_COV_Sawbar',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/PartSet/InvPartSet_AR_COV_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/PartSet/InvPartSet_AR_COV_02_UnCommon',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/PartSet/InvPartSet_AR_COV_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/PartSet/InvPartSet_AR_COV_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Sawhorse/Balance/InvPartSet_AR_COV_Sawhorse',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Sawhorse/Balance/InvPartSet_AR_COV_Sawhorse_Epic',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Trash/Balance/InvPartSet_AR_COV_Trash',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/PewPew/Balance/InvPartSet_AR_COV_PewPew',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/InvPartSet_AR_COV_BioBetsy_Rad',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/InvPartSet_AR_COV_BioBetsy_Shock',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Homicidal/Balance/InvPartSet_AR_COV_Homicidal',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SparkyBoom/Balance/InvPartSet_AR_COV_SparkyBoom',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/ZheitsevEruption/Balance/InvPartSet_AR_COV_Zheitsev'
        ], [1,3]),
    ('Dahl Assault Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/Dahl/Balance/InvPartSet_DAL_AR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/Dahl/Balance/InvPartSet_DAL_AR_ETech_VeryRare',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Barrage/Balance/InvPartSet_DAL_AR_Barrage',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/BOTD/Balance/InvPartSet_DAL_AR_BOTD',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/CrazyEarlDefault/InvPartSet_DAL_AR_CrazyEarlDefault',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Earworm/Balance/InvPartSet_DAL_AR_Earworm',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Hail/Balance/InvPartSet_DAL_AR_Hail',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Kaos/Balance/InvPartSet_DAL_AR_Kaos',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/StarHelix/Balance/InvPartSet_DAL_AR_StarHelix',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Warlord/Balance/InvPartSet_DAL_AR_Warlord',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/PartSet/InvPartSet_DAL_AR_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/PartSet/InvPartSet_DAL_AR_02_Uncommon',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/PartSet/InvPartSet_DAL_AR_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/PartSet/InvPartSet_DAL_AR_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Digby/Balance/InvPartSet_DAL_AR_Digby',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Soulrender/Balance/InvPartSet_DAL_AR_Soulrender',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Juju/Balance/InvPartSet_DAL_AR_ETech_Juju'
        ], [1,3]),
    ('Jakobs Assault Rifles', [
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/Bekah/Balance/InvPartSet_JAK_AR_Bekah',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/GatlingGun/Balance/InvPartSet_JAK_AR_GatlingGun',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/HandOfGlory/Balance/InvPartSet_JAK_AR_HandOfGlory',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/LeadSprinkler/Balance/InvPartSet_JAK_AR_LeadSprinkler',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/PasRifle/Balance/InvPartSet_JAK_AR_PasRifle',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/RowansCall/Balance/InvPartSet_JAK_AR_RowansCall',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/TraitorsDeath/Balance/InvPartSet_JAK_AR_TraitorsDeath',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/PartSet/InvPartSet_JAK_AR_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/PartSet/InvPartSet_JAK_AR_02_UnCommon',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/PartSet/InvPartSet_JAK_AR_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/PartSet/InvPartSet_JAK_AR_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/CoolBeans/Balance/InvPartSet_JAK_AR_CoolBeans',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/McSmugger/Balance/InvPartSet_JAK_AR_McSmugger',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/StoneThrow/Balance/InvPartSet_JAK_AR_Stonethrow',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Clairvoyance/Balance/InvPartSet_JAK_AR_Clairvoyance',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Mutant/Balance/InvPartSet_JAK_AR_Mutant'
        ], [3]),
    ('Torgue Assault Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/TOR/Balance/InvPartSet_AR_TOR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/TOR/Balance/InvPartSet_AR_TOR_ETech_VeryRare',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/Alchemist/Balance/InvPartSet_AR_TOR_Alchemist',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/AmberManagement/Balance/InvPartSet_AR_TOR_AmberManagement',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/Bearcat/Balance/InvPartSet_AR_TOR_Bearcat',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/LaserSploder/Balance/InvPartSet_AR_TOR_LaserSploder',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Balance/InvPartSet_AR_TOR_TryBolt',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/WardenWeapon/InvPartSet_AR_TOR_Warden',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/PartSet/InvPartSet_AR_TOR_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/PartSet/InvPartSet_AR_TOR_02_UnCommon',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/PartSet/InvPartSet_AR_TOR_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/PartSet/InvPartSet_AR_TOR_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/LovableRogue/Balance/InvPartSet_AR_TOR_LovableRogue',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/LovableRogue/Balance/InvPartSet_AR_TOR_LovableRogue_Epic',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Varlope/Balance/InvPartSet_AR_TOR_Varlope',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/ContainedExplosion/Balance/InvPartSet_AR_TOR_Contained',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/HotfootTeddy/Balance/InvPartSet_AR_TOR_Hotfoot',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Juliet/Balance/InvPartSet_AR_TOR_Juliet',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Juliet/Balance/InvPartSet_AR_TOR_Juliet_WorldDrop'
        ], [1,3]),
    ('Vladof Assault Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/VLA/Balance/InvPart_VLA_AR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/AssaultRifle/VLA/Balance/InvPart_VLA_AR_ETech_VeryRare',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/BigSucc/InvPart_VLA_AR_BigSucc',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Damn/Balance/InvPart_VLA_AR_Damn',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Dictator/Balance/InvPart_VLA_AR_Dictator',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Faisor/Balance/InvPart_VLA_AR_Faisor',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/LuciansCall/Balance/InvPart_VLA_AR_LuciansCall',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Ogre/Balance/InvPart_VLA_AR_Ogre',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Shredifier/Balance/InvPart_VLA_AR_Sherdifier',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Sickle/Balance/InvPart_VLA_AR_Sickle',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/PartSets/InvPart_VLA_AR_01_Common',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/PartSets/InvPart_VLA_AR_02_UnCommon',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/PartSets/InvPart_VLA_AR_03_Rare',
        '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/PartSets/InvPart_VLA_AR_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/DowsingRod/Balance/InvPart_VLA_AR_Dowsing',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Monarch/Balance/InvPart_VLA_AR_Monarch',
        '/Game/PatchDLC/Takedown2/Gear/Weapons/WebSlinger/Balance/InvPart_VLA_AR_WebSlinger'
        ], [1,3,5,7]),
    ('Hyperion Shotguns', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Hyperion/Balance/BPInvPartSet_SG_HYP_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Hyperion/Balance/BPInvPartSet_SG_HYP_ETech_VeryRare',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Brick/Balance/BPInvPartSet_SG_HYP_Brick',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/ConferenceCall/Balance/BPInvPartSet_SG_HYP_ConferenceCall',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Balance/BPInvPartSet_SG_HYP_Phebert',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Redistributor/Balance/BPInvPartSet_SG_HYP_Redistributor',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/TheButcher/Balance/BPInvPartSet_SG_HYP_TheButcher',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/PartSets/BPInvPartSet_SG_HYP_01_Common',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/PartSets/BPInvPartSet_SG_HYP_02_Uncommon',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/PartSets/BPInvPartSet_SG_HYP_03_Rare',
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/PartSets/BPInvPartSet_SG_HYP_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Convergence/Balance/BPInvPartSet_SG_HYP_Convergence',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Convergence/Balance/BPInvPartSet_SG_HYP_Convergence_Epic',
        '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Fearmonger/Balance/PartSet_SG_HYP_ETech_Fearmonger',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/HeartBreaker/Balance/BPInvPartSet_SG_HYP_HeartBreaker',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/MeltFacer/Balance/BPInvPartSet_SG_HYP_MeltFacer',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/SlowHand/Balance/BPInvPartSet_SG_HYP_SlowHand',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/IceBurger/Balance/BPInvPartSet_SG_HYP_IceBurger',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Firecracker/Balance/InvPartSet_SG_HYP_Firecracker',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Reflux/Balance/BPInvPartSet_SG_HYP_Reflux'
        ], [1,3]),
    ('Jakobs Shotguns', [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Garcia/Balance/PartSet_SG_JAK_Garcia',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Hellwalker/Balance/PartSet_SG_JAK_Hellwalker',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/NimbleJack/Balance/PartSet_SG_JAK_Nimble',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/OnePunch/Balance/PartSet_SG_JAK_OnePunch',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Sledge/Balance/PartSet_SG_JAK_LGD_Sledge',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/Fingerbiter/Balance/PartSet_SG_JAK_Fingerbiter',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/TheWave/Balance/PartSet_SG_JAK_Unique_Wave',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/PartSet/Partset_SG_JAK_01_Common',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/PartSet/PartSet_SG_JAK_02_UnCommon',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/PartSet/PartSet_SG_JAK_03_Rare',
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/PartSet/PartSet_SG_JAK_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Dakota/Balance/PartSet_SG_JAK_Dakota',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Fakobs/Balance/PartSet_SG_JAK_Fakobs',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/SpeakEasy/Balance/PartSet_SG_JAK_SpeakEasy',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Splinter/Balance/PartSet_SG_JAK_Splinter',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheCure/Balance/PartSet_SG_JAK_TheCure'
        ], [3]),
    ('Maliwan Shotguns', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Maliwan/Balance/InvPartSet_SG_MAL_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Maliwan/Balance/InvPartSet_SG_MAL_ETech_VeryRare',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/MouthPiece2/Balance/InvPartSet_SG_MAL_Mouthpiece2',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Recursion/Balance/InvPartSet_SG_MAL_Recursion',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Shriek/Balance/InvPartSet_SG_MAL_Shriek',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Trev/Balance/InvPartSet_SG_MAL_Trev',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Wisp/Balance/InvPartSet_SG_MAL_Wisp',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/PartSet/InvPartSet_SG_MAL_01_Common',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/PartSet/InvPartSet_SG_MAL_02_Uncommon',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/PartSet/InvPartSet_SG_MAL_03_Rare',
        '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/PartSet/InvPartSet_SG_MAL_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/BlindBandit/Balance/InvPartSet_SG_MAL_BlindBandit',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/BlindBandit/Balance/InvPartSet_SG_MAL_BlindBandit_Epic',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Antler/Balance/InvPartSet_SG_MAL_ETech_Antler',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Frequency/Balance/InvPartSet_SG_MAL_Frequency',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Insider/Balance/InvPartSet_SG_MAL_ETech_Insider',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheNothing/Balance/InvPartSet_SG_MAL_TheNothing',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/DeathGrip/Balance/InvPartSet_SG_MAL_DeathGrip'
        ], [1,3]),
    ('Tediore Shotguns', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Tediore/Balance/PartSet_SG_TED_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Tediore/Balance/PartSet_SG_TED_ETech_VeryRare',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/FriendZone/Balance/PartSet_SG_TED_FriendZone',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Horizon/Balance/PartSet_SG_TED_Horizon',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Polybius/Balance/PartSet_SG_TED_Polybius',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Sludge/Balance/PartSet_SG_TED_Sludge',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/PartSets/PartSet_SG_TED_01_Common',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/PartSets/PartSet_SG_TED_02_Uncommon',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/PartSets/PartSet_SG_TED_03_Rare',
        '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/PartSets/PartSet_SG_TED_04_VeryRare',
        '/Game/PatchDLC/EventVDay/Gear/Weapon/_Unique/TwitchPrime/Balance/PartSet_SG_TED_Twitch',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Brightside/Balance/PartSet_SG_TED_Brightside',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Anarchy/Balance/PartSet_SG_TED_Anarchy',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Omen/Balance/PartSet_SG_TED_Omen',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SacrificalLamb/Balance/PartSet_SG_TED_SacrificialLamb'
        ], [1,3]),
    ('Torgue Shotguns', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Torgue/Balance/InvPartSet_SG_Torgue_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Shotgun/Torgue/Balance/InvPartSet_SG_Torgue_ETech_VeryRare',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Balrog/Balance/InvPartSet_SG_Torgue_Balrog',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Brew/Balance/InvPartSet_SG_TOR_Brewha',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Flakker/Balance/InvPartSet_SG_Torgue_Flakker',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/RedLiner/Balance/InvPartSet_SG_Torgue_RedLine',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/TheBoringGun/Balance/InvPartSet_SG_TOR_Boring',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/TheLob/Balance/InvPartSet_SG_Torgue_ETech_TheLob',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Thumper/Balance/InvPartSet_SG_Torgue_Thumper',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/PartSets/InvPartSet_SG_Torgue_01_Common',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/PartSets/InvPartSet_SG_Torgue_02_UnCommon',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/PartSets/InvPartSet_SG_Torgue_03_Rare',
        '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/PartSets/InvPartSet_SG_Torgue_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Shoveler/Balance/InvPartSet_SG_Torgue_Shoveler',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Shocker/Balance/InvPartSet_SG_Torgue_ETech_Shocker',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/CriticalThug/Balance/InvPartSet_SG_Torgue_CriticalThug',
        '/Game/PatchDLC/Raid1/Gear/Weapons/TiggsBoom/Balance/InvPartSet_SG_Torgue_TiggsBoom'
        ], [1,3]),
    ('Atlas Heavy Weapons', [
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/_Unique/Freeman/Balance/PartSet_ATL_HW_Freeman',
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/_Unique/RubysWrath/Balance/PartSet_ATL_HW_RubysWrath',
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/PartSets/PartSet_ATL_HW_01_Common',
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/PartSets/PartSet_ATL_HW_02_UnCommon',
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/PartSets/PartSet_ATL_HW_03_Rare',
        '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/PartSets/PartSet_ATL_HW_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Plumage/Balance/PartSet_ATL_HW_Plumage'
        ], [1,3]),
    ('COV Heavy Weapons', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/COV/Balance/PartSet_HW_COV_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/COV/Balance/PartSet_HW_COV_ETech_VeryRare',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/HotDrop/Balance/PartSet_HW_COV_HotDrop',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/PortaPooper/Balance/PartSet_HW_COV_PortaPooper',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/Terror/Balance/PartSet_HW_COV_Terror',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_HW_COV_01_Common',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_HW_COV_02_UnCommon',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_HW_COV_03_Rare',
        '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_HW_COV_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/BanditLauncher/Balance/PartSet_HW_COV_BanditLauncher',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/BanditLauncher/Balance/PartSet_HW_COV_BanditLauncher_Epic',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/YellowCake/Balance/PartSet_HW_COV_ETech_YellowCake',
        '/Game/PatchDLC/Takedown2/Gear/Weapons/Globetrotter/Balance/PartSet_HW_COV_Globetrotter'
        ], [1,3]),
    ('Torgue Heavy Weapons', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/TOR/Balance/PartSet_HW_TOR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/TOR/Balance/PartSet_HW_TOR_ETech_VeryRare',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/BurgerCannon/Balance/PartSet_HW_TOR_BurgerCannon',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Hive/Balance/PartSet_HW_TOR_Hive',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Rampager/Balance/PartSet_HW_TOR_Rampager',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/RYNO/Balance/PartSet_HW_TOR_RYNO',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Swarm/Balance/PartSet_HW_TOR_Swarm',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Tunguska/Balance/PartSet_HW_TOR_Tunguska',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/PartSets/PartSet_HW_TOR_01_Common',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/PartSets/PartSet_HW_TOR_02_Uncommon',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/PartSets/PartSet_HW_TOR_03_Rare',
        '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/PartSets/PartSet_HW_TOR_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Creamer/Balance/PartSet_HW_TOR_Creamer',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Nukem/Balance/PartSet_HW_TOR_Nukem',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Satisfaction/Balance/PartSet_HW_TOR_Satisfaction',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/IceAge/Balance/PartSet_HW_TOR_IceAge',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Plague/Balance/PartSet_HW_TOR_Plague'
        ], [1,3,7]),
    ('Vladof Heavy Weapons', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/VLA/Balance/PartSet_HW_VLA_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/HW/VLA/Balance/PartSet_HW_VLA_ETech_VeryRare',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/_Unique/CloudBurst/Balance/PartSet_HW_VLA_CloudBurst',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/_Unique/Mongol/Balance/PartSet_HW_VLA_Mongol',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/PartSet/PartSet_HW_VLA_01_Common',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/PartSet/PartSet_HW_VLA_02_Uncommon',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/PartSet/PartSet_HW_VLA_03_Rare',
        '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/PartSet/PartSet_HW_VLA_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/IonCannon/Balance/PartSet_HW_VLA_IonCannon',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Backburner/Balance/PartSet_HW_VLA_ETech_BackBurner'
        ], [1,3]),
    ('Atlas Pistols', [
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Drill/Balance/PartSet_PS_ATL_Drill',
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Warmonger/Balance/PartSet_PS_ATL_Warmonger',
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/PartSets/PartSet_PS_ATL_01_Common',
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/PartSets/PartSet_PS_ATL_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/PartSets/PartSet_PS_ATL_03_Rare',
        '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/PartSets/PartSet_PS_ATL_04_VeryRare',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/SpiritOfMaya/Balance/PartSet_PS_ATL_SpiritOfMaya',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/DoubleTap/Balance/PartSet_PS_ATL_DoubleTap'
        ], [1,3]),
    ('COV Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/COV/Balance/PartSet_PS_COV_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/COV/Balance/PartSet_PS_COV_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Chad/Balance/PartSet_PS_COV_Chad',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Contagion/Balance/PartSet_PS_COV_Contagion',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Legion/Balance/PartSet_PS_COV_Legion',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Mouthpiece/Balance/PartSet_PS_COV_Mouthpiece',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/PsychoStabber/Balance/PartSet_PS_COV_PsychoStabber',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Skeksis/Balance/PartSet_PS_COV_Skeksis',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_PS_COV_01_Common',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_PS_COV_02_Uncommon',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_PS_COV_03_Rare',
        '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/PartSet/PartSet_PS_COV_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Gargoyle/Balance/PartSet_PS_COV_Gargoyle',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Hydrafrost/Balance/PartSet_PS_COV_Hydrafrost',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/Tizzy/Balance/PartSet_PS_COV_Tizzy'
        ], [1,3]),
    ('Dahl Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/Dahl/Balance/PartSet_DAL_PS_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/Dahl/Balance/PartSet_DAL_PS_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/AAA/Balance/PartSet_DAL_PS_AAA',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Hornet/Balance/PartSet_DAL_PS_Hornet',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Nemesis/Balance/PartSet_DAL_PS_Nemesis',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Omniloader/Balance/PartSet_DAL_PS_Omniloader',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/OperativeSkillSCreen/PartSet_DAL_PS_OperativeSkillScreen',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Rakkman/Balance/PartSet_DAL_PS_Rakkman',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/PartSet/PartSet_DAL_PS_01_Common',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/PartSet/PartSet_DAL_PS_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/PartSet/PartSet_DAL_PS_03_Rare',
        '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/PartSet/PartSet_DAL_PS_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/PrivateInvestigator/Balance/PartSet_DAL_PS_PrivateInvestigator',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Kaleidoscope/Balance/PartSet_DAL_PS_Kaleidoscope'
        ], [2]),
    ('Jakobs Pistols', [
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/AmazingGrace/Balance/InvPartSet_PS_JAK_AmazingGrace',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/AureliaBackup/Balance/InvPartSet_PS_JAK_AureliaPistol',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Buttplug/Balance/InvPartSet_PS_JAK_Buttplug',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Doc/Balance/InvPartSet_PS_JAK_DOC',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/GodMother/Balance/InvPartSet_PS_JAK_GodMother',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Maggie/Balance/InvPartSet_PS_JAK_Maggie',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Malevolent/Balance/InvPartSet_PS_JAK_Malevolent',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Balance/InvPartSet_PS_JAK_MelsCompanion',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/SpyRevolver/InvPartSet_PS_JAK_SpyRevolver',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/TheDuc/Balance/InvPartSet_PS_JAK_TheDuc',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/TortureTruck/InvPartSet_PS_JAK_TortureTruck',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Unforgiven/Balance/InvPartSet_PS_JAK_Unforgiven',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/WagonWheel/Balance/InvPartSet_PS_JAK_WagonWheel',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/PartSets/InvPartSet_PS_JAK_01_Common',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/PartSets/InvPartSet_PS_JAK_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/PartSets/InvPartSet_PS_JAK_03_Rare',
        '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/PartSets/InvPartSet_PS_JAK_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Lucky7/Balance/InvPartSet_PS_JAK_Lucky7',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/RoboMasher/Balance/InvPartSet_PS_JAK_RoboMasher',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Peashooter/Balance/InvPartSet_PS_JAK_Peashooter',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/QuickDraw/Balance/InvPartSet_PS_JAK_QuickDraw',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Rose/Balance/InvPartSet_PS_JAK_Rose',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Sheriff/Balance/InvPartSet_PS_JAK_Sheriff',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/BiteSize/Balance/InvPartSet_PS_JAK_BiteSize',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LittleYeeti/Balance/InvPartSet_PS_JAK_LittleYeeti',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/Balance/InvPartSet_PS_JAK_LoveDrill',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/Balance/InvPartSet_PS_JAK_LoveDrill_Legendary',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SeventhSense/Balance/InvPartSet_PS_JAK_SeventhSense',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SeventhSense/Balance/InvPartSet_PS_JAK_SS_L',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/InvPartSet_PS_JAK_TheSeventhSense',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/InvPartSet_PS_JAK_TheSeventhSense_MissionWeapon',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/Trickshot/Balance/InvPartSet_PS_JAK_Trickshot'
        ], [1,3]),
    ('Maliwan Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/MAL/Balance/InvPartSet_PS_MAL_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/MAL/Balance/InvPartSet_PS_MAL_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/_AI/TrooperBadass/InvPartSet_PS_MAL_AI_TrooperBadass',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Hellshock/Balance/InvPartSet_PS_MAL_Hellshock',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/HyperHydrator/Balance/InvPartSet_PS_MAL_HyperHydrator',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Plumber/Balance/InvPartSet_PS_MAL_Plumber',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Starkiller/Balance/InvPartSet_PS_MAL_Starkiller',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/SuckerPunch/Balance/InvPartSet_PS_MAL_SuckerPunch',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/ThunderballFist/Balance/InvPartSet_PS_MAL_ThuderballFists',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/PartSet/InvPartSet_PS_MAL_01_Common',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/PartSet/InvPartSet_PS_MAL_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/PartSet/InvPartSet_PS_MAL_03_Rare',
        '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/PartSet/InvPartSet_PS_MAL_04_VeryRare',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/GreaseTrap/Balance/InvPartSet_PS_MAL_GreaseTrap',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/IcePick/Balance/InvPartSet_PS_MAL_IcePick',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BubbleBlaster/Balance/InvPartSet_PS_MAL_BubbleBlaster',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Decoupler/Balance/InvPartSet_PS_MAL_Decoupler',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/FrozenDevil/Balance/InvPartSet_PS_MAL_FrozenDevil'
        ], [3,7]),
    ('Tediore Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/TED/Balance/InvPartSet_PS_TED_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/TED/Balance/InvPartSet_PS_TED_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/_Bangarang/Balance/InvPartSet_PS_TED_Bangerang',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/BabyMaker/Balance/InvPartSet_PS_TED_BabyMaker',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/BabyMaker/Balance/Salvage/InvPartSet_PS_TED_BabyMaker_Salvage',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/Gunerang/Balance/InvPartSet_PS_TED_Gunerang',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/Sabre/Balance/InvPartSet_PS_TED_Sabre',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/PartSets/InvPartSet_PS_TED_01_Common',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/PartSets/InvPartSet_PS_TED_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/PartSets/InvPartSet_PS_TED_03_Rare',
        '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/PartSets/InvPartSet_PS_TED_04_VeryRare',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Execute/Balance/InvPartSet_PS_TED_Execute'
        ], [1,3]),
    ('Torgue Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/TOR/Balance/PartSet_PS_TOR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/TOR/Balance/PartSet_PS_TOR_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Devestator/Balance/PartSet_PS_TOR_Devestator',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Echo/Balance/PartSet_PS_TOR_Echo',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Foursum/Balance/PartSet_PS_TOR_4SUM',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/HeckelAndHyde/Heckle/Balance/PartSet_PS_TOR_Heckle',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/HeckelAndHyde/Hyde/Balance/PartSet_PS_TOR_Hyde',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Nurf/Balance/PartSet_PS_TOR_Nurf',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/RoisensThorns/Balance/PartSet_PS_TOR_RoisensThorns',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Troy/Balance/PartSet_PS_TOR_Troy',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/PartSet/PartSet_PS_TOR_01_Common',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/PartSet/PartSet_PS_TOR_02_Uncommon',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/PartSet/PartSet_PS_TOR_03_Rare',
        '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/PartSet/PartSet_PS_TOR_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Voice/Balance/PartSet_PS_TOR_Voice',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Voice/Balance/PartSet_PS_TOR_Voice_Epic',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Craps/Balance/PartSet_PS_TOR_Craps',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Scoville/Balance/PartSet_PS_TOR_Scoville',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/UnkemptHarold/Balance/PartSet_PS_TOR_UnkemptHarold',
        '/Game/PatchDLC/Raid1/Gear/Weapons/HandCannon/Balance/PartSet_PS_TOR_HandCannon'
        ], [1,3]),
    ('Vladof Pistols', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/Vladof/Balance/InvPart_VLA_PS_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/Pistol/Vladof/Balance/InvPart_VLA_PS_ETech_VeryRare',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/BoneShredder/Balance/InvPart_VLA_PS_BoneShredder',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/Infiniti/Balance/InvPart_VLA_PS_Infiniti',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/Magnificent/Balance/InvPart_VLA_PS_Magnificent',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/TheLeech/Balance/InvPart_VLA_PS_TheLeech',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/PartSets/InvPart_VLA_PS_01_Common',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/PartSets/InvPart_VLA_PS_02_UnCommon',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/PartSets/InvPart_VLA_PS_03_Rare',
        '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/PartSets/InvPart_VLA_PS_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Lasocannon/Balance/InvPart_VLA_PS_Lasocannon',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Miscreant/Balance/InvPart_VLA_PS_Miscreant',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/Firefly/Balance/InvPart_VLA_PS_Firefly'
        ], [3,12]),
    ('Dahl SMGs', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Dahl/Balance/InvPartSet_SM_DAL_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Dahl/Balance/InvPartSet_SM_DAL_ETech_VeryRare',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Demoskag/Balance/InvPartSet_SM_DAL_Demoskag',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/HellFire/Balance/InvPartSet_SM_DAL_HellFire',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/NineVolt/Balance/InvPartSet_SM_DAL_NineVolt',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Ripper/Balance/InvPartSet_SM_DAL_Ripper',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/RockNRoll_Intro/InvPartSet_SM_DAL_PlayableIntroOnly',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/SleepingGiant/Balance/InvPartSet_SM_DAL_SleepingGiant',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Vanquisher/Balance/PartSet_SM_DAL_Vanquisher',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/PartSets/InvPartSet_SM_DAL_01_Common',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/PartSets/InvPartSet_SM_DAL_01_Common_NoElemental',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/PartSets/InvPartSet_SM_DAL_02_UnCommon',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/PartSets/InvPartSet_SM_DAL_03_Rare',
        '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/PartSets/InvPartSet_SM_DAL_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/AshenBeast/Balance/InvPartSet_SM_DAL_ETech_AshenBeast',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/AshenBeast/Balance/InvPartSet_SM_DAL_ETech_AshenBeast_Epic',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Boomer/Balance/InvPartSet_SM_DAL_Boomer',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Kaoson/Balance/InvPartSet_SM_DAL_Kaoson',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/CraderMP5/Balance/InvPartSet_SM_DAL_CraderMP5',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/PurpleSMG/InvPartSet_SM_DAL_LowLvlReturningGift'
        ], [1,3]),
    ('Hyperion SMGs', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Hyperion/Balance/InvPartSet_SM_HYP_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Hyperion/Balance/InvPartSet_SM_HYP_ETech_VeryRare',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Bitch/Balance/InvPartSet_SM_HYP_Bitch',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Crossroad/Balance/InvPartSet_SM_HYP_Crossroad',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Fork/Balance/InvPartSet_SM_HYP_Fork',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Handsome/Balance/InvPartSet_SM_HYP_Handsome',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/L0V3M4CH1N3/Balance/InvPartSet_SM_HYP_L0V3M4CH1N3',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/PredatoryLending/Balance/InvPartSet_SM_HYP_PredatoryLending',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/XZ/Balance/InvPartSet_SM_HYP_XZ',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/PartSets/InvPartSet_SM_HYP_01_Common',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/PartSets/InvPartSet_SM_HYP_02_UnCommon',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/PartSets/InvPartSet_SM_HYP_03_Rare',
        '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/PartSets/InvPartSet_SM_HYP_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/CheapTips/Balance/InvPartSet_SM_HYP_CheapTips',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/JustCaustic/Balance/InvPartSet_SM_HYP_JustCaustic',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/Pricker/Balance/InvPartSet_SM_HYP_Pricker',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Copybeast/Balance/InvPartSet_SM_HYP_Copybeast',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Oldridian/Balance/InvPartSet_SM_HYP_Oldridian',
        '/Game/PatchDLC/Raid1/Gear/Weapons/Fork2/Balance/InvPartSet_SM_HYP_Fork2',
        '/Game/PatchDLC/Steam/Gear/Weapons/SteamGun/Balance/InvPartSet_SM_HYP_ShortStick',
        '/Game/PatchDLC/Steam/Gear/Weapons/SteamGun/Balance/InvPartSet_SM_HYP_ShortStick_Legendary',
        '/Game/PatchDLC/Takedown2/Gear/Weapons/Smog/Balance/InvPartSet_SM_HYP_Smog'
        ], [1,3]),
    ('Maliwan SMGs', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Maliwan/Balance/InvPartSet_SM_MAL_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Maliwan/Balance/InvPartSet_SM_MAL_ETech_VeryRare',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/CloudKill/Balance/InvPartSet_SM_MAL_CloudKill',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Crit/Balance/InvPartSet_SM_MAL_Crit',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Cutsman/Balance/InvPartSet_SM_MAL_Cutsman',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/DestructoSpin/Balance/InvPartSet_SM_MAL_DestructoSpin',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Devoted/Balance/InvPartSet_SM_MAL_Devoted',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/E3/InvPartSet_SM_MAL_E3',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Egon/Balance/InvPartSet_SM_MAL_Egon',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Emporer/Balance/InvPartSet_SM_MAL_Emporer',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Kevins/Balance/InvPartSet_SM_MAL_Kevins',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Tsunami/Balance/InvPartSet_SM_MAL_Tsunami',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/VibraPulse/Balance/InvPartSet_SM_MAL_VibraPulse',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/westergun/Balance/InvPartSet_SM_MAL_westergun',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/PartSets/InvPartSet_SM_MAL_01_Common',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/PartSets/InvPartSet_SM_MAL_02_Uncommon',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/PartSets/InvPartSet_SM_MAL_03_Rare',
        '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/PartSets/InvPartSet_SM_MAL_04_VeryRare',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/EmbersPurge/Balance/InvPartSet_SM_MAL_EmbersPurge',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/IonLaser/Balance/InvPartSet_SM_MAL_IonLaser',
        '/Game/PatchDLC/EventVDay/Gear/Weapon/_Unique/PolyAim/Balance/InvPartSet_SM_MAL_PolyAim',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Flipper/Balance/InvPartSet_SM_MAL_Flipper',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SFForce/Balance/InvPartSet_SM_MAL_SFForce',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/PlasmaCoil/Balance/InvPartSet_SM_MAL_PlasmaCoil',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/DNA/Balance/InvPartSet_SM_MAL_DNA',
        '/Game/PatchDLC/Raid1/Gear/Weapons/KybsWorth/Balance/InvPartSet_SM_MAL_KybsWorth',
        '/Game/PatchDLC/Raid1/Gear/Weapons/Link/Balance/InvPartSet_SM_MAL_Link'
        ], [1,3]),
    ('Tediore SMGs', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Tediore/Balance/Partset_SM_TED_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SMGs/Tediore/Balance/Partset_SM_TED_ETech_VeryRare',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/Beans/Balance/Partset_SM_TED_Beans',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/NotAFlamethrower/Balance/Partset_SM_TED_NotAFlamethrower',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/SpiderMind/Balance/Partset_SM_TED_SpiderMind',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/TenGallon/Balance/Partset_SM_TED_TenGallon',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/PartSets/Partset_SM_TED_01_Common',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/PartSets/Partset_SM_TED_02_UnCommon',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/PartSets/Partset_SM_TED_03_Rare',
        '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/PartSets/Partset_SM_TED_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/PAT_Mk3/Balance/Partset_SM_TED_PatMk3',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/PAT_Mk3/Balance/Partset_SM_TED_PatMk3_Epic',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/PAT_Mk3/Balance/Partset_SM_TED_PatMk3_Parent',
        '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/NeedleGun/Balance/Partset_SM_TED_NeedleGun',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Earthbound/Balance/Partset_SM_TED_Earthbound',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/DarkArmy/Balance/Partset_SM_TED_DarkArmy'
        ], [1,3]),
    ('Dahl Sniper Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Dahl/Balance/PartSet_SR_DAL_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Dahl/Balance/PartSet_SR_DAL_ETech_VeryRare',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/BrashisDedication/Balance/PartSet_SR_DAL_BrashisDedication',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/MalaksBane/Balance/PartSet_SR_DAL_ETech_MalaksBane',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/WorldDestroyer/Balance/PartSet_SR_DAL_WorldDestroyer',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/PartSets/PartSet_SR_DAL_01_Common',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/PartSets/PartSet_SR_DAL_02_UnCommon',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/PartSets/PartSet_SR_DAL_03_Rare',
        '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/PartSets/PartSet_SR_DAL_04_VeryRare',
        '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/SniperRifles/Dahl/_Design/_Unique/Frostbolt/Balance/PartSet_SR_DAL_ETech_Frostbolt',
        '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/AutoAime/Balance/PartSet_SR_DAL_AutoAime',
        '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/SandHawk/Balance/PartSet_SR_DAL_SandHawk'
        ], [1,3,11]),
    ('Hyperion Sniper Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Hyperion/Balance/PartSet_SR_HYP_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Hyperion/Balance/PartSet_SR_HYP_ETech_VeryRare',
        '/Game/Gear/Weapons/_Shared/NPC_Weapons/Zero/ZeroForPlayer/PartSet_SR_HYP_ZeroForPlayer',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/MasterworkCrossbow/Balance/PartSet_SR_HYP_Masterwork',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/TwoTime/Balance/PartSet_SR_HYP_TwoTime',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/Woodblocks/Balance/PartSet_SR_HYP_Woodblocks',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/PartSets/PartSet_SR_HYP_01_Common',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/PartSets/PartSet_SR_HYP_02_Uncommon',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/PartSets/PartSet_SR_HYP_03_Rare',
        '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/PartSets/PartSet_SR_HYP_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Narp/Balance/PartSet_SR_HYP_Narp',
        '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Tankman/Balance/PartSet_SR_HYP_Tankman'
        ], [1,3,8]),
    ('Jakobs Sniper Rifles', [
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/Headsplosion/Balance/PartSet_SR_JAK_Headsplosion',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/IceQueen/Balance/PartSet_SR_JAK_IceQueen',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/Monocle/Balance/PartSet_SR_JAK_Monocle',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/Balance/PartSet_SR_JAK_Hunter',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/Hunted/Balance/PartSet_SR_JAK_Hunted',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/Huntress/Balance/PartSet_SR_JAK_Huntress',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/PartSets/PartSet_SR_JAK_01_Common',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/PartSets/PartSet_SR_JAK_02_Uncommon',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/PartSets/PartSet_SR_JAK_03_Rare',
        '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/PartSets/PartSet_SR_JAK_04_VeryRare',
        '/Game/PatchDLC/EventVDay/Gear/Weapon/_Unique/WeddingInvitation/Balance/PartSet_SR_JAK_WeddingInvite',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/CockyBastard/Balance/PartSet_SR_JAK_CockyBastard',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Skullmasher/Balance/PartSet_SR_JAK_Skullmasher',
        '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/UnseenThreat/Balance/PartSet_SR_JAK_UnseenThreat'
        ], [1,3,7]),
    ('Maliwan Sniper Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Maliwan/Balance/PartSet_MAL_SR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Maliwan/Balance/PartSet_MAL_SR_ETech_VeryRare',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/ASMD/Balance/PartSet_MAL_SR_ASMD',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Krakatoa/Balance/PartSet_MAL_SR_Krakatoa',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Soleki/Balance/PartSet_MAL_SR_Soleki',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Storm/Balance/PartSet_MAL_SR_LGD_Storm',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/PartSet/PartSet_MAL_SR_01_Common',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/PartSet/PartSet_MAL_SR_02_UnCommon',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/PartSet/PartSet_MAL_SR_03_Rare',
        '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/PartSet/PartSet_MAL_SR_04_VeryRare',
        '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/ImaginaryNumber/Balance/PartSet_MAL_SR_ImaginaryNumber',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/BinaryOperator/Balance/PartSet_MAL_SR_BinaryOperator'
        ], [1,3,9]),
    ('Vladof Sniper Rifles', [
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Vladof/Balance/PartSet_VLA_SR_ETech_Rare',
        '/Game/Gear/Weapons/_Shared/_Design/_Manufacturers/_ETech/_Design/SniperRifles/Vladof/Balance/PartSet_VLA_SR_ETech_VeryRare',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Lyuda/Balance/PartSet_VLA_SR_Lyuda',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Prison/Balance/PartSet_VLA_SR_Prison',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/PartSet/PartSet_VLA_SR_01_Common',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/PartSet/PartSet_VLA_SR_02_Uncommon',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/PartSet/PartSet_VLA_SR_03_Rare',
        '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/PartSet/PartSet_VLA_SR_04_VeryRare',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Septimator/Balance/PartSet_VLA_SR_Septimator',
        '/Game/PatchDLC/Alisma/Gear/Weapon/_Unique/Septimator/Balance/PartSet_VLA_SR_Septimator_Epic',
        '/Game/PatchDLC/Ixora/Gear/Weapons/_Unique/Boogeyman/Balance/PartSet_VLA_SR_Boogeyman'
        ], [1,3,8,11])
        
    ]:
        
        mod.header(label)
        for partset in partsets:
            for index in part_inds:
                mod.reg_hotfix(Mod.PATCH, '',
                    partset,
                    'ActorPartLists[{}].MultiplePartSelectionRange.Min'.format(index),
                    0)
                mod.newline()
        
mod.close()
