#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Copyright 2019-2020 Christopher J. Kucera
# <cj@apocalyptech.com>
# <http://apocalyptech.com/contact.php>
#
# This Borderlands 3 Hotfix Mod is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This Borderlands 3 Hotfix Mod is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this Borderlands 3 Hotfix Mod.  If not, see
# <https://www.gnu.org/licenses/>.

from bl3hotfixmod.bl3hotfixmod import Mod

mod = Mod('all_weapons_can_anoint.txt',
        'All Weapons Can Anoint',
        'Apocalyptech',
        [
            "Adds anointment parts to all the weapons which can't ordinarily",
            "have them.  (This doesn't *guarantee* anointments -- use my",
            "Better Loot for that.)  Excludes The Shoddy.",
        ],
        lic=Mod.CC_BY_SA_40,
        )

# Weight attributes
(NONE, GENERIC, SIREN, OPERATIVE, BEASTMASTER, GUNNER) = range(6)

anoint_parts = {
        NONE: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_NoneChanceGuns.Att_EndGame_NoneChanceGuns',
        GENERIC: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_GenericPartChance.Att_EndGame_GenericPartChance',
        SIREN: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_Siren_PartChance.Att_EndGame_Siren_PartChance',
        OPERATIVE: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_Operative_PartChance.Att_EndGame_Operative_PartChance',
        BEASTMASTER: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_BEastmaster_PartChance.Att_EndGame_Beastmaster_PartChance',
        GUNNER: '/Game/Gear/Weapons/_Shared/_Design/EndGameParts/DropWeight/Att_EndGame_Gunner_PartChance.Att_EndGame_Gunner_PartChance',
        }

# Constants for mapping anointments to manufacturers/types.  This and the 'anointments'
# bit below generated by a bit of code in my extracted data dir, in /Game/Gear/Weapons
# (get_anoints_code.py).  Grenade bits were added by hand, though.
(ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
        HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
        MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
        VLA_PS, VLA_SR, GR) = range(33)

# Anointment list.  We actually only need to put the base game Anointments in here -- the others
# will be added automatically by the GPartExpansion objects.  Those don't apply to these
# weapons ordinarily because they don't have a GenericParts array to alter.  Since we're adding
# that in with this mod, they'll pick up the new ones automatically (including, say, Bloody Harvest
# anoints when that event's active, etc).
anointments = [

        # Base game generics
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_AccuracyHandling/GPart_All_SkillEnd_AccuracyHandling', GENERIC, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_SplashDamage/GPart_All_SkillEnd_SplashDamage', GENERIC, {
            ATL_HW, COV_HW, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR,
            TOR_HW, TOR_PS, TOR_SG, VLA_HW,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_CritDamage/GPart_All_SkillEnd_CritDamage', GENERIC, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_FireRateReload/GPart_All_SkillEnd_FireRateReload', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_LifeSteal/GPart_All_SkillEnd_LifeSteal', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_MeleeDamage/GPart_All_SkillEnd_MeleeDamage', GENERIC, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_UniqueEnemyDamage/GPart_All_SkillEnd_UniqueEnemyDamage', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_WeaponDamage/GPart_All_SkillEnd_WeaponDamage', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_NextMagBonus/Fire/GPart_All_SkillEnd_NextMagBonusDamageFire', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_NextMagBonus/Shock/GPart_All_SkillEnd_NextMagBonusDamageShock', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_NextMagBonus/Radiation/GPart_All_SkillEnd_NextMagBonusDamageRadiation', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_NextMagBonus/Cryo/GPart_All_SkillEnd_NextMagBonusDamageCryo', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_NextMagBonus/Corrosive/GPart_All_SkillEnd_NextMagBonusDamageCorrosive', GENERIC, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_EleChanceDamage/GPart_All_SkillEnd_EleChanceDamage', GENERIC, {
            COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM, HYP_SR,
            MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS,
            TOR_SG, VLA_AR, VLA_HW, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillEnd_ProjectileSpeed/GPart_All_SkillEnd_ProjectileSpeed', GENERIC, {
            ATL_HW, COV_HW, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TOR_AR, TOR_HW, TOR_PS, TOR_SG,
            VLA_HW,
            }),

        # Base game Siren
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Cast_WeaponDamage/GPart_Siren_Cast_WeaponDamage', SIREN, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Grasp_AccuracyCrit/GPart_Siren_Grasp_AccuracyCrit', SIREN, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/SkillEnd_AttunedEleDamage/GPart_Siren_SkillEnd_AttunedSkillDamage', SIREN, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Slam_MeleeDamage/GPart_Siren_Slam_MeleeDamage', SIREN, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Slam_WeaponDamage/GPart_Siren_Slam_WeaponDamage', SIREN, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Cast_EleChance/GPart_Siren_Cast_ElementalChance', SIREN, {
            COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM, HYP_SR,
            MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS,
            TOR_SG, VLA_AR, VLA_HW, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Siren/Grasp_ChargeSpeed/GPart_Siren_Grasp_ChargeSpeed', SIREN, {
            MAL_PS, MAL_SG, MAL_SM, MAL_SR,
            }),

        # Base game Operative
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/BarrierActiveAccuracyCrit/GPart_Operative_BarrierActive_AccuracyCrit', OPERATIVE, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/CloneActiveRegenAmmo/GPart_Operative_CloneActive_AmmoRegen', OPERATIVE, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/CloneSwapDamage/GPart_CloneSwap_WeaponDamage', OPERATIVE, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/CloneSwapInstaReload/GPart_Operative_CloneSwapInstaReload', OPERATIVE, {
            ATL_AR, ATL_PS, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM, HYP_SR,
            JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG,
            TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/DroneActiveBonusDamage/GPart_Operative_DroneActiveBonusDamage', OPERATIVE, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/DroneActiveFireRateReload/GPart_Operative_DroneActive_FireRateReload', OPERATIVE, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG,
            HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR,
            TED_PS, TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Operative/BarrierActive_StatusEffectChance/GPart_Operative_BarrierActive_StatusEffectChance', OPERATIVE, {
            COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM, HYP_SR,
            MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS,
            TOR_SG, VLA_AR, VLA_HW, VLA_PS, VLA_SR,
            }),

        # Base game Beastmaster
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/AttackCommandLifeSteal/GPart_Beast_AttackCmd_Lifesteal', BEASTMASTER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/Beast_Gamma_BonusRadiationDamage/GPart_BonusRadiationDamage', BEASTMASTER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/RakkAttackCharge/GPart_Beast_RakkCharge', BEASTMASTER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/RakkSlag/GPart_Beast_RakkSlag', BEASTMASTER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/RakkUsed_CritDamage/GPart_Beast_RakkCrit', BEASTMASTER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Beastmaster/StealthAccuracyHandling/GPart_Beast_Stealth_AccuracyHandling', BEASTMASTER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),

        # Base game Gunner
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_NextMagFireDamage/GPart_Gunner_NextMagFireDamage', GUNNER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_NextMagFirerateCrit/GPart_Gunner_NextMagFirerateCrit', GUNNER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_NextMagReloadHandling/GPart_Gunner_NextMagReloadHandling', GUNNER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/AutoBear_AmmoRegen/GPart_Gunner_AutoBear_AmmoRegen', GUNNER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/AutoBear_FireDamage/GPart_Gunner_AutoBear_FireDamage', GUNNER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_NoAmmoConsumption/GPart_Gunner_NoAmmoConsumption', GUNNER, {
            ATL_AR, ATL_PS, COV_AR, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR, HYP_SG, HYP_SM,
            HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS,
            TED_SG, TED_SM, TOR_AR, TOR_PS, TOR_SG, VLA_AR, VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_KillsLowerCooldown/GPart_Gunner_KillsLowerCooldown', GUNNER, {
            ATL_AR, ATL_HW, ATL_PS, COV_AR, COV_HW, COV_PS, DAL_AR, DAL_PS, DAL_SM, DAL_SR,
            HYP_SG, HYP_SM, HYP_SR, JAK_AR, JAK_PS, JAK_SG, JAK_SR, MAL_PS, MAL_SG, MAL_SM,
            MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR, TOR_HW, TOR_PS, TOR_SG, VLA_AR, VLA_HW,
            VLA_PS, VLA_SR,
            }),
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/Exit_SplashDamageIncrease/GPart_Gunner_SplashDamageIncrease', GUNNER, {
            ATL_HW, COV_HW, MAL_PS, MAL_SG, MAL_SM, MAL_SR, TED_PS, TED_SG, TED_SM, TOR_AR,
            TOR_HW, TOR_PS, TOR_SG, VLA_HW,
            }),

        # Base game Grenade Generics
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/_Generic/SkillStart_AddGrenade/GPart_All_SkillEnd_AddGrenade', GENERIC, {GR}),

        # Base game Grenade Gunner
        ('/Game/Gear/Weapons/_Shared/_Design/EndGameParts/Character/Gunner/IBActive_ChanceGrenade/GPart_Gunner_IBGrenadeChance', GUNNER, {GR}),

        ]

partlist_cache = {}

# Construct the anointment PartList
def construct_partlist(passed_anointments):
    """
    Constructs the anointment partlist
    """
    parts = ["""(
            PartData=None,
            Weight=(
                BaseValueConstant=1,
                BaseValueAttribute=GbxAttributeData'"{}"',
                BaseValueScale=1
            )
        )""".format(anoint_parts[NONE])]
    for (part_obj, part_type) in passed_anointments:
        parts.append("""(
            PartData=InventoryGenericPartData'"{}"',
            Weight=(
                BaseValueConstant=1,
                BaseValueAttribute=GbxAttributeData'"{}"',
                BaseValueScale=1
            )
        )""".format(
            Mod.get_full_cond(part_obj),
            anoint_parts[part_type],
            ))
    return '({})'.format(','.join(parts))

def get_partlist(weap_type):
    global partlist_cache
    global anointments

    if weap_type in partlist_cache:
        return partlist_cache[weap_type]

    this_anoints = []
    for (part_name, char, valid_types) in anointments:
        if weap_type in valid_types:
            this_anoints.append((part_name, char))
    partlist_cache[weap_type] = construct_partlist(this_anoints)
    return partlist_cache[weap_type]

# List of weapons which don't have anoints
weapons = [
        ("Amazing Grace",
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/AmazingGrace/Balance/Balance_PS_JAK_AmazingGrace',
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/AmazingGrace/Balance/InvPartSet_PS_JAK_AmazingGrace',
           JAK_PS),
        ("Amber Management",
           '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/AmberManagement/Balance/Balance_AR_TOR_AmberManagement',
           '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/AmberManagement/Balance/InvPartSet_AR_TOR_AmberManagement',
           TOR_AR),
        ("Baby Maker ++ (from Clapslist Reward)",
           '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/BabyMaker/Balance/Salvage/Balance_PS_Tediore_BabyMaker_Salvage',
           '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/BabyMaker/Balance/Salvage/InvPartSet_PS_TED_BabyMaker_Salvage',
           TED_PS),
        ("Big Succ",
           '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/BigSucc/Balance_AR_VLA_BigSucc',
           '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/BigSucc/InvPart_VLA_AR_BigSucc',
           VLA_AR),
        ("Black Flame",
           '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Brew/Balance/Balance_SG_TOR_Brewha',
           '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Brew/Balance/InvPartSet_SG_TOR_Brewha',
           TOR_SG),
        ("Brashi's Dedication",
           '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/BrashisDedication/Balance/Balance_SR_DAL_BrashisDedication',
           '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/BrashisDedication/Balance/PartSet_SR_DAL_BrashisDedication',
           DAL_SR),
        ("Buttplug",
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Buttplug/Balance/Balance_PS_JAK_Buttplug',
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Buttplug/Balance/InvPartSet_PS_JAK_Buttplug',
           JAK_PS),
        ("Extreme Hangin' Chadd",
           '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Chad/Balance/Balance_PS_COV_Chad',
           '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Chad/Balance/PartSet_PS_COV_Chad',
           COV_PS),
        ("Cold Shoulder",
           '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Prison/Balance/Balance_VLA_SR_Prison',
           '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Prison/Balance/PartSet_VLA_SR_Prison',
           VLA_SR),
        ("Emperor's Condiment",
           '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Emporer/Balance/Balance_SM_MAL_Emporer',
           '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Emporer/Balance/InvPartSet_SM_MAL_Emporer',
           MAL_SM),
        ("Fingerbiter",
           '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/Fingerbiter/Balance/Balance_SG_JAK_Fingerbiter',
           '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/Fingerbiter/Balance/PartSet_SG_JAK_Fingerbiter',
           JAK_SG),
        ("Gettleburger",
           '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/BurgerCannon/Balance/Balance_HW_TOR_BurgerCannon',
           '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/BurgerCannon/Balance/PartSet_HW_TOR_BurgerCannon',
           TOR_HW),
        ("Girth Blaster Elite",
           '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Nurf/Balance/Balance_PS_TOR_Nurf',
           '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Nurf/Balance/PartSet_PS_TOR_Nurf',
           TOR_PS),
        ("Hand of Glory",
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/HandOfGlory/Balance/Balance_AR_JAK_HandOfGlory',
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/HandOfGlory/Balance/InvPartSet_JAK_AR_HandOfGlory',
           JAK_AR),
        ("Hot Drop",
           '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/HotDrop/Balance/Balance_HW_COV_HotDrop',
           '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/HotDrop/Balance/PartSet_HW_COV_HotDrop',
           COV_HW),
        ("Hyper-Hydrator",
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/HyperHydrator/Balance/Balance_PS_MAL_HyperHydrator',
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/HyperHydrator/Balance/InvPartSet_PS_MAL_HyperHydrator',
           MAL_PS),
        ("Ice Queen",
           '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/IceQueen/Balance/Balance_SR_JAK_IceQueen',
           '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/IceQueen/Balance/PartSet_SR_JAK_IceQueen',
           JAK_SR),
        ("Just Kaus",
           '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/JustCaustic/Balance/Balance_SM_HYP_JustCaustic',
           '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/JustCaustic/Balance/InvPartSet_SM_HYP_JustCaustic',
           HYP_SM),
        ("Kenulox",
           '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/WorldDestroyer/Balance/Balance_SR_DAL_WorldDestroyer',
           '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/WorldDestroyer/Balance/PartSet_SR_DAL_WorldDestroyer',
           DAL_SR),
        ("Kevin's Chilly",
           '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Kevins/Balance/Balance_SM_MAL_Kevins',
           '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Kevins/Balance/InvPartSet_SM_MAL_Kevins',
           MAL_SM),
        ("Killing Word",
           '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Mouthpiece/Balance/Balance_PS_COV_Mouthpiece',
           '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Mouthpiece/Balance/PartSet_PS_COV_Mouthpiece',
           COV_PS),
        ("Leech",
           '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/TheLeech/Balance/Balance_PS_VLA_TheLeech',
           '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/TheLeech/Balance/InvPart_VLA_PS_TheLeech',
           VLA_PS),
        ("Linc",
           '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Drill/Balance/Balance_PS_ATL_Drill',
           '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Drill/Balance/PartSet_PS_ATL_Drill',
           ATL_PS),
        ("Null Pointer",
           '/Game/Gear/Weapons/_Shared/NPC_Weapons/Zero/ZeroForPlayer/Balance_SR_HYP_ZeroForPlayer',
           '/Game/Gear/Weapons/_Shared/NPC_Weapons/Zero/ZeroForPlayer/PartSet_SR_HYP_ZeroForPlayer',
           HYP_SR),
        ("Pa's Rifle",
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/PasRifle/Balance/Balance_AR_JAK_PasRifle',
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/PasRifle/Balance/InvPartSet_JAK_AR_PasRifle',
           JAK_AR),
        ("Peacemonger",
           '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Warmonger/Balance/Balance_PS_ATL_Warmonger',
           '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Warmonger/Balance/PartSet_PS_ATL_Warmonger',
           ATL_PS),
        ("Porta-Pooper 5000",
           '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/PortaPooper/Balance/Balance_HW_COV_PortaPooper',
           '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/PortaPooper/Balance/PartSet_HW_COV_PortaPooper',
           COV_HW),
        ("Pricker",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/Pricker/Balance/Balance_SM_HYP_Pricker',
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/Pricker/Balance/InvPartSet_SM_HYP_Pricker',
            HYP_SM),
        ("R.Y.N.A.H.",
           '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/RYNO/Balance/Balance_HW_TOR_RYNO',
           '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/RYNO/Balance/PartSet_HW_TOR_RYNO',
           TOR_HW),
        ("Robo-Melter",
           '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/RoboMasher/Balance/Balance_PS_JAK_RoboMasher',
           '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/RoboMasher/Balance/InvPartSet_PS_JAK_RoboMasher',
           JAK_PS),
        ("Rogue-Sight",
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/SpyRevolver/Balance_PS_JAK_SpyRevolver',
           '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/SpyRevolver/InvPartSet_PS_JAK_SpyRevolver',
           JAK_PS),
        ("Sellout",
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/SuckerPunch/Balance/Balance_PS_MAL_SuckerPunch',
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/SuckerPunch/Balance/InvPartSet_PS_MAL_SuckerPunch',
           MAL_PS),
        ("Starkiller",
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Starkiller/Balance/Balance_PS_MAL_Starkiller',
           '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Starkiller/Balance/InvPartSet_PS_MAL_Starkiller',
           MAL_PS),
        ("Traitor's Death",
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/TraitorsDeath/Balance/Balance_AR_JAK_TraitorsDeath',
           '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/TraitorsDeath/Balance/InvPartSet_JAK_AR_TraitorsDeath',
           JAK_AR),
        ("TWO TIME",
           '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/TwoTime/Balance/Balance_SR_HYP_TwoTime',
           '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/TwoTime/Balance/PartSet_SR_HYP_TwoTime',
           HYP_SR),
        ("Vault Hero",
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/E3/Balance_SM_MAL_E3',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/E3/InvPartSet_SM_MAL_E3',
            MAL_SM),
        ("Ghast Call",
            '/Game/PatchDLC/BloodyHarvest/Gear/GrenadeMods/_Design/_Unique/FontOfDarkness/Balance/InvBalD_GM_TOR_FontOfDarkness',
            '/Game/PatchDLC/BloodyHarvest/Gear/GrenadeMods/_Design/_Unique/FontOfDarkness/Balance/PartSet_GM_FontOfDarkness',
            GR),
        
        # DLC2 Weapons
        ("Firecracker",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Firecracker/Balance/Balance_SG_HYP_Firecracker',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Firecracker/Balance/InvPartSet_SG_HYP_Firecracker',
            HYP_SG),
        ("Kaleidoscope",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Kaleidoscope/Balance/Balance_DAL_PS_Kaleidoscope',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Kaleidoscope/Balance/PartSet_DAL_PS_Kaleidoscope',
            DAL_PS),
        ("Love Drill (mission version)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/Balance/Balance_PS_JAK_LoveDrill',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/Balance/InvPartSet_PS_JAK_LoveDrill',
            JAK_PS),
        ("Sacrificial Lamb",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SacrificalLamb/Balance/Balance_SG_TED_SacrificialLamb',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SacrificalLamb/Balance/PartSet_SG_TED_SacrificialLamb',
            TED_SG),
        ("The Cure",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheCure/Balance/Balance_SG_JAK_TheCure',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheCure/Balance/PartSet_SG_JAK_TheCure',
            JAK_SG),
        # There are two more Seventh Sense balances in "SeventhSense" (without "The"), but I think if those are
        # used at all, it's just as an enemy-use-only version.
        ("Seventh Sense (mission version)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/Balance_PS_JAK_TheSeventhSense_MissionWeapon',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/InvPartSet_PS_JAK_TheSeventhSense_MissionWeapon',
            JAK_PS),
        ("Seventh Sense (legendary version)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/Balance_PS_JAK_TheSeventhSense',
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/Balance/InvPartSet_PS_JAK_TheSeventhSense',
            JAK_PS),

        # DLC3 Weapons
        ("Bubble Blaster",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BubbleBlaster/Balance/Balance_PS_MAL_BubbleBlaster',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BubbleBlaster/Balance/InvPartSet_PS_MAL_BubbleBlaster',
            MAL_PS),
        ("Marshal",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Sheriff/Balance/Balance_PS_JAK_Sheriff',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Sheriff/Balance/InvPartSet_PS_JAK_Sheriff',
            JAK_PS),
        ("Peashooter",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Peashooter/Balance/Balance_PS_JAK_Peashooter',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Peashooter/Balance/InvPartSet_PS_JAK_Peashooter',
            JAK_PS),
        ("Quickdraw",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/QuickDraw/Balance/Balance_PS_JAK_QuickDraw',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/QuickDraw/Balance/InvPartSet_PS_JAK_QuickDraw',
            JAK_PS),
        ("Splinter",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Splinter/Balance/Balance_SG_JAK_Splinter',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Splinter/Balance/PartSet_SG_JAK_Splinter',
            JAK_SG),
        ("The Beast (rad)",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/Balance_AR_COV_BioBetsy_Rad',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/InvPartSet_AR_COV_BioBetsy_Rad',
            COV_AR),
        ("The Beast (shock)",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/Balance_AR_COV_BioBetsy_Shock',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/Balance/InvPartSet_AR_COV_BioBetsy_Shock',
            COV_AR),
        ("The Chalice",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/McSmugger/Balance/Balance_AR_JAK_McSmugger',
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/McSmugger/Balance/InvPartSet_JAK_AR_McSmugger',
            JAK_AR),
        # Leaving The Shoddy out of this intentionally.
        #("The Shoddy",
        #    '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Fakobs/Balance/Balance_SG_JAK_Fakobs',
        #    '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Fakobs/Balance/PartSet_SG_JAK_Fakobs',
        #    JAK_SG),
        ]

# Now do the actual mod
for (label, balance, partset, weap_type) in sorted(weapons):
    mod.comment(label)

    part_data = get_partlist(weap_type)

    # First the Balance
    mod.reg_hotfix(Mod.PATCH, '',
            balance,
            'RuntimeGenericPartList.bEnabled',
            'True')
    mod.reg_hotfix(Mod.PATCH, '',
            balance,
            'RuntimeGenericPartList.PartList',
            part_data)

    # Then the PartSet
    mod.reg_hotfix(Mod.PATCH, '',
            partset,
            'GenericParts.bEnabled',
            'True')
    mod.reg_hotfix(Mod.PATCH, '',
            partset,
            'GenericParts.PartList',
            part_data)

    mod.newline()

mod.close()
