#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

from bl3hotfixmod.bl3hotfixmod import Mod

mod = Mod('vehicle_unlocks.txt',
        'Vehicle Unlocks',
        [
            "Attempts to unlock all vehicle parts/skins from the beginning of the game,",
            "though note that this doesn't *really* do that yet.  A lot of parts/skins",
            "are dependent on the SpawnOptions used by the level, so you're still only",
            "going to have a small number of parts/skins available in The Droughts, for",
            "instance, because that level's Outrunner SpawnOptions just doesn't have",
            "hardly anything in it.",
            "",
            "Still, it's possible that this may unlock some parts/skins a bit early.",
            "It's not really tested, since I've never really paid too close attention",
            "to when those things become available, so hopefully I don't have some stupid",
            "error in here which makes this do literally nothing.  Ah well!",
            "",
            "Eventually I hope to figure out expanding the actual SpawnOptions structures,",
            "but so far that's eluded me.",
        ],
        'VUnlocks',
        )

for (label, table, col_name, rows) in [
        ('Vehicle Parts (table 1)',
            '/Game/Vehicles/_Shared/Design/Balance/Data/DataTable_VehiclePartsData',
            'MinGameStage_15_D986BDE142AA94D9995403BC41D5DA70',
            [
                'Technical_StickyBombs',
                'Technical_FlakCannon',
                'Technical_ToxicBooster',
                'Technical_FuelBarrels',
                'Outrunner_TwitchyWheels',
                'Outrunner_HoverWheels',
                'Outrunner_TeslaCoil',
                'Outrunner_FlameThrower',
                'Outrunner_ShotgunMissile',
                'Outrunner_SwarmerMissile',
                'Outrunner_BlazeBooster',
                'Revolver_DualWheel',
                'Revolver_HoverWheels',
                'Revolver_HeavyArmor',
                'Revolver_FireStarter',
                'Revolver_SpikeLauncher',
                'Revolver_SawBladeLauncher',
                ]),
        ('Vehicle Parts (table 2)',
            '/Game/Vehicles/_Shared/Design/Balance/Data/DataTable_VehiclePartsSchedule',
            'MinGameStage_17_2500317646FAD2F4916D158835B29E83',
            [
                'Technical_Mod_ToxicBoost',
                'Technical_Mod_FuelBarrels',
                'Technical_Armor_Heavy',
                'Technical_Wep_FlakCannon',
                'Outrunner_Wheels_Twitchy',
                'Outrunner_Wheels_Hover',
                'Outrunner_Mod_BlazeBoost',
                'Outrunner_Wep_Flamethrower',
                'Outrunner_Wep_TeslaCoil',
                'Outrunner_Wep_SwarmerMissile',
                'Outrunner_Wep_ShotgunMissile',
                'Revolver_Wheel_Dual',
                'Revolver_Wheel_Hover',
                'Revolver_Mod_FireStarter',
                'Revolver_Armor_Heavy',
                'Revolver_Wep_SpikeLauncher',
                'Revolver_Wep_Sawblades',
                ]),
        ('Vehicle Skins',
            '/Game/Vehicles/_Shared/Design/Balance/Data/DataTable_VehicleSkinSchedule',
            'MinGameStage_17_2500317646FAD2F4916D158835B29E83',
            [
                'Outrunner_PsychoMobile',
                'Outrunner_Houndstooth',
                'Outrunner_Forest',
                'Outrunner_GoldenHog',
                'Outrunner_Borderlandstton',
                'Outrunner_HistoricRacing',
                'Outrunner_Bubblegum',
                'Outrunner_RageCage',
                'Outrunner_Pirate',
                'Outrunner_RedMachine',
                'Technical_Bubblegum',
                'Technical_Desert',
                'Technical_Blueangels',
                'Technical_Halftone',
                'Technical_Forest',
                'Technical_Leather',
                'Technical_Stealth',
                'Technical_Thunderbird',
                'Revolver_Chopper',
                'Revolver_Lollipop',
                'Revolver_Dark',
                'Revolver_Forest',
                'Revolver_Bubblegum',
                'Revolver_Golden',
                'Revolver_Lifeline',
                'Revolver_Maliwan',
                'Revolver_Stealth',
                ]),
        ]:
    table_last = table.split('/')[-1]
    full_table = f'{table}.{table_last}'
    mod.comment(label)
    for row in rows:
        mod.table_hotfix(Mod.PATCH, '',
                full_table,
                row,
                col_name,
                0)
    mod.newline()

mod.close()
