#!/usr/bin/env python3
# vim: set expandtab tabstop=4 shiftwidth=4:

# Copyright 2019-2020 Christopher J. Kucera
# <cj@apocalyptech.com>
# <http://apocalyptech.com/contact.php>
#
# This Borderlands 3 Hotfix Mod is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# This Borderlands 3 Hotfix Mod is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this Borderlands 3 Hotfix Mod.  If not, see
# <https://www.gnu.org/licenses/>.

from bl3hotfixmod.bl3hotfixmod import Mod

mod = Mod('red_text_explainer.txt',
        'Red Text Explainer',
        'Apocalyptech',
        [
            "Inspired by Ezeith's BL2 Red Text Explainer",
            '',
            'Adds explanations in the red text for all legendary/unique weapons and',
            'grenade mods.  Shields, COMs, and Artifacts have been omitted since they',
            'already detail their special functions on the card text.',
            '',
            'Text mostly summarized from borderlands.fandom.com, so take with a grain',
            'of salt. :)  Some weapons could use some verification, especially the ones',
            'whose special abilities appear to just be the "better" stats on the card.',
        ],
        lic=Mod.CC_BY_SA_40,
        )

def elementize(text):
    for snippet, tag in [
            ('corrosive', 'corrosive'),
            ('cryo', 'cryo'),
            ('incendiary', 'fire'),
            ('ignite', 'fire'),
            ('ignites', 'fire'),
            ('radiation', 'radiation'),
            ('radioactive', 'radiation'),
            ('shock', 'shock'),
            ('electrocute', 'shock'),
            ('electrocutes', 'shock'),
            ('explosive', 'bold'),
            ]:
        text = text.replace(snippet, '[{}]{}[/{}]'.format(tag, snippet, tag))
    return text

ON_CARD = 'all effects on card'

for (gear_name, obj_name, redtext, explanation) in [
        # Vault Hero has no red text.  No special abilities for it, though.
        # Elemental Persistent Contact Grenade is a sort-of "unique" purple grenade dropped by Jabbermogwai, but
        #    it doesn't do anything special (or have red text)
        # Re-Router doesn't have red text, though it already explains what it does on the card, so whatever.
        ('9-Volt',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/NineVolt/UIStat_NineVolt_Flavor.UIStat_NineVolt_Flavor',
            "Contact.",
            "7 pellets in inverted triangle, alt mode changes zoom"),
        ('AAA',
            '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/AAA/UIStat_RedText_AAA.UIStat_RedText_AAA',
            "Hold on! They're lithium!",
            "always shock, 6 projectiles in shape of [bold]A[/bold]"),
        ('ASMD',
            '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/ASMD/UIStat_RedText_ASMD.UIStat_RedText_ASMD',
            "You planning a follow-up?",
            "instant fire, Unreal shock-rifle-alike"),
        ('Agonizer 1500',
            '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/Terror/UIStat_RedText_Terror.UIStat_RedText_Terror',
            "Bow to Drell, the pot roast king.",
            "3 explosive sawblades which home in on enemies"),
        ('Alchemist',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/Alchemist/UIStat_RedText_Alchemist.UIStat_RedText_Alchemist',
            "You can't gain something without giving something in return.",
            "gyrojets deal shock damage, player takes small shock damage on hit"),
        ('Amazing Grace',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/AmazingGrace/UIStat_RedText_AmazingGrace.UIStat_RedText_AmazingGrace',
            "Memento mori.",
            "critical hits add 1 bullet to mag"),
        ('Amber Management',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/AmberManagement/UIStat_RedText_AmberManagement.UIStat_RedText_AmberManagement',
            "Will end your soul.",
            "anger kills increase damage, Happiness kills heal"),
        ('Baby Maker ++',
            '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/BabyMaker/UIStat_RedText_BabyMaker.UIStat_RedText_BabyMaker',
            "Safety off.",
            "reloads explode into 4 homing projectiles"),
        ('Back Ham',
            '/Game/Gear/Shields/_Design/_Uniques/BackHam/Name/UIStat_RedText_BackHam.UIStat_RedText_BackHam',
            "Synthetic Vercuvian ham. Typhon DeLeon approved.",
            "reduced damage from behind, chance to reflect when charged"),
        ('Band of Sitorak',
            '/Game/Gear/Shields/_Design/_Uniques/Cyttorak/UI/UIStat_RedText_Cyttorak.UIStat_RedText_Cyttorak',
            "I said, “biiiiiiiiiiiitttccchhhh...”",
            "+22% weapon damage when depleted, 25% max health"),
        ('Bangarang',
            '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/_Bangarang/UIStat_RedText_Bangarang.UIStat_RedText_Bangarang',
            "To die would be a grand adventure.",
            "spins horizontally and sprays bullets"),
        ('Barrage',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Barrage/UIStat_RedText_Barrage.UIStat_RedText_Barrage',
            "Quick maths.",
            "always burst, alt fire mode toggles zoom"),
        ('Bearcat',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/Bearcat/UIStat_RedText_Bearcat.UIStat_RedText_Bearcat',
            "I love the smell of popcorn in the morning.",
            "3 bouncing grenades in horizontal row, 4 ammo per shot"),
        ('Bekah',
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/Bekah/UIStat_RedText_Bekah.UIStat_RedText_Bekah',
            "Shoot them in the face. Twice.",
            "splits into horizontal pattern of 3 bullets"),
        ('Big Boom Blaster',
            '/Game/Gear/Shields/_Design/_Uniques/BigBoomBlaster/Name/UIStat_RedText_BigBoomBlaster.UIStat_RedText_BigBoomBlaster',
            "For all your big boom blasting needs!",
            "boosters restore shields, grenade, and ammo"),
        ('The Big Succ',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/BigSucc/UIStat_RedText_BigSucc.UIStat_RedText_BigSucc',
            "What dat underbarrel do?",
            "grenade underbarrel"),
        ('Bitch',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Bitch/UIStat_RedText_Bitch.UIStat_RedText_Bitch',
            "If you can't handle me at my worst...",
            ON_CARD),
        ('Black Flame',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Brew/UIStat_RedText_Shroom.UIStat_RedText_Shroom',
            "A virgin lit the candle.",
            "just mission-related"),
        ('Black Hole',
            '/Game/Gear/Shields/_Design/_Uniques/BlackHole/Name/UIStat_RedText_BlackHole.UIStat_RedText_BlackHole',
            "She’s gone from suck to blow.",
            "nova pushes enemies"),
        ('Bone Shredder',
            '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/BoneShredder/UIStat_RedText_BoneShredder.UIStat_RedText_BoneShredder',
            "THE LEAD WIND BLOWS!",
            ON_CARD),
        ('The Boo+',
            '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/Beans/UIStat_RedText_Beans.UIStat_RedText_Beans',
            "We gotchu.",
            "on reload, becomes a turret with legs"),
        ('Boom Sickle / Sickle',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Sickle/UIStat_RedText_Sickle.UIStat_RedText_Sickle',
            "Swing the sickle!",
            "blasts in shape of sickle"),
        ('The Boring Gun',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/TheBoringGun/UIStat_RedText_Boring.UIStat_RedText_Boring',
            "This is beyond science.",
            "shoots 3 sawblades that roll along the ground"),
        ('Brainstormer',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Redistributor/UIStat_RedText_Redistributor.UIStat_RedText_Redistributor',
            "Let's put our heads together.",
            "7 projectiles in lightning bolt pattern, hit targets chain heavily"),
        ("Brashi's Dedication",
            '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/BrashisDedication/UIStat_RedText_BrashisDedication.UIStat_RedText_BrashisDedication',
            "Three sims are better than one.",
            "three projectiles, two orbiting the middle"),
        ('Breath of the Dying',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/BOTD/UIStat_RedText_BOTD.UIStat_RedText_BOTD',
            "VexHelElEldZodEth.",
            "kills make the enemy explode, releasing corrosive balls"),
        ('Breeder',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Echo/UIStat_RedText_Breeder.UIStat_RedText_Breeder',
            "Man hands on misery to man.",
            "projectiles stick and spawn 2 extra arcing projectiles"),
        ('Burning Summit',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Summit/UIStat_RedText_Summit.UIStat_RedText_Summit',
            "Can we get some 1G's in the chat?",
            "explodes in your face"),
        ('The Butcher',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/TheButcher/UIStat_RedText_TheButcher.UIStat_RedText_TheButcher',
            "Fresh meat!",
            "chance to refill mag by random amount when fired"),
        ('Buttplug',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Buttplug/UIStat_RedText_Buttplug.UIStat_RedText_Buttplug',
            "You plug 'em, and they'll be on their butt.",
            "double melee damage from behind"),
        ('Carrier',
            '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/Carrier/UIStat_RedText_Carrier.UIStat_RedText_Carrier',
            "I have arrived.",
            "hits spawn additional homing bullets"),
        ('Chocolate Thunder',
            '/Game/Gear/GrenadeMods/_Design/_Unique/JustDeserts/Name/UIStat_RedText_JustDeserts.UIStat_RedText_JustDeserts',
            "Boom chocolaka!",
            "exploding cake!"),
        ('Chomper',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Balrog/UIStat_RedText_Balrog.UIStat_RedText_Balrog',
            "Shotguna dentata!",
            "teeth of Terramorphous; extra projectiles disappear after second bite"),
        ("Chupa's Organ",
            '/Game/Gear/GrenadeMods/_Design/_Unique/Chupa/UI/UIStat_RedText_Chupa.UIStat_RedText_Chupa',
            "Cabrón.",
            "sticks to a target and drains their health, healing player"),
        ('Cloud Kill',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/CloudKill/UIStat_RedText_CloudKill.UIStat_RedText_CloudKill',
            "Now, you will rise.",
            "creates corrosive cloud"),
        ('Cold Shoulder',
            '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Prison/UIStat_RedText_Prison.UIStat_RedText_Prison',
            "Say “freeze”!",
            ON_CARD),
        ('The Companion',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/UIStat_RedText_MelsCompanion.UIStat_RedText_MelsCompanion',
            "You can't take the sky from me.",
            "cannot ignite without critical hit"),
        ('Conference Call',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/ConferenceCall/UIStat_RedText_ConferenceCall.UIStat_RedText_ConferenceCall',
            "Let's just ping everyone all at once.",
            "shots split on hit / after a time"),
        ('Creeping Death',
            '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Sludge/UIStat_RedText_Sludge.UIStat_RedText_Sludge',
            "I creep across the land.",
            "fires orbs that stick to the surface and follow the gun"),
        ('Crit',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Crit/UIStat_RedText_Crit.UIStat_RedText_Crit',
            "Slippery when wet.",
            "heals player, has a chance to drop when reloading"),
        ('Crossroad',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Crossroad/UIStat_RedText_Crossroad.UIStat_RedText_Crossroad',
            "Open the gate for me.",
            "instant fire, 3 projectiles/2 ammo per shot, bursts of 6"),
        ('Cutsman',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Cutsman/UIStat_RedText_Cutsman.UIStat_RedText_Cutsman',
            "Little android man, born without a soul.",
            "projectiles stretch horizontally"),
        ('Damned',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Damn/UIStat_RedText_Damn.UIStat_RedText_Damn',
            "Well, I'll be...",
            "hyperion-style shield"),
        ('Dead Chamber',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Malevolent/UIStat_RedText_Malevolent.UIStat_RedText_Malevolent',
            "You're not playing the odds, friend.",
            "50% chance to buff weapon on reload"),
        ('Deluxe Badass Combustor',
            '/Game/Gear/Shields/_Design/_Uniques/_XPLootBooster/Name/UIStat_RedText_XPLootBooster.UIStat_RedText_XPLootBooster',
            "Take it up to eleven!",
            "XP, Loot boos up to level 10"),
        ('Destructo Spinner',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/DestructoSpin/UIStat_RedText_DestructoSpin.UIStat_RedText_DestructoSpin',
            "I've been hired for destruction.",
            "both elements fire in corkscrew, alt mode determines splash type"),
        ('Devastator',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Devestator/UIStat_RedText_Devestator.UIStat_RedText_Devestator',
            "Hail.",
            "slower projectiles, increased blast radius, 2-round burst"),
        ('Devils Foursum',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Foursum/UIStat_RedText_4SUM.UIStat_RedText_4SUM',
            "I love it when a plan comes together.",
            "3 projectiles reconverge after a short distance"),
        ('Devoted',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Devoted/UIStat_RedText_Devoted.UIStat_RedText_Devoted',
            "This is your champion.",
            "instant fire, fire rate increases over time"),
        ('The Dictator',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Dictator/UIStat_RedText_Dictator.UIStat_RedText_Dictator',
            "Let them hate me, so that they will but fear me.",
            "3 bullets in rifle mode, 7 in bipod mode"),
        ('Diamond Butt Bomb',
            '/Game/Gear/GrenadeMods/_Design/_Unique/ButtStallion/Name/UIStat_RedText_ButtStallion.UIStat_RedText_ButtStallion',
            "Bye bye, Li'l Butt Stallion!",
            "homing Butt Stallions"),
        ('The Duc',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/TheDuc/UIStat_RedText_TheDuc.UIStat_RedText_TheDuc',
            "Fire that off to me real quick.",
            "bullets stick to foes and explode after delay, crits ricochet 2"),
        ('E-Gone',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Egon/UIStat_RedText_Egon.UIStat_RedText_Egon',
            "Don't cross the streams.",
            "continuous laser beam"),
        # The internet believes that the ECHO-2 behaves differently depending on whether you look at
        # it or not, but my testing doesn't bear that out.  IMO that was something that was mentioned
        # once or twice online and everyone else just ran with it without checking and spread it
        # around.
        ('ECHO-2',
            '/Game/Gear/GrenadeMods/_Design/_Unique/EchoV2/UIStat_RedText_EchoV2_3.UIStat_RedText_EchoV2_3',
            "Do not look directly at ECHO-2.",
            #"damage, radius, and fuse time depend on player looking at it (best not to?)"),
            "no special effects, despite what the internet says"),
        ('Embrace the Pain',
            '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/_Unique/KriegAR/UIStat_RedText_HeatFirerate.UIStat_RedText_HeatFirerate',
            "It hurts, hahahahaha! IT HURTS!",
            "will ignite player; during overheat, consumes no ammo"),
        ('EMP',
            '/Game/Gear/GrenadeMods/_Design/_Unique/EMP/UIStat_RedText_EMP.UIStat_RedText_EMP',
            "Drop the shields.",
            "only damages shields"),
        ("The Emperor's Condiment",
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Emporer/UIStat_RedText_Emporer.UIStat_RedText_Emporer',
            "I am the punishment of the food gods.",
            "shoots laser beam that looks like mustard"),
        ('Earworm',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Earworm/UIStat_RedText_Earworm.UIStat_RedText_Earworm',
            "The deadliest summer hit.",
            "plays music while in use"),
        ('Echo',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Echo/UIState_RedText_Echo1.UIState_RedText_Echo1',
            "Don't make me repeat myself.",
            "sticky rounds explode 3 times"),
        ('Epicenter',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Epicenter/UI/UIStat_RedText_Epicenter.UIStat_RedText_Epicenter',
            "It burns, burns, burns.",
            "ring of 13 orbs which deal incendiary damage"),
        ('Exterminator',
            '/Game/Gear/GrenadeMods/_Design/_Unique/BirthdaySuprise/UI/UIStat_RedText_BirthdaySuprise.UIStat_RedText_BirthdaySuprise',
            "Give me sugar.",
            "extra damage to bugs"),
        ("Extreme Hangin' Chadd",
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Chad/UIStat_RedText_Chad.UIStat_RedText_Chad',
            "So Chadd's not even real?",
            "does not consume ammo, very sturdy"),
        ('Face-puncher',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Brick/UIStat_RedText_Brick.UIStat_RedText_Brick',
            "Man your own jackhammer.",
            "listed damage based on character's melee damage"),
        ('Faisor',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Faisor/UIStat_RedText_Faisor.UIStat_RedText_Faisor',
            "Set Faisers to kill.",
            "fires elemental bolts"),
        ('Fastball',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Fastball/Name/UIStat_RedText_Fastball.UIStat_RedText_Fastball',
            "Forget the curveball Ricky, give him the heater.",
            "flat arc and fast travel speed"),
        ('Fearmonger',
            '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Fearmonger/UIStat_RedText_Fearmonger.UIStat_RedText_Fearmonger',
            "I can't control their fear, only my own.",
            "shoots multiple projectiles in square, which explode after short delay"),
        ('Fingerbiter',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/Fingerbiter/UIStat_RedText_Fingerbiter.UIStat_RedText_Fingerbiter',
            "I suppose you are wondering about my bandages.",
            "bullets ricochet up to 4 times, travel in arcs"),
        ('Firestorm',
            '/Game/Gear/GrenadeMods/_Design/_Unique/FireStorm/Name/UIStat_RedText_FireStorm.UIStat_RedText_FireStorm',
            "Soon afterwards, the cloud descended upon the earth.",
            "calls down rain of meteors"),
        ('Firestorm',
            '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Storm/UIStat_RedText_FireStorm.UIStat_RedText_FireStorm',
            "Seek shelter immediately.",
            "spawns 3 incendiary orbs around impact"),
        ('Flakker',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Flakker/UIStat_RedText_Flakker.UIStat_RedText_Flakker',
            "Flak the world.",
            "continuously generate explosions"),
        ('The Flood',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Doc/UIStat_RedText_Doc.UIStat_RedText_Doc',
            "Take us.",
            "full auto"),
        ('Freeman',
            '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/_Unique/Freeman/UIStat_RedText_Freeman.UIStat_RedText_Freeman',
            "The right man in the wrong place can make all the difference in the world.",
            "rockets follow crosshairs"),
        ('Front Loader',
            '/Game/Gear/Shields/_Design/_Uniques/FrontLoader/Name/UIStat_RedText_FrontLoader.UIStat_RedText_FrontLoader',
            "You could always use a little more life insurance.",
            "converts health to shields"),
        ('Frozen Heart',
            '/Game/Gear/Shields/_Design/_Uniques/Aurelia/Name/UIStat_RedText_Aurelia.UIStat_RedText_Aurelia',
            "I feel... cold.",
            "return nova damage as health"),
        ('Fungus Among Us',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Mushroom/UIStat_RedText_ShroomGM.UIStat_RedText_ShroomGM',
            "Turn on, tune in, drop out.",
            "creates mushroom on impact which explodes into corrosive cloud"),
        ('The Garcia',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Garcia/UIStat_RedText_Garcia.UIStat_RedText_Garcia',
            "Rooty-tooty, pointy-shooty.",
            "increased mag size"),
        ('Gatling Gun',
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/GatlingGun/UIStat_RedText_GatlingGun.UIStat_RedText_GatlingGun',
            "Watch me crank it, watch me roll.",
            "full auto"),
        ('Gettleburger',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/BurgerCannon/UIStat_RedText_BurgerCannon.UIStat_RedText_BurgerCannon',
            "Dayum. Dayum! DAYUM!",
            "fires cheeseburgers"),
        ('Ghast Call',
            '/Game/PatchDLC/BloodyHarvest/Gear/GrenadeMods/_Design/_Unique/FontOfDarkness/UI/UIStat_RedText_FontOfDarkness.UIStat_RedText_FontOfDarkness',
            "To you I am past, a story to tell.",
            "launches a ghast skull which creates ghast rift"),
        ('Girth Blaster Elite (joke weapon)',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Nurf/UIStat_RedText_Nurf.UIStat_RedText_Nurf',
            "Don't go to pieces on me.",
            "joke gun"),
        ('Golden Touch',
            '/Game/Gear/Shields/_Design/_Uniques/GoldenTouch/Name/UIStat_RedText_GoldenTouch.UIStat_RedText_GoldenTouch',
            "I wanna know where the gold at.",
            ON_CARD),
        ('Gunerang',
            '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/Gunerang/UIStat_RedText_Gunerang.UIStat_RedText_Gunerang',
            "Give it a burl.",
            "discarded weapon returns to player"),
        ('Hail',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Hail/UIStat_RedText_Hail.UIStat_RedText_Hail',
            "What plaything can you offer me today?",
            "parabolic projectiles, player is healed"),
        ('Hand of Glory',
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/HandOfGlory/UIStat_RedText_HandOfGlory.UIStat_RedText_HandOfGlory',
            "By one, by two, by three!",
            "bursts of 2 with a short delay after 3 bursts"),
        ('Handsome Jackhammer',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Handsome/UIStat_RedText_Handsome.UIStat_RedText_Handsome',
            "Everyone thinks they are the hero of their own story.",
            "Tediore-like reload, Jack voice module"),
        ('Headsplosion',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/Headsplosion/UIStat_RedText_Headsplosion.UIStat_RedText_Headsplosion',
            "That happens all the time.",
            "explosive rounds, crits ricochet three rounds"),
        ('Heckle',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/HeckelAndHyde/Heckle/UIStat_RedText_Heckle.UIStat_RedText_Heckle',
            "Am I evil?",
            ON_CARD),
        ('Hellfire',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/HellFire/UIStat_RedText_HellFire.UIStat_RedText_HellFire',
            "We don't need no... something...",
            "alt fire toggles zoom"),
        ('Hellshock',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Hellshock/UIStat_RedText_Hellshock.UIStat_RedText_Hellshock',
            "I had not thought death had undone so many.",
            "projectiles switch element on bounce"),
        ('Hellwalker',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Hellwalker/UIStat_RedText_Hellwalker.UIStat_RedText_Hellwalker',
            "So, my demons. Your time has come.",
            "pentagram fire pattern, DOOM sfx"),
        ('Hex',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Seeker/UIStat_RedText_Seeker.UIStat_RedText_Seeker',
            "Keeper of the stars, I hope to never find...",
            "homing, does high elemental damage"),
        ('Hive',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Hive/UIStat_RedText_Hive.UIStat_RedText_Hive',
            "Full of bees.",
            "generates homing rockets on impact"),
        ('The Horizon',
            '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Horizon/UIStat_RedText_Horizon.UIStat_RedText_Horizon',
            "You can't leave. She won't let you.",
            "reloaded weapon can be shot to create singularity"),
        ('Hornet',
            '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Hornet/UIStat_RedText_Hornet.UIStat_RedText_Hornet',
            "Fear the swarm!",
            "6-round burst, alt fire toggles zoom"),
        ('Hot Drop',
            '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/HotDrop/UIStat_RedText_HotDrop.UIStat_RedText_HotDrop',
            "We are coming out hot.",
            "creates incendiary pool and launches 2 small projectiles on impact"),
        ('The Hunt(ed)',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/UIStat_RedText_Hunted.UIStat_RedText_Hunted',
            "So dead.",
            ON_CARD),
            #"+175% damage against robots"),
        ('The Hunt(er)',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/UIStat_RedText_Hunter.UIStat_RedText_Hunter',
            "So big.",
            ON_CARD),
            #"+175% damage against creatures"),
        ('The Hunt(ress)',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/TheHunter/UIStat_RedText_Huntress.UIStat_RedText_Huntress',
            "So angry.",
            ON_CARD),
            #"+175% damage against humans"),
        ('Hunter-Seeker',
            '/Game/Gear/GrenadeMods/_Design/_Unique/HunterSeeker/UI/UIStat_RedText_HunterSeeker.UIStat_RedText_HunterSeeker',
            "Grip tightly.",
            "drone homes in on enemies while shooting"),
        ('Hyde',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/HeckelAndHyde/Hyde/UIStat_RedText_Hyde.UIStat_RedText_Hyde',
            "Yes, I am.",
            ON_CARD),
        ('Hyper-Hydrator',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/HyperHydrator/UIStat_RedText_HyperHydrator.UIStat_RedText_HyperHydrator',
            "Moister is noice-ter.",
            "instant fire, alt fire increases shock damage"),
        ('Hyperfocus XZ41',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/XZ/UIStat_RedText_XZ.UIStat_RedText_XZ',
            "My line has ended.",
            "hits spawn two bouncy ricochets"),
        ('The Ice Queen',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/IceQueen/UIStat_RedText_IceQueen.UIStat_RedText_IceQueen',
            "Let it go!",
            ON_CARD),
        ('Impaler',
            '/Game/Gear/Shields/_Design/_Uniques/Impaler/Name/UIStat_RedText_Impaler.UIStat_RedText_Impaler',
            "Out for a walk, bitch.",
            "homing spikes when damaged by bullets"),
        ('Infinity',
            '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/Infiniti/UIStat_RedText_Infiniti.UIStat_RedText_Infiniti',
            "It's closer than you think! (no it isn't)",
            "does not consume ammo"),
        ("It's Piss",
            '/Game/Gear/GrenadeMods/_Design/_Unique/Piss/UI/UIStat_RedText_Piss.UIStat_RedText_Piss',
            "Hey you guys!",
            "clears status effects from allies"),
        ('Jericho',
            '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/_Unique/CloudBurst/UIStat_RedText_CloudBurst.UIStat_RedText_CloudBurst',
            "I prefer the weapon you only need to fire once.",
            "shots rise into air, explode, release 3 downward projectiles"),
        ('Kaos',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Kaos/UIStat_RedText_Kaos.UIStat_RedText_Kaos',
            "Grants the mystical art of exploding smallhands.",
            "killed enemies generate a large matching-element explosion"),
        ('Kenulox',
            '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/WorldDestroyer/UIStat_RedText_WorldDestroyer.UIStat_RedText_WorldDestroyer',
            "Live life like it's early access.",
            "1-ammo shot cost, alt fire toggles zoom"),
        ("Kevin's Chilly",
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Kevins/UIStat_RedText_Kevins.UIStat_RedText_Kevins',
            "This one goes to keleven.",
            "just mission item"),
        ("Kill-o'-the-Wisp",
            '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Wisp/UIStat_RedText_Wisp.UIStat_RedText_Wisp',
            "Some say it can lead you to your fate.",
            "slow sphere which detonates on fixed distance"),
        ('The Killing Word',
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Mouthpiece/UIStat_RedText_Mouthpiece.UIStat_RedText_Mouthpiece',
            "His word will carry death eternal.",
            "oscillating projectiles"),
        ("King's Call / Queen's Call",
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/GodMother/UIStat_RedText_GodMother.UIStat_RedText_GodMother',
            "Life is ours, we live it our way.",
            "crits return 3 to mag and ricochet 3"),
        ('Krakatoa',
            '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Krakatoa/UIStat_RedText_Krakatoa.UIStat_RedText_Krakatoa',
            "Get him angry and he's bound to erupt.",
            "killed enemies generate volcano"),
        ('Kryll',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Kryll/UI/UIStat_RedText_Kryll.UIStat_RedText_Kryll',
            "Besiege!",
            "MIRV whose children become fast-moving homing mini-MIRVs after a short time"),
        ('L0V3M4CH1N3',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/L0V3M4CH1N3/UIStat_RedText_L0V3M4CH1N3.UIStat_RedText_L0V3M4CH1N3',
            "Love always undermines righteous action.",
            "bullets in heart pattern"),
        ('Laser-Sploder',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/LaserSploder/UIStat_RedText_LaserSploder.UIStat_RedText_LaserSploder',
            "LASERS ≠ EXPLOSIONS?!",
            "simultaneous beam and rockets"),
        ('Lead Sprinkler',
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/LeadSprinkler/UIStat_RedText_LeadSprinkler.UIStat_RedText_LeadSprinkler',
            "Splish splash.",
            "hits spawn extra pellets"),
        ('The Leech',
            '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/TheLeech/UIStat_RedText_TheLeech.UIStat_RedText_TheLeech',
            "Today, a new emperor must seize the throne.",
            "alt fire ignites enemies and heals the player"),
        ('Linc',
            '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Drill/UIStat_RedText_Drill.UIStat_RedText_Drill',
            "Power is pizza.",
            ON_CARD),
        ('Linoge',
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Legion/UIStat_RedText_Legion.UIStat_RedText_Legion',
            "My name is Legion, for we are many.",
            "rounds ricochet"),
        ('The Lob',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/TheLob/UIStat_RedText_TheLob.UIStat_RedText_TheLob',
            "Everything has to be magical.",
            "slow-moving orb which passes through enemies"),
        ('Long Musket',
            '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/NotAFlamethrower/UIStat_RedText_NotAFlamethrower.UIStat_RedText_NotAFlamethrower',
            "Say “cryptocurrency”!",
            "shoots flames, reload becomes walking flamethrower"),
        ('Loop of 4N631',
            '/Game/Gear/Shields/_Design/_Uniques/LoopOf4N631/Name/UIStat_RedText_LoopOf4N631.UIStat_RedText_LoopOf4N631',
            "Executing phaseshift.",
            "improves action skill cooldown when depleted"),
        ("Lucian's Call",
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/LuciansCall/UIStat_RedText_LuciansCall.UIStat_RedText_LuciansCall',
            "What happened?",
            "crits return 2 rounds and ricochet 2"),
        ('Lyuda',
            '/Game/Gear/Weapons/SniperRifles/Vladof/_Shared/_Design/_Unique/Lyuda/UIStat_RedText_Lyuda.UIStat_RedText_Lyuda',
            "Man killer.",
            "spawns 2 additional projectiles eventually"),
        ('MSRC AUto-Dispensary',
            '/Game/Gear/Shields/_Design/_Uniques/Dispensary/Name/UIStat_RedText_Dispensary.UIStat_RedText_Dispensary',
            "Better living through medical science.",
            "drops a variety of effects"),
        ('Maggie',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Maggie/UIStat_RedText_Maggie.UIStat_RedText_Maggie',
            "Monty's wife don't take no guff.",
            "very good masher"),
        ('Magnificent',
            '/Game/Gear/Weapons/Pistols/Vladof/_Shared/_Design/_Unique/Magnificent/UIStat_RedText_Magnificent.UIStat_RedText_Magnificent',
            "Yedesh na den', khleba beri na nedelyu.",
            ON_CARD),
        ("Malak's Bane",
            '/Game/Gear/Weapons/SniperRifles/Dahl/_Shared/_Design/_Unique/MalaksBane/UIStat_RedText_MalaksBane.UIStat_RedText_MalaksBane',
            "Welcome to the end.",
            "projectiles bounce, alt is shotgun-style blast"),
        ('Manic Pixie Dream Gun',
            '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/FriendZone/UIStat_RedText_FriendZone.UIStat_RedText_FriendZone',
            "It's all in your head.",
            "reloads will sometimes drop the gun, which will run away and must be caught to retrieve the weapon"),
        ('Masterwork Crossbow',
            '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/MasterworkCrossbow/UIStat_RedText_Masterwork.UIStat_RedText_Masterwork',
            "All craftsdwarfship is of the highest quality.",
            "arcing projectiles"),
        ("Mendel's Multivitamin Shield",
            '/Game/Gear/Shields/_Design/_Uniques/BuriedAlive/UIStat_RedText_BuriedAlive.UIStat_RedText_BuriedAlive',
            "Give it to me straight.",
            "increased health and regeneration while charged"),
        ('Messy Breakup',
            '/Game/Gear/Shields/_Design/_Uniques/MessyBreakup/UI/UIStat_RedText_Breakup.UIStat_RedText_Breakup',
            "It's complicated.",
            "drone support, unique voice module"),
        ('Mind-Killer',
            '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/MouthPiece2/UIStat_RedText_Mouthpiece2.UIStat_RedText_Mouthpiece2',
            "I must not fear. Fear is the mind-killer.",
            "instant fire, circle pattern while hip-firing, plus sign while zoomed"),
        ("Miss Moxxi's Vibra-Pulse",
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/VibraPulse/UIStat_RedText_VibraPulse.UIStat_RedText_VibraPulse',
            "Why not turn me on?",
            "energy beam which chains lightning, heals the player"),
        ('Mongol',
            '/Game/Gear/Weapons/HeavyWeapons/Vladof/_Shared/_Design/_Unique/Mongol/UIStat_RedText_Mongol.UIStat_RedText_Mongol',
            "Man is a horde animal.",
            "main rocket spawns smaller rockets"),
        ('Monocle',
            '/Game/Gear/Weapons/SniperRifles/Jakobs/_Shared/_Design/_Unique/Monocle/UIStat_RedText_Monocle.UIStat_RedText_Monocle',
            "One is enough.",
            "extremely high crit damage"),
        ("Moxxi's Bouncing Pair",
            '/Game/Gear/GrenadeMods/_Design/_Unique/MoxiesBosom/Name/UIStat_RedText_MoxiesBosom.UIStat_RedText_MoxiesBosom',
            "Prepare for trouble, and make it double.",
            "2 grenades at once - shock and incendiary - and heals player"),
        ("Moxxi's Embrace",
            '/Game/Gear/Shields/_Design/_Uniques/MoxxisEmbrace/Name/UIStat_RedText_MoxxisEmbrace.UIStat_RedText_MoxxisEmbrace',
            "Want to see a magic trick?",
            "when depeleted, heals all players"),
        ('Mr Caffeine',
            '/Game/Gear/Shields/_Design/_Uniques/MrCaffeine/UIStat_RedText_Caffeine.UIStat_RedText_Caffeine',
            "I don’t want my coffee shaking!",
            "increased reload and fire rate when recharged, reduced while depleted"),
        ('NOG Potion #9',
            '/Game/Gear/GrenadeMods/_Design/_Unique/WizardOfNOG/UI/UIStat_RedText_WizardOfNOG.UIStat_RedText_WizardOfNOG',
            "That's a horse of a different color!",
            "converts NOGs to fight for you for 12 seconds"),
        ('Nagata',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Nagate/UI/UIStat_RedText_Nagate.UIStat_RedText_Nagate',
            "Beltalowda!",
            "ring of projectiles launched in spiral"),
        ('Nemesis',
            '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Nemesis/UIStat_RedText_Nemesis.UIStat_RedText_Nemesis',
            "A righteous infliction of retribution.",
            "chance to deal additional shock damage"),
        ('Night Flyer',
            '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Rakkman/UIStat_RedText_Rakkman.UIStat_RedText_Rakkman',
            "I have one rule.",
            "damages enemies to 1HP, alt fire toggles zoom"),
        ('Night Hawkin',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Demoskag/UIStat_RedText_Demoskag.UIStat_RedText_Demoskag',
            "Stranger than things.",
            "cryo during day, incendiary at night, increased elemental chance with each hit"),
        ('Nimble Jack',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/NimbleJack/UIStat_RedText_Nimble.UIStat_RedText_Nimble',
            "Jack be nimble, Jack be quick, Jack jump up and kill lunatics.",
            "crits don't consume ammo, increased accuracy when airborne"),
        ('Nova Berner',
            '/Game/Gear/Shields/_Design/_Uniques/NovaBurner/Name/UIStat_RedText_NovaBurner.UIStat_RedText_NovaBurner',
            "Feel the Bern.",
            "releases nova when depleted and recharged"),
        ('Null Pointer',
            '/Game/Gear/Weapons/_Shared/NPC_Weapons/Zero/ZeroForPlayer/UIStat_RedText_ZeroForPlayer.UIStat_RedText_ZeroForPlayer',
            ":-D",
            ON_CARD),
        ('Occultist',
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/Troy/UIStat_RedText_Troy.UIStat_RedText_Troy',
            "The only way you can control people is to lie to them.",
            "swirling projectiles which can explode"),
        ('Ogre',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Ogre/UIStat_RedText_Ogre.UIStat_RedText_Ogre',
            "It's all ogre now.",
            "missiles instead of bullets"),
        ('Omniloader',
            '/Game/Gear/Weapons/Pistols/Dahl/_Shared/_Design/_Unique/Omniloader/UIStat_RedText_Omniloader.UIStat_RedText_Omniloader',
            "Omnilock. Omniload. Omnideath.",
            "reloading also reloads other equipped weapons"),
        ('One Pump Chump',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/OnePunch/UIStat_RedText_OnePunch.UIStat_RedText_OnePunch',
            "I swear, that has never happened before.",
            "50% chance not to consume ammo"),
        ("Pa's Rifle",
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/PasRifle/UIStat_RedText_PasRifle.UIStat_RedText_PasRifle',
            "He'd want you to have it.",
            "crits ricochet 3"),
        ('Pain is Power',
            '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/_Unique/KriegAR/UIStat_RedText_HeatDamage.UIStat_RedText_HeatDamage',
            "Nobody kills me but ME!",
            "does not break, deals incendiary damage to player when overheated"),
        ('Peacemonger',
            '/Game/Gear/Weapons/Pistols/Atlas/_Shared/_Design/_Unique/Warmonger/UIStat_RedText_Warmonger.UIStat_RedText_Warmonger',
            "Look around, chief. You've got a right to protect yourself.",
            "fires rocket which eventually splits up"),
        ('Pestilence',
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Contagion/UIStat_RedText_Contagion.UIStat_RedText_Contagion',
            "Go forth conquering, and to conquer.",
            "when broken, player becomes radioactive"),
        ('Phebert',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/UIStat_RedText_Phebert.UIStat_RedText_Phebert',
            "Faster than all estimates.",
            "instant (hitscan) projectiles"),
        ('Polybius',
            '/Game/Gear/Weapons/Shotguns/Tediore/_Shared/_Design/_Unique/Polybius/UIStat_RedText_Polybius.UIStat_RedText_Polybius',
            "21. 11. 33. 14. 24. 42.",
            "fires in 4x4 grid pattern"),
        ('Porcelain Pipe Bomb',
            '/Game/Gear/GrenadeMods/_Design/_Unique/ToiletBombs/UI/UIStat_RedText_ToiletBombs.UIStat_RedText_ToiletBombs',
            "Slinkin', beamin', splooshin'.",
            "spawns several child grenades when main one lands"),
        ('Porta-Pooper 5000',
            '/Game/Gear/Weapons/HeavyWeapons/ChildrenOfTheVault/_Shared/_Design/_Unique/PortaPooper/UIStat_RedText_PortaPooper.UIStat_RedText_PortaPooper',
            "Never washes out.",
            "fires feces"),
        ('Portals and Shite',
            '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/Portal/UIStat_RedText_Portals.UIStat_RedText_Portals',
            "This is beyond science.",
            "unimplemented gun - nothing special about it"),
        ('Predatory Lending',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/PredatoryLending/UIStat_RedText_PredatoryLending.UIStat_RedText_PredatoryLending',
            "Bullets are cheap, but not that cheap.",
            "uses cash as ammunition: $1/shot"),
        ('Projectile Recursion',
            '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Recursion/UIStat_RedText_Recursion.UIStat_RedText_Recursion',
            "See green text for description.",
            "tightly-grouped projectiles which bounce, must charge per shot"),
        ('Psycho Stabber',
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/PsychoStabber/UIStat_RedText_PsychoStabber.UIStat_RedText_PsychoStabber',
            "Fa fa fa fa, fa fa fa fa fa fa...",
            "fires knives in arcs"),
        ('Quadomizer',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Rampager/UIStat_RedText_Rampager.UIStat_RedText_Rampager',
            "Damn near killed ‘em.",
            "fires 4 rockets in horizontal line, cycles between radiation, corrosive, and incendiary"),
        ('Quasar',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Quasar/UI/UIStat_RedText_Quasar.UIStat_RedText_Quasar',
            "E=mc^(OMG)/wtf",
            "pulls enemies in, and chains shock"),
        ('R.Y.N.A.H.',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/RYNO/UIStat_RedText_Rampager.UIStat_RedText_Rampager',
            "You've had this one coming a long time.",
            "2 slow orbs which damage nearby enemies, and fire faster rockets at them upon explosion"),
        ('Re-Charger',
            '/Game/Gear/Shields/_Design/_Uniques/Re-Charger/Name/UIStat_RedText_ReCharger.UIStat_RedText_ReCharger',
            "Once more, with feeling.",
            "no recharge delay when depleted (20sec cooldown)"),
        ('Rebel Yell',
            '/Game/Gear/Weapons/AssaultRifles/Atlas/_Shared/_Design/_Unique/RebellYell/UIStat_RedText_RebelYell.UIStat_RedText_RebelYell',
            "When you charge, yell like Furies.",
            "regular bullets deal normal damage, trackers deal shock"),
        ('Rectifier',
            '/Game/Gear/Shields/_Design/_Uniques/Rectifier/Name/UIStat_RedText_Rectifier.UIStat_RedText_Rectifier',
            "You conduit.",
            "when depleted, electrocutes nearby enemies"),
        ('Red Card',
            '/Game/Gear/Shields/_Design/_Uniques/SlideKick/Name/UIStat_RedText_SlideKick.UIStat_RedText_SlideKick',
            "All studs.",
            "sliding into enemies drains all shields and does bonus damage"),
        ('Red Queen',
            '/Game/Gear/GrenadeMods/_Design/_Unique/RedQueen/UI/UIStat_RedText_RedQueen.UIStat_RedText_RedQueen',
            "OFF WITH THEIR HEADS!",
            "grenade splits in two with laser connecting them"),
        ('Red Suit',
            '/Game/Gear/Shields/_Design/_Uniques/Radiate/Name/UIStat_RedText_Radiate.UIStat_RedText_Radiate',
            "Warning. Containment failure.",
            "constantly deals radiation damage to nearby enemies"),
        ('Redistributor (mission reward)',
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Fork/UIStat_RedText_Fork.UIStat_RedText_Fork',
            "Man's reach exceeds his imagination.",
            ON_CARD),
        ('Redline',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/RedLiner/UIStat_RedText_RedLine.UIStat_RedText_RedLine',
            "I live my life a quarter mag at a time.",
            "increased fire rate with weapon charge-up"),
        ('Revengenader',
            '/Game/Gear/Shields/_Design/_Uniques/Revengenader/Name/UIStat_RedText_Revengenader.UIStat_RedText_Revengenader',
            "Don’t get mad, get explosives.",
            "when depleted, drops a grenade based on equipped mod"),
        ('Ripper',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Ripper/UIStat_RedText_Ripper.UIStat_RedText_Ripper',
            "They say I'm a doctor now.",
            "deals more damage to enemies that have been hit by melee"),
        ('Rogue-Sight',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/SpyRevolver/UIStat_RedText_SpyRevolver.UIStat_RedText_SpyRevolver',
            "Do you see?",
            "homing bullets"),
        ("Roisen's Thorns",
            '/Game/Gear/Weapons/Pistols/Torgue/_Shared/_Design/_Unique/RoisensThorns/UIStat_RedText_RoisensThorns.UIStat_RedText_RoisensThorns',
            "Where there is pleasure, there is pain.",
            "impact mode fires 4 additional incendiary projectiles"),
        ('Rough Rider',
            '/Game/Gear/Shields/_Design/_Uniques/RoughRider/Name/UIStat_RedText_RoughRider.UIStat_RedText_RoughRider',
            "It takes more than that to kill a Bull Moose.",
            "reduces incoming damage, increases maximum health"),
        ("Rowan's Call",
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/RowansCall/UIStat_RedText_RowansCall.UIStat_RedText_RowansCall',
            "Uh-oh!",
            "full auto, crits return 2 to mag and ricochet 2"),
        ('Rubber Cheddar Shredder',
            '/Game/Gear/GrenadeMods/_Design/_Unique/CashMoneyPreorder/Name/UIStat_RedText_CashMoneyPreorder.UIStat_RedText_CashMoneyPreorder',
            "Make it rain.",
            "enemies drop more money when hit"),
        ("Ruby's Wrath",
            '/Game/Gear/Weapons/HeavyWeapons/ATL/_Shared/_Design/_Unique/RubysWrath/UIStat_RedText_RubysWrath.UIStat_RedText_RubysWrath',
            "No one can escape.",
            # also vortex grenade, but the card already mentions that
            "reduced movement speed, 7 missiles per round"),
        ('Sawbar',
            '/Game/Gear/Weapons/AssaultRifles/ChildrenOfTheVault/_Shared/_Design/_Unique/Sawbar/UIStat_RedText_Sawbar.UIStat_RedText_Sawbar',
            "Suppressing fires!",
            "shots eventually split into three projectiles"),
        ('Scorpio',
            '/Game/Gear/Weapons/Pistols/Tediore/Shared/_Design/_Unique/Sabre/UIStat_RedText_Sabre.UIStat_RedText_Sabre',
            "Mobile oppression for pennies a day.",
            "thrown weapon spawns protective shield"),
        ('Scourge',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Swarm/UIStat_RedText_Swarm.UIStat_RedText_Swarm',
            "Or am I?",
            "swirling smaller projectiles around the main one"),
        ('Scream of Terror',
            '/Game/PatchDLC/BloodyHarvest/Gear/Shields/_Design/_Unique/ScreamOfPain/Name/UIStat_RedText_ScreamOfTerror.UIStat_RedText_ScreamOfTerror',
            "Behold the flesh and the power it holds.",
            "enemies hit by nova can be mind-controlled if player is under terror"),
        ('Sellout',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/SuckerPunch/UIStat_RedText_SuckerPunch.UIStat_RedText_SuckerPunch',
            "Hey there, superfan!",
            "no charge time, unique voice module"),
        ('Shooting Star',
            '/Game/Gear/Shields/_Design/_Uniques/ShootingStar/Name/UIStat_RedText_ShootingStar.UIStat_RedText_ShootingStar',
            "Don't look up.",
            "when depleted, melee hits spawn projectile"),
        ('Shrieking Devil',
            '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Shriek/UIStat_RedText_Shriek.UIStat_RedText_Shriek',
            "If the sound is high, sharp, and loud, it's a shriek.",
            "releases elemental nova when fired"),
        ('SkekSil',
            '/Game/Gear/Weapons/Pistols/ChildrenOfTheVault/_Shared/_Design/_Unique/Skeksis/UIStat_RedText_Skeksis.UIStat_RedText_Skeksis',
            "Get back, spithead!",
            "burst fire, launches 1-3 explosive projectiles"),
        ("Sledge's Shotgun / Sledge's Super Shotgun",
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/_Legendary/Sledge/UIStat_RedText_Sledge.UIStat_RedText_Sledge',
            "The legend (still) lives.",
            "2-round burst"),
        ('Sleeping Giant',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/SleepingGiant/UIStat_RedText_SleepingGiant.UIStat_RedText_SleepingGiant',
            "Infinite path carved with unrivaled skill.",
            "reloading has a chance to grant random gun bonuses"),
        ('Smart-Gun XXL',
            '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/SpiderMind/UIStat_RedText_SpiderMind.UIStat_RedText_SpiderMind',
            "Busy getting brain like Krang.",
            "spawns Gigamind spider turret"),
        ('Soleki Protocol',
            '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Soleki/UIStat_RedText_Soleki.UIStat_RedText_Soleki',
            "Cut Katagawa Jr.'s Junior.",
            "on hit, ricochet splits into 5 projectiles in horizontal (X) or vertical (Y) line"),
        ('Stalker',
            '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/SniperRifles/Dahl/_Design/_Unique/Frostbolt/UIStat_RedText_Fbolt.UIStat_RedText_Fbolt',
            "All that remains is an icy husk.",
            "2 ammo per shot, 3 round burst, switch between horiz/vert line"),
        ('Star Helix',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/StarHelix/UIStat_RedText_Helix.UIStat_RedText_Helix',
            "The stars are better off without us.",
            "fires 2 extra projectiles which orbit the main one"),
        ('Starkiller',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Starkiller/UIStat_RedText_Starkiller.UIStat_RedText_Starkiller',
            "Has to have some kind of thermal oscillator.",
            "fires continuous beam"),
        ('Stop-Gap',
            '/Game/Gear/Shields/_Design/_Uniques/StopGap/Name/UIStat_RedText_StopGap.UIStat_RedText_StopGap',
            "The process is called “living”.",
            "player is immune to damage for 5 seconds when depleted"),
        ('Storm',
            '/Game/Gear/Weapons/SniperRifles/Maliwan/Shared/_Design/_Unique/_Legendary/Storm/UIStat_RedText_Storm.UIStat_RedText_Storm',
            "Tut, tut, it looks like rain.",
            "spawns 4 shock orbs around impact"),
        ('Storm Front',
            '/Game/Gear/GrenadeMods/_Design/_Unique/StormFront/UI/UIStat_RedText_StormFront.UIStat_RedText_StormFront',
            "Very, very frightening.",
            "spawns several child grenades that chain shock"),
        ('Super Shredifier',
            '/Game/Gear/Weapons/AssaultRifles/Vladof/_Shared/_Design/_Unique/Shredifier/UIStat_RedText_Shredifier.UIStat_RedText_Shredifier',
            "Speed kills.",
            ON_CARD),
        ('Superball',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/Plumber/UIStat_RedText_Plumber.UIStat_RedText_Plumber',
            "Flower power.",
            "instant fire, shoots small bouncy incendiary balls in downward arc"),
        ('Surge',
            '/Game/Gear/GrenadeMods/_Design/_Unique/Surge/UI/UIStat_RedText_Surge.UIStat_RedText_Surge',
            "Thar she blows!",
            "bounces, after exploding jumps 6 times spawning 3 children each time"),
        ("T.K.'s Wave / T.K's Heatwave / T.K's Shockwave",
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/TheWave/UIStat_RedText_TKWave.UIStat_RedText_TKWave',
            "Ride the wave, dude!",
            "projectiles oscillate up and down and ricochet"),
        ('Ten Gallon',
            '/Game/Gear/Weapons/SMGs/Tediore/_Shared/_Design/_Unique/TenGallon/UIStat_RedText_TenGallon.UIStat_RedText_TenGallon',
            "Let me tell you about my best friend.",
            "on reload, follows the player as a drone"),
        ("The Tidal Wave",
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/_Unique/TheWave/UIStat_RedText_TidalWave.UIStat_RedText_TidalWave',
            "Flee the wave, dude!",
            "projectiles oscillate up and down and ricochet"),
        ('The Transformer',
            '/Game/Gear/Shields/_Design/_Uniques/Transformer/Name/UIStat_RedText_Transformer.UIStat_RedText_Transformer',
            "There's more than your eye can see.",
            "converts 100% of shock damage into shields"),
        ('THE TWO TIME',
            '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/TwoTime/UIStat_RedText_TwoTime.UIStat_RedText_TwoTime',
            "Back-to-back consecutive champion.",
            "hitscan projectiles (no better than Jakobs, though)"),
        ('Thumper',
            '/Game/Gear/Weapons/Shotguns/Torgue/_Shared/_Design/_Unique/Thumper/UIStat_RedText_Thumper.UIStat_RedText_Thumper',
            "The happiest place on Pandora.",
            "bouncy, slow-moving projectile fired in arc"),
        ('Thunderball Fists',
            '/Game/Gear/Weapons/Pistols/Maliwan/_Shared/_Design/_Unique/ThunderballFist/UIStat_RedText_ThunderballFists.UIStat_RedText_ThunderballFists',
            "I can have such a thing?",
            "instant fire, on impact, projectiles form orb which does more damage"),
        ("Tina's Hippity Hopper",
            '/Game/Gear/GrenadeMods/_Design/_Unique/HipHop/Name/UIStat_RedText_HipHop.UIStat_RedText_HipHop',
            "Hare today, bomb tomorrow.",
            "bounces back towards source, spawning extra grenades"),
        ("Traitor's Death",
            '/Game/Gear/Weapons/AssaultRifles/Jakobs/_Shared/_Design/_Unique/TraitorsDeath/UIStat_RedText_TraitorsDeath.UIStat_RedText_TraitorsDeath',
            "Non vo' che più favelle.",
            "25% chance to deal double damage as incendiary"),
        ('Tran-fusion',
            '/Game/Gear/GrenadeMods/_Design/_Unique/TranFusion/UIStat_RedText_TranFusion.UIStat_RedText_TranFusion',
            "Here go, hell come.",
            ON_CARD),
        ('Trevonator',
            '/Game/Gear/Weapons/Shotguns/Maliwan/_Shared/_Design/_Unique/Trev/UIStat_RedText_Trev.UIStat_RedText_Trev',
            "Trev is gunna get you!",
            "no charge time, fires 6 orbs in a burst"),
        ('Try-Bolt',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/UIStat_RedText_TryBolt.UIStat_RedText_TryBolt',
            "Do... or do not-bolt.",
            "burst of 3 rockets"),
        ('Tsunami',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/Tsunami/UIStat_RedText_Tsunami.UIStat_RedText_Tsunami',
            "You can't explain that.",
            "Periodic shock+corrosive, one ricochet"),
        ('Tunguska',
            '/Game/Gear/Weapons/HeavyWeapons/Torgue/_Shared/_Design/_Unique/Tunguska/UIStat_RedText_Tunguska.UIStat_RedText_Tunguska',
            "Crack the skye.",
            "on impact, rocket redirects upwards, then explodes"),
        ('Ultraball',
            '/Game/Gear/GrenadeMods/_Design/_Unique/ToyGrenade/Name/UIStat_RedText_ToyGrenade.UIStat_RedText_ToyGrenade',
            "Do not taunt Happy Fun Ball.",
            "splits into multiple bouncy balls"),
        ('Unforgiven',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/Unforgiven/UIStat_RedText_TheUnforgiven.UIStat_RedText_TheUnforgiven',
            "It's a helluva thing...",
            ON_CARD),
        ('Unpaler',
            '/Game/Gear/Shields/_Design/_Uniques/Unpaler/UIStat_RedText_Unpaler.UIStat_RedText_Unpaler',
            "Kind of tickles.",
            "increased melee damage when depleted"),
        ('Vanquisher',
            '/Game/Gear/Weapons/SMGs/Dahl/_Shared/_Design/_Unique/Vanquisher/UIStat_RedText_Vanquisher.UIStat_RedText_Vanquisher',
            "Slide forward into your cave.",
            "20% increased slide speed, double fire rate while sliding"),
        ('Wagon Wheel',
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/WagonWheel/UIStat_RedText_WagonWheel.UIStat_RedText_WagonWheel',
            "Keep them doggies rollin'.",
            "on hits, additional ricochets spawn"),
        ('Ward',
            '/Game/Gear/Shields/_Design/_Uniques/Ward/Name/UIStat_RedText_Ward.UIStat_RedText_Ward',
            "Free me master, see me shiver.",
            ON_CARD),
        ('Warlord',
            '/Game/Gear/Weapons/AssaultRifles/Dahl/_Shared/_Design/_Unique/Warlord/UIStat_RedText_Warlord.UIStat_RedText_Warlord',
            "My gun sings for your blood.",
            "30% chance to not consume ammo"),
        ('Westergun',
            '/Game/Gear/Weapons/SMGs/Maliwan/_Shared/_Design/_Unique/westergun/UIStat_RedText_westergun.UIStat_RedText_westergun',
            "I believe ya, but my tommy gun don't.",
            "no charge time, increased splash radius"),
        ('Whiskey Tango Foxtrot',
            '/Game/Gear/Shields/_Design/_Uniques/WhiskeyTangoFoxtrot/Name/UIStat_RedText_WTF.UIStat_RedText_WTF',
            "Situation normal.",
            "25% chance to drop an IED"),
        ('Whispering Ice',
            '/Game/Gear/GrenadeMods/_Design/_Unique/ObviousTrap/UI/UIStat_RedText_ObviousTrap.UIStat_RedText_ObviousTrap',
            "You’ve raised my frosty dander!",
            "lays down several proximity mines"),
        ('Widowmaker',
            '/Game/Gear/GrenadeMods/_Design/_Unique/WidowMaker/Name/UIStat_RedText_WidowMaker.UIStat_RedText_WidowMaker',
            "À la vie, à la mort.",
            "creates landmine which spawns homing rockets"),
        ('Woodblocker',
            '/Game/Gear/Weapons/SniperRifles/Hyperion/_Shared/_Design/_Unique/Woodblocks/UIStat_RedText_Woodblocks.UIStat_RedText_Woodblocks',
            "You don't get into woodblocks unless you are ready to f***.",
            "four-round burst"),

        # New Mayhem 4 / Maliwan Takedown gear
        ('Good Juju',
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Juju/UIStat_RedText_Juju.UIStat_RedText_Juju',
            "Kinda, sorta wants to end all existence.",
            "refills magazine on kill"),
        ("Tankman's Shield",
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Tankman/UIStat_RedText_Tankman.UIStat_RedText_Tankman',
            "You ever seen this dude tank anything ever?",
            ON_CARD),
        ('S3RV-80S-EXECUTE',
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Execute/UIStat_RedText_Execute.UIStat_RedText_Execute',
            "Touch of death requires mastery of combo strikes.",
            "enemies hit with empty reload take more damage for 12 sec, effect can stack"),
        ("Vosk's Deathgrip",
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/DeathGrip/UIStat_RedText_Deathgrip.UIStat_RedText_Deathgrip',
            "A good death is its own reward.",
            "launches a grid of damaging beams which remain stationary, alt fires singularity"),
        ("Juliet's Dazzle",
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/Juliet/UIStat_RedText_Juliet.UIStat_RedText_Juliet',
            "Lights up the world.",
            ON_CARD),
        ("Zheitsev's Eruption",
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/ZheitsevEruption/UIStat_RedText_Zheitsev.UIStat_RedText_Zheitsev',
            "Pain and Misery erupt in the Void.",
            "launches barrage of homing projectiles when overheated"),
        ("Crader's EM-P5",
            '/Game/PatchDLC/Raid1/Re-Engagement/Weapons/CraderMP5/UIStat_RedText_CraderMP5.UIStat_RedText_CraderMP5',
            "Dust off the beta EMP5.",
            "increased movement speed, increased accuracy in air"),
        ("Kyb's Worth",
            '/Game/PatchDLC/Raid1/Gear/Weapons/KybsWorth/UIStat_RedText_KybsWorth.UIStat_RedText_KybsWorth',
            "Stand in the f****** circle.",
            "shoots two oscillating projectiles side by side"),
        ('Redistributor (legendary version)',
            '/Game/PatchDLC/Raid1/Gear/Weapons/Fork2/UIStat_RedText_Fork2.UIStat_RedText_Fork2',
            "Man's reach exceeds his imagination.",
            ON_CARD),
        ('Moonfire',
            '/Game/PatchDLC/Raid1/Gear/Weapons/HandCannon/UIStat_RedText_HandCannon.UIStat_RedText_HandCannon',
            "Meet your destiny.",
            "every 3rd shot is more powerful"),
        ("Tiggs' Boom",
            '/Game/PatchDLC/Raid1/Gear/Weapons/TiggsBoom/UIStat_RedText_TiggsBoom.UIStat_RedText_TiggsBoom',
            "A gaping hole in the sky.",
            "shots pierce enemies and makes meteors fall from sky"),
        ('P2P Networker',
            '/Game/PatchDLC/Raid1/Gear/Weapons/Link/UIStat_RedText_Link.UIStat_RedText_Link',
            "You wouldn't download a car.",
            "hits chain to nearby enemies, broken second element"),
        ('Frozen Snowshoe',
            '/Game/PatchDLC/Raid1/Gear/Shields/_HybridLegendary/SlideKickHybrid/SlideKick_FrozenHeart/UIStat_RedText_SlideKick_FrozenHeart.UIStat_RedText_SlideKick_FrozenHeart',
            "Give em' the cold toelder.",
            ON_CARD),
        ('Red Card Re-Charger',
            '/Game/PatchDLC/Raid1/Gear/Shields/_HybridLegendary/SlideKickHybrid/SlideKick_Recharger/UIStat_RedText_SlideKickRecharger.UIStat_RedText_SlideKickRecharger',
            "One more kick, with feeling.",
            "{} - combines Red Card and Re-Charger effects".format(ON_CARD)),
        ('Re-Charger Berner',
            '/Game/PatchDLC/Raid1/Gear/Shields/_HybridLegendary/SlideKickHybrid/ReCharger_Berner/UIStat_RedText_ReCharger_Berner.UIStat_RedText_ReCharger_Berner',
            "Feelin' the Bern.",
            "{} - combines Re-Charger and Nova Berner effects".format(ON_CARD)),
        ('Version 0.m',
            '/Game/PatchDLC/Raid1/Gear/Shields/VersionOmNom/Name/UIStat_RedText_VersionOmNom.UIStat_RedText_VersionOmNom',
            "Stand and Clap.",
            "amp effect, on depletion releases AOE and creates a temporary amp damage area"),

        # DLC1 (Dandelion) Gear - Moxxi's Heist of the Handsome Jackpot
        ('AutoAimè',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/AutoAime/UIStat_RedText_AutoAime.UIStat_RedText_AutoAime',
            "OGC HOOKED",
            "bullets home to center of target, must be reasonably close to activate"),
        ('Boomer',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Boomer/UIStat_RedText_Boomer.UIStat_RedText_Boomer',
            'Some like it hot.',
            'bullets explode with incendiary effect'),
        ('Cheap Tips',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/CheapTips/UIStat_RedText_CheapTips.UIStat_RedText_CheapTips',
            "I'll get home early from work.",
            ON_CARD),
        ('Craps',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Craps/UIStat_RedText_Craps.UIStat_RedText_Craps',
            'Oh me.',
            'has a chance to fire 5 bullets instead of just 1'),
        ('Creamer',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Creamer/UIStat_RedText_Creamer.UIStat_RedText_Creamer',
            'non-dairy',
            'rocket explodes mid-flight and splits into two'),
        ("Digby's Smooth Tube",
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Digby/UIStat_RedText_Digby.UIStat_RedText_Digby',
            'Hot or cool, man, hyperjazz is hyperjazz.',
            'plays a saxophone sound with each shot'),
        ("Ember's Purge",
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/EmbersPurge/UIStat_RedText_EmbersPurge.UIStat_RedText_EmbersPurge',
            "She's the only one who knows what it is to burn.",
            'hits have a chance to spawn an incendiary pool'),
        ('Heart Breaker',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/HeartBreaker/UIStat_RedText_HeartBreaker.UIStat_RedText_HeartBreaker',
            "I don't want to set the world on fire...",
            'restores health based on damage dealt, fires in heart-shaped pattern'),
        ('ION CANNON',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/IonCannon/UIStat_RedText_IonCannon.UIStat_RedText_IonCannon',
            'Fun Detected: Obliterate.',
            'hold to charge'),
        ('ION LASER',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/IonLaser/UIStat_RedText_IonLaser.UIStat_RedText_IonLaser',
            'Particles unite!',
            'beam weapon, shoots additional projectiles at end based on trigger hold time'),
        ('Just Kaus',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/JustCaustic/UIStat_RedText_JustCaustic.UIStat_RedText_JustCaustic',
            'I like to keep my lists short.',
            ON_CARD),
        ('Lucky 7',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Lucky7/UIStat_RedText_Lucky7.UIStat_RedText_Lucky7',
            'O Fortuna.',
            'random effects rolled on reload, active for next mag'),
        ('Melt Facer',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/MeltFacer/UIStat_RedText_MeltFacer.UIStat_RedText_MeltFacer',
            'Get melted.',
            'cryo damage/freeze chance on critical hits'),
        ('Nukem',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Nukem/UIStat_RedText_Nukem.UIStat_RedText_Nukem',
            'Name dropper.',
            'mortar projectiles with a huge blast radius'),
        ('Robo-Melter',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/RoboMasher/UIStat_RedText_RoboMasher.UIStat_RedText_RoboMasher',
            'Reduce. Reuse. Recycle. Reload.',
            ON_CARD),
        ('Scoville',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Scoville/UIStat_RedText_Scoville.UIStat_RedText_Scoville',
            'Put a little pepper on the end of it.',
            'lobbed incendiary balls which explode'),
        ('Slow Hand',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/SlowHand/UIStat_RedText_SlowHand.UIStat_RedText_SlowHand',
            'Take your time, Sugar...',
            'slow-moving projectile, high elemental damage and splash, heals a percentage of damage dealt'),
        ('Brad Luck',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Trash/UIStat_RedText_Trash.UIStat_RedText_Trash',
            'Brad to the bone.',
            'fire rate varies over time'),
        ('La Varlope',
            '/Game/PatchDLC/Dandelion/Gear/Weapon/_Unique/Varlope/UIStat_RedText_Varlope.UIStat_RedText_Varlope',
            'Just take a little off the top.',
            'full auto, speedy rapid-fire missiles which fly in arc'),
        ('All-in',
            '/Game/PatchDLC/Dandelion/Gear/Shield/Clover/Name/UIStat_RedText_Clover.UIStat_RedText_Clover',
            'With marshmallow bits.',
            ON_CARD),
        ('Double Downer',
            '/Game/PatchDLC/Dandelion/Gear/Shield/DoubleDowner/Name/UIStat_RedText_DoubleDowner.UIStat_RedText_DoubleDowner',
            "We're going down, down, down to Mephisto's Cafe.",
            ON_CARD),
        ("Ember's Blaze",
            '/Game/PatchDLC/Dandelion/Gear/Shield/Ember/Name/UIStat_RedText_Ember.UIStat_RedText_Ember',
            'In order to rise from its own ashes, a phoenix first must burn.',
            ON_CARD),
        ('Rico',
            '/Game/PatchDLC/Dandelion/Gear/Shield/Rico/Name/UIStat_RedText_Rico.UIStat_RedText_Rico',
            'You wanna live forever?',
            ON_CARD),
        ('Acid Burn',
            '/Game/PatchDLC/Dandelion/Gear/Grenade/AcidBurn/UI/UIStat_RedText_AcidBurn.UIStat_RedText_AcidBurn',
            'Hack the Planet!',
            ON_CARD),
        ('Slider',
            '/Game/PatchDLC/Dandelion/Gear/Grenade/Slider/Name/UIStat_RedText_Slider.UIStat_RedText_Slider',
            'Same planet, different dimension.',
            'travels in a perfectly straight line, small radius'),

        # New Broken Hearts event gear
        ('Terminal Polyaimorous',
            '/Game/PatchDLC/EventVDay/Gear/Weapon/_Unique/PolyAim/UIStat_RedText_PolyAim.UIStat_RedText_PolyAim',
            "Spread the love.",
            "beam chains to nearby enemies"),
        ('Wedding Invitation',
            '/Game/PatchDLC/EventVDay/Gear/Weapon/_Unique/WeddingInvitation/UIStat_RedText_WeddingInvite.UIStat_RedText_WeddingInvite',
            "Will you be the rest of my life?",
            "full auto, return ammo on crits, splash damage, cryo ricochet"),
        # This was added in Broken Hearts but it has no special abilities or red text
        #('Superstreamer',
        #    '',
        #    '',
        #    ''),

        # DLC2 (Hibiscus) Gear - Guns, Love, and Tentacles
        ("Clairvoyance",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Clairvoyance/UIStat_RedText_Clairvoyance',
            "A broken smile beneath her whispered wings.",
            "crits leave sticky bomb that fires a shot on detonation"),
        ("Seeryul Killur",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Homicidal/UIStat_RedText_Homicidal',
            "Look at that unsubtle blood-red coloring...",
            "kills reduce heat shot cost, increase damage and fire rate, max 3 stacks"),
        ("Mutant",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Mutant/UIStat_RedText_Mutant',
            "Super unnatural.",
            "continuous laser beam"),
        ("Soulrender",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Soulrender/UIStat_RedText_Soulrender',
            "Picture a soul. Now REND that thing!",
            "shoots homing skulls at targets"),
        ("Stauros' Burn",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SparkyBoom/UIStat_RedText_SparkyBoom',
            "A long sigh was heard...",
            ON_CARD),
        # This is basically exactly like the Duc, minus a few visual effects
        ("Bite Size",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/BiteSize/UIStat_RedText_BiteSize',
            "And yet so filling!",
            "Torgue-like sticky explosion after a few seconds, initial burst does NOT do splash"),
        ("Frozen Devil",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/FrozenDevil/UIStat_RedText_FrozenDevil',
            "Not sorry, not sorry, not sorry.",
            "continuous laser and ice spike"),
        ("Hydrafrost",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Hydrafrost/UIStat_RedText_Hydrafrost',
            "Tell your heads to chill.",
            "after kill, second shot deals 200% shock or incendiary damage for 6 secs"),
        ("Kaleidoscope",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Kaleidoscope/UIStat_RedText_Kaleidoscope',
            "I can fly twice as high, take a look...",
            "every 3rd shot will be an elemental amp shot, ADS changes element"),
        ("Little Yeeti",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LittleYeeti/UIStat_RedText_LittleYeeti',
            "Yeet 'em if you got 'em!",
            "multiple projectiles, chance to knockback enemy"),
        ("Love Drill (legendary version)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/UIStat_RedText_LoveDrill_L',
            "...till death us depart.",
            "20% chance to deal double damage as shock"),
        ("Love Drill (mission version)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/LoveDrill/UIStat_RedText_LoveDrill',
            "To have and to hold...",
            "20% chance to deal double damage as shock"),
        ("Short Stick",
            '/Game/PatchDLC/Steam/Gear/Weapons/SteamGun/UIStat_RedText_ShortStick',
            "A small price to pay.",
            "chance to fire 2 additional spiralling shots and deal incendiary damage"),
        ("Seventh Sense (prefixed mission)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/UIStat_RedText_TheSeventhSense',
            "Do you see?",
            "mission item, reveals ghosts during ADS"),
        ("Seventh Sense (prefixed legendary)",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheSeventhSense/UIStat_RedText_TheSeventhSense_Legendary',
            "Something so close, and yet... so distant.",
            "on hit, creates additional wandering projectiles; reloading sends them back to enemy"),
        # I don't think these are actually used anywhere, except possibly as enemy-use
        #("Seventh Sense (non-prefixed, both purple and legendary)",
        #    '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SeventhSense/Parts/UIStat_RedText_SeventhSense',
        #    "Do you see?",
        #    "unknown - non-prefixed"),
        ("Anarchy",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Anarchy/UIStat_RedText_Anarchy',
            "The stacks... THE STACKS!",
            "every auto reload or kill grants 30% damage and reduces accuracy, 10 stacks max"),
        ("Firecracker",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Firecracker/UIStat_RedText_Firecracker',
            "Ooooh. Aaaah.",
            "shoots cluster of 12 fireworks which spiral randomly and explode into hearts"),
        ("Insider",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Insider/UIStat_RedText_Insider',
            "You can run, but you can't hide",
            "instant fire, shots penetrate enemies and deal splash damage"),
        ("Flama Diddle",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Omen/UIStat_RedText_Omen',
            "VIII. Never turn your back on a Monster!",
            "reload shoots twice before exploding on impact, bullets ricochet once"),
        ("Sacrificial Lamb",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SacrificalLamb/UIStat_RedText_SacrificialLamb',
            "Kali Ma Shakti de!",
            ON_CARD),
        ("Shocker",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Shocker/UIStat_RedText_Shocker',
            "Surprise!",
            "shock orb splits into 3 orbs horizontally"),
        ("The Cure",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheCure/UIStat_RedText_TheCure',
            "Vaccinations save lives. Sorry, no joke here! Just facts.",
            "restores health with each hit"),
        ("Nothingness",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/TheNothing/UIStat_RedText_TheNothing',
            "A hole would be something.",
            "generates additional explosions around the main shot, similar to Flakker"),
        ("Oldridian",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Oldridian/UIStat_RedText_Oldridian',
            "They bound the ones they knew of. There were more.",
            "switches element on reload, shield reduces elemental damage by 20%"),
        ("SF Force",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/SFForce/UIStat_RedText_SFForce',
            "Flavor-blast them all.",
            ON_CARD),
        ("Initiative",
            '/Game/PatchDLC/Hibiscus/Gear/Shields/_Unique/Initiative/UIStat_RedText_Initiative',
            "You're only given a little spark...",
            ON_CARD),
        ("Old God",
            '/Game/PatchDLC/Hibiscus/Gear/Shields/_Unique/OldGod/UIStat_RedText_OldGod',
            "The end comes from within.",
            ON_CARD),
        ("Torch",
            '/Game/PatchDLC/Hibiscus/Gear/Shields/_Unique/Torch/UIStat_RedText_Torch',
            "Inflammable means flammable!?",
            ON_CARD),
        ("Void Rift",
            '/Game/PatchDLC/Hibiscus/Gear/Shields/_Unique/VoidRift/UIStat_RedText_VoidRift',
            "Be careful what comes out.",
            ON_CARD),
        ("Cocky Bastard",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/CockyBastard/UIStat_RedText_CockyBastard',
            "Great, kid.",
            "crits deal shock damage equal to crit damage"),
        ("Skullmasher",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/Skullmasher/UIStat_RedText_Skullmasher',
            "Makes your brain hurt.",
            "x5 projectiles per shot, extremely fast fire rate"),
        ("Unseen Threat",
            '/Game/PatchDLC/Hibiscus/Gear/Weapon/_Unique/UnseenThreat/UIStat_RedText_UnseenThreat',
            "Taste their fear.",
            "crits ricochet 3 homing projectiles"),

        # Mayhem 2.0 Gear
        ("Backburner",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Backburner/UIStat_RedText_BackBurner',
            "We'll get to it eventually.",
            "shoots orb which spawns singularity with child MIRV orbs"),
        ("D.N.A.",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/DNA/UIStat_RedText_DNA',
            "Death cannot be contained.",
            "fires paired swirling random-element projectiles connected by beam"),
        ("Multi-tap",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/DoubleTap/UIStat_RedText_DoubleTap',
            "Double the fun",
            ON_CARD),
        ("Kaoson",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Kaoson/UIStat_RedText_Kaoson',
            "Small but packs a punch.",
            "fires Torgue-like sticky shots"),
        ("The Monarch",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Monarch/UIStat_RedText_Monarch',
            "The deadly sting of the monarch!",
            "shotgun AR with bipod"),
        ("Plaguebearer",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Plague/UIStat_RedText_Plague',
            "Glad you could make it.",
            "main orb creates singularity on hit, and spawns additional homing orbs enroute"),
        ("Reflux",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/Reflux/UIStat_RedText_Reflux',
            "That's gotta burn.",
            "creates corrosive beam between enemies, shield returns bullets to mag when damaged"),
        ("Sand Hawk",
            '/Game/PatchDLC/Mayhem2/Gear/Weapon/_Shared/_Unique/SandHawk/UIStat_RedText_SandHawk',
            "Wedge a pig.",
            "fires nine bullets in a wing pattern which flap as they travel"),

        # Revenge of the Cartels Gear
        ("Grease Trap",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/GreaseTrap/UIStat_RedText_GreaseTrap',
            "“EXTREMELY FLAMMABLE!”",
            "Fire Starter mode shoots incendiary fireballs, Hot Grease shoots arcing projectiles with kinetic damage"),
        ("Iceburger",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/IceBurger/UIStat_RedText_IceBurger',
            "90% of the flavor is under the bun.",
            "Continuous laser while launching MIRV-like cryo burgers"),
        # no red text on this one!
        #("Ice Pick",
        #    '',
        #    "",
        #    "seems to just be an ordinary Maliwan pistol; decent splash"),
        ("Needle Gun",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/NeedleGun/UIStat_RedText_NeedleGun',
            "Not your average needle.",
            ON_CARD),
        ("O.P.Q. System",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/OPQ/UIStat_RedText_OPQ',
            "B.Y.O.B.B.",
            "spawns a drone copy of itself"),
        ("NoPewPew",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/PewPew/UIStat_RedText_PewPew',
            "Extra, extra spicy.",
            "Fire rate increases as trigger is held, generates lava pool at killed enemies"),
        ("Pricker",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/Pricker/UIStat_RedText_Pricker',
            "What have they to say now?",
            "slow homing needles which stick on contact, exploding once four have landed"),
        ("Yellowcake",
            '/Game/PatchDLC/Event2/Gear/Weapon/_Unique/YellowCake/UIStat_RedText_YellowCake',
            "I'm really more of a pie person.",
            "multi-MIRV projectiles, extremely powerful"),
        ("Firewall",
            '/Game/PatchDLC/Event2/Gear/Shield/_Unique/Firewall/UIStat_RedText_Firewall',
            "Initiate countermeasures.",
            ON_CARD),
        ("M.E.A.T. Shield",
            '/Game/PatchDLC/Event2/Gear/Shield/_Unique/MEAT/UIStat_RedText_MEAT',
            "Must. Eat. All. Tendies.",
            "Increases health, meat kebab boosters provide health regen"),
        ("Wattson",
            '/Game/PatchDLC/Event2/Gear/Shield/_Unique/Wattson/UIStat_RedText_Wattson',
            "It's all quite arbitrary, my dear boy.",
            "spawns grenades based on element of incoming projectile"),
        ("Fish Slap",
            '/Game/PatchDLC/Event2/Gear/GrenadeMods/FishSlap/UIStat_RedText_FishSlap',
            "Say hello to my little fish!",
            "30% of damage dealt is used to refill shields"),

        # Guardian Takedown gear
        ("Globetrottr",
            '/Game/PatchDLC/Takedown2/Gear/Weapons/Globetrotter/UIStat_RedText_Globetrotter',
            "Um allan heim, styttur hrynja fyrir mig.",
            "3 discs that bounce several times before rising and exploding"),
        ("Smog",
            '/Game/PatchDLC/Takedown2/Gear/Weapons/Smog/UIStat_RedText_Smog',
            "Haze amaze.",
            "increased damage when weapon shield is active and at full capacity"),
        ("Web Slinger",
            '/Game/PatchDLC/Takedown2/Gear/Weapons/WebSlinger/UIStat_RedText_WebSlinger',
            "Let's do this one last time.",
            "crits can cause novas that deal 500% status effect damage"),
        ("Asclepius",
            '/Game/PatchDLC/Takedown2/Gear/Shields/Aesclepius/UIStat_RedText_Aesclepius',
            "Always carry a small snake.",
            "50% resistance to elemental status effects while depleted"),
        ("Stinger",
            '/Game/PatchDLC/Takedown2/Gear/Shields/Stinger/UIStat_RedText_Stinger',
            "They don't let you use that no more.",
            "melee damage increased by 50% when full"),
        ("Lightspeed",
            '/Game/PatchDLC/Takedown2/Gear/GrenadeMods/Lightspeed/UIStat_RedText_Lightspeed',
            "Gimme a parsec.",
            "extremely fast longbow which explodes into ricocheting projectiles"),

        # DLC3 (Bounty of Blood)
        ("The Beast (rad)",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/UIStat_RedText_BioBetsy_Rad',
            "She grew big, and she grew mean.",
            "no special effects"),
        ("The Beast (shock)",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BioBetsy/UIStat_RedText_BioBetsy_Shock',
            "She grew big, and she grew mean.",
            "no special effects"),
        ("Contained Blast",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/ContainedExplosion/UIStat_RedText_Contained',
            "Put a lid on it.",
            "projectiles explode on impact, semi-auto"),
        ("Icebreaker",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/CoolBeans/UIStat_RedText_CoolBeans',
            "Dread fifty below more than fifty above.",
            "cryothrower"),
        ("Dowsing Rod",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/DowsingRod/UIStat_RedText_Dowsing',
            "It's down there somewhere, lemme take another look.",
            "full auto, high fire rate"),
        ("The Chalice",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/McSmugger/UIStat_RedText_McSmugger',
            "You'll have to do much better than that, loves.",
            #"crit kills cause the next mag to deal 100% more damage",
            ON_CARD),
        ("Stonethrower",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/StoneThrow/UIStat_RedText_StoneThrow',
            "Everywhere is nearby.",
            "semi-auto"),
        ("Plumage",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Plumage/UIStat_RedText_Plumage',
            "Quit peacocking around.",
            "marked enemies drop tracking grenade on kill"),
        ("Satisfaction",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Satisfaction/UIStat_RedText_Satisfaction',
            "Thirty minutes or less.",
            "four sticky orbs"),
        ("Bubble Blaster",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/BubbleBlaster/UIStat_RedText_BubbleBlaster',
            "Every day is a holiday.",
            "rounds float upward and explode after a delay"),
        ("Beacon",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Decoupler/UIStat_RedText_Decoupler',
            "This little light of mine...",
            "reload triggers nova of current element"),
        ("Gargoyle",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Gargoyle/UIStat_RedText_Gargoyle',
            "Defender of the night.",
            "rapidly shoots projectiles and occasional globs of corrosive"),
        ("Light Show",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Lasocannon/UIStat_RedText_Lasocannon',
            "Give me some light, away!",
            "shots form rotating circular pattern"),
        ("Miscreant",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Miscreant/UIStat_RedText_Miscreant',
            "Why waste time shoot lot gun when few gun do trick?",
            "full-auto rockets"),
        ("Peashooter",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Peashooter/UIStat_RedText_Peashooter',
            "If you think there's no risk, take a good dose.",
            "crits generate MIRV-like ricochets"),
        ("The Blanc",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/PrivateInvestigator/UIStat_RedText_PrivateInvestigator',
            "This machine unerringly arrives at the truth.",
            "damaging enemies grants +35% weapon damage when switching, stacks x10"),
        ("Quickdraw",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/QuickDraw/UIStat_RedText_QuickDraw',
            "Oo, that smarts!",
            #"instantly reloads and buffs damage on weapon swap",
            ON_CARD),
        ("Bloom",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Rose/UIStat_RedText_Rose',
            "A thorn by any other name would probably still hurt.",
            "hold trigger to charge burst-fire shots"),
        # Just a weird green-rarity thing
        #("Marshal",
        #    '(no red text found, maybe not on barrel?)',
        #    "(no red text found, maybe not on barrel?)",
        #    "unknown"),
        ("Unkempt Harold",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/UnkemptHarold/UIStat_RedText_UnkemptHarold',
            "I wasn't counting either.",
            "narrow spread of explosive projectiles"),
        ("Chandelier",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Antler/UIStat_RedText_Antler',
            "It will not last the night.",
            "shoots disk projectiles"),
        ("Brightside",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Brightside/UIStat_RedText_Brightside',
            "It's killing me.",
            "reload becomes drone which splits into four elemental drones"),
        ("Dakota",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Dakota/UIStat_RedText_Dakota',
            "The longarm of the law.",
            "randomly fires shock, incendiary, or non-elemental pellets"),
        ("The Shoddy",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Fakobs/UIStat_RedText_Fakobs',
            "100% Genuine Fakobs.",
            "projectiles fall very close to player"),
        ("Frequency",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Frequency/UIStat_RedText_Frequency',
            "Hertz so good.",
            "kills increase burst count for a short time"),
        ("Spade",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Shoveler/UIStat_RedText_Shoveler',
            "Lucille, God gave me a gift.",
            "gyrojets penetrate, leaving sticky bombs on enemies"),
        ("Robin's Call",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/SpeakEasy/UIStat_RedText_SpeakEasy',
            "Are you not he?",
            "crits ricochet 1 bullet and return 1 to mag"),
        ("Splinter",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Splinter/UIStat_RedText_Splinter',
            "The first one is always the hardest.",
            # TODO: Should try to verify this.
            "crits might ricochet 3x instead of just 1, unsure"),
        ("Proprietary License",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Copybeast/UIStat_RedText_Copybeast',
            "A little from Column A, a little from Column B.",
            "crits ricochet, ads increases fire rate"),
        ("Mother Too",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Earthbound/UIStat_RedText_Earthbound',
            "Thank you for taking the time to read this flavor text. This flavor text loves you.",
            "continuous laser, reload becomes laser drone"),
        ("Flipper",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Flipper/UIStat_RedText_Flipper',
            "Put one foot in front of the other.",
            "hold trigger for increased projectile count"),
        ("Complex Root",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/ImaginaryNumber/UIStat_RedText_ImaginaryNumber',
            "Your brain is a creative computer.",
            "shoots sporadic zig-zagging projectiles"),
        ("Narp",
            '/Game/PatchDLC/Geranium/Gear/Weapon/_Unique/Narp/UIStat_RedText_Narp',
            "What happened to your peace lily?",
            "when reloading, remaining rounds grant bonuses to next mag"),
        ("Core Buster",
            '/Game/PatchDLC/Geranium/Gear/Grenade/CoreBurst/UIStat_RedText_CoreBurst',
            "Work it.",
            "MIRV effect on explosion"),
        ("Doc Hina's Miracle Bomb",
            '/Game/PatchDLC/Geranium/Gear/Grenade/SkagOil/UIStat_RedText_SkagOil',
            "Give me fever.",
            "generates incendiary pools while bouncing"),
        ]:

    # Eh, let's omit shields by default; I am 99% sure that all of them already
    # explicitly say what they do.  (though Version 0.m could be an exception)
    if '/Shields/' not in obj_name and '/Shield/' not in obj_name:

        # Stupid little special-case here; wtf is Echo seemingly the one different gun?
        if gear_name == 'Echo':
            attr_name = 'FormatText'
        else:
            attr_name = 'Text'

        # Another *weird* special-case.  The red text for Short Stick doesn't actually
        # get updated if we do it at PATCH time.
        if 'ShortStick' in obj_name:
            hf_type = Mod.LEVEL
            hf_package = 'MatchAll'
        else:
            hf_type = Mod.PATCH
            hf_package = ''

        # Now generate the hotfix
        mod.comment(gear_name)
        mod.reg_hotfix(hf_type, hf_package,
                obj_name,
                attr_name,
                '[Flavor]{}[/Flavor] ({})'.format(redtext, elementize(explanation)))
        mod.newline()

mod.close()
