Attribute_Damage_Ammo=[
    [
        [
            'ValueResolver'
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale'            
        ],
        [
            "SimpleMathValueResolver'/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale:ValueResolver_SimpleMathValueResolver'"
        ]
    ],
    [
        [
            'ContextResolver'
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale'            
        ],
        [
            'None'
        ]
    ],
    [
        [
            'ValueA'
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale:ValueResolver_SimpleMathValueResolver'            
        ],
        [
            '(BaseValueAttribute=/Game/GameData/Weapons/Att_Weapon_CurrentLoadedAmmo.Att_Weapon_CurrentLoadedAmmo)'
        ]
    ],
    [
        [
            'ValueB'
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale:ValueResolver_SimpleMathValueResolver'            
        ],
        [
            '(BaseValueAttribute=/Game/GameData/Weapons/Att_Weapon_MaxLoadedAmmo.Att_Weapon_MaxLoadedAmmo)'
        ]
    ],
    [
        [
            'Operator'
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale:ValueResolver_SimpleMathValueResolver'            
        ],
        [
            'ESimpleMathValueResolverOperatorType::Divide'
        ]
    ]
]

Fade_Away=[
    [
        [
            'bUseDefaultCriticalHitMultiplier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/Balance/Weapon_Mod_Beastmaster_Cloak_Base.Weapon_Mod_Beastmaster_Cloak_Base'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'AdditionalCriticalMultiplier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/Balance/Weapon_Mod_Beastmaster_Cloak_Base.Weapon_Mod_Beastmaster_Cloak_Base'            
        ],
        [
            """
            (
                BaseValueConstant=0.0,
                DataTableValue=(DataTable=None),
                BaseValueScale=0.0
            )
            """
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/ActionSkill/ActionSkill_Cloak.Default__ActionSkill_Cloak_C'            
        ],
        [
            'You [actionskill]Cloak[/actionskill] and turn invisible, granting you 3 shots that automatically turn into [skillbold]Critical Hits[/skillbold]. <br>While [actionskill]Cloaked[/actionskill] you gain [skillbold]Movement Speed[/skillbold] and [skillbold]Health Regeneration[/skillbold].'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/ActionSkill/ActionSkill_Cloak.Default__ActionSkill_Cloak_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_2'            
        ],
        [
            '[skillbold]Cloaked Health Regeneration:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'SignStyle'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/ActionSkill/ActionSkill_Cloak.Default__ActionSkill_Cloak_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_2'            
        ],
        [
            'Positive'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/ActionSkill/ActionSkill_Cloak.Default__ActionSkill_Cloak_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            ''
        ]
    ],
    [
        [
            'AttributeEffects.AttributeEffects[1]'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/StatusEffects/Status_Beastmaster_FadeAway'            
        ],
        [
            """
            (
                AttributeData=/Game/GameData/Attributes/Health/Att_HealthPassivePercentRegenerationRate.Att_HealthPassivePercentRegenerationRate,
                ModifierType=PreAdd,
                BaseModifierValue=(DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=Ultimate_Spiderant,ValueName=Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453))
            )
            """
        ]
    ]
]

Fade_Away_A1=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod1'            
        ],
        [
            'Your [red]Pet[/red] taunts all the enemies in a huge radius at the end of [actionskill]Fade Away[/actionskill], granting it [skillbold]Damage Reduction[/skillbold].'
        ]
    ]
]

Fade_Away_A2=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod2'            
        ],
        [
            'You also gain [skillbold]Additive Critical Hit Damage[/skillbold].'
        ]
    ],
    [
        [
            'bUseDefaultCriticalHitMultiplier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/Balance/Weapon_Mod_Beastmaster_Cloak_Mod2.Weapon_Mod_Beastmaster_Cloak_Mod2'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod2.Augment_Beastmaster_Cloak_Mod2:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            '[skillbold]Critical Hit Damage:[/skillbold] $VALUE$'
        ]
    ],
    [   #Critical Hit Bonus
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Cloak_AutoCrits'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            1.0
        ]
    ]
]

Fade_Away_A3=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod3'            
        ],
        [
            '[actionskill]Fade Away[/actionskill] no longer has a shot limit, at the cost of [skillbold]Duration[/skillbold].'
        ]
    ],
    [
        [
            'bUseDefaultCriticalHitMultiplier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/Balance/Weapon_Mod_Beastmaster_Cloak_Mod2And3.Weapon_Mod_Beastmaster_Cloak_Mod2And3'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'bUseDefaultCriticalHitMultiplier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/Balance/Weapon_Mod_Beastmaster_Cloak_Mod3.Weapon_Mod_Beastmaster_Cloak_Mod3'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod3.Augment_Beastmaster_Cloak_Mod3:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            ''
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Spiderant_Mod3'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.0
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Spiderant_Mod3'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            6.0
        ]
    ]
]

Fade_Away_A4=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill2_Cloak/Augments/Augment_Beastmaster_Cloak_Mod4'            
        ],
        [
            'The [skillbold]Health Regeneration[/skillbold] and [skillbold]Movement Speed[/skillbold] of [actionskill]Fade Away[/actionskill] last for a short time after it has ended.'
        ]
    ]
]

Base_Jabber=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/StatusEffects/Status_Beastmaster_PetJabbBuff_Base'            
        ],
        [
            """
                (
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/Character/Att_GroundSpeedScale.Att_GroundSpeedScale\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.3)
                    )
                )
            """
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon.Augment_Pet_Jabbermon:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            """
                (
                    BaseValueConstant=1.0,
                    BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,
                    BaseValueScale=0.15
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey.Default__BPChar_PetMonkey_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey.Default__BPChar_PetMonkey_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'BalancedItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Weapons/JabberWeaponBase/ItemPool_BM_JabberWeapon_Base'            
        ],
        [
            """
            (
                (
                    InventoryBalanceData=/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Balance/Balance_PS_JAK_MelsCompanion.Balance_PS_JAK_MelsCompanion,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Balance/Balance_PS_JAK_MelsCompanion.Balance_PS_JAK_MelsCompanion\"',
                    Weight=(BaseValueConstant=1.0,BaseValueScale=1.0)
                )
            )
            """
        ]
    ],
    [
        [
            'RarityData'
        ],
        [
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Balance/Balance_PS_JAK_MelsCompanion'            
        ],
        [
            '/Game/GameData/Loot/RarityData/RarityData_04_VeryRare.RarityData_04_VeryRare'
        ]
    ],
    [
        [
            'InventoryAttributeEffects'
        ],
        [
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Parts/Part_PS_JAK_Barrel_MelsCompanion'            
        ],
        [
            """
            (
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=2.2)
                ),
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_StatusEffectChance.Att_Weapon_StatusEffectChance"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=1.5)
                )
            )
            """
        ]
    ],
    [
        [
            'DamageType'
        ],
        [
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Parts/Part_PS_JAK_Barrel_MelsCompanion.Part_PS_JAK_Barrel_MelsCompanion:AspectList_WeaponDamageTypeAspectData'            
        ],
        [
            "BlueprintGeneratedClass'/Game/GameData/DamageTypes/Radiation/DmgType_Radiation_Impact.DmgType_Radiation_Impact_C'"
        ]
    ],
    [
        [
            'ImpactData'
        ],
        [
            '/Game/Gear/Weapons/Pistols/Jakobs/_Shared/_Design/_Unique/MelsCompanion/Parts/Part_PS_JAK_Barrel_MelsCompanion.Part_PS_JAK_Barrel_MelsCompanion:AspectList_WeaponDamageTypeAspectData'            
        ],
        [
            '/Game/GameData/Impacts/Impact_Bullet_Radiation.Impact_Bullet_Radiation'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon'            
        ],
        [
            "You are joined by a loyal [red]Jabber[/red] companion, armed with a [skillbold]Radiation Pistol[/skillbold]. While accompanied by the [red]Jabber[/red], your [skillbold]Slide Speed[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Jabber[/red] to throw a [skillbold]Radiation Barrel[/skillbold] at enemies."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon.Augment_Pet_Jabbermon:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            "[skillbold]Movement Speed:[/skillbold] $VALUE$"
        ]
    ]
]

JAK_SG_Beefcake_BALANCE=[
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/EPartList_Jakobs_Shotgun.EPartList_Jakobs_Shotgun'
    ],
    [
        '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Weapons/JabberWeaponBeefcake/Balance_SG_JAK_JabberBeefcake.Balance_SG_JAK_JabberBeefcake',
        '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Weapons/JabberWeaponBeefcake/PartSet_SG_JAK_JabberBeefcake.PartSet_SG_JAK_JabberBeefcake'
    ],
    [ 
    '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Body/Part_SG_JAK_Body.Part_SG_JAK_Body'
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Barrel/Barrel_02/Part_SG_JAK_Barrel_02.Part_SG_JAK_Barrel_02',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Barrel/Barrel_02/Part_SG_JAK_Barrel_02_A.Part_SG_JAK_Barrel_02_A',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Barrel/Barrel_02/Part_SG_JAK_Barrel_02_B.Part_SG_JAK_Barrel_02_B',
            '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Barrel/Barrel_02/Part_SG_JAK_Barrel_02_C.Part_SG_JAK_Barrel_02_C'
        ]
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Body/Part_SG_JAK_Trigger_02.Part_SG_JAK_Trigger_02'        
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Bolt/Part_SG_JAK_Bolt_02.Part_SG_JAK_Bolt_02'        
    ],
    [ 
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Foregrip/Part_SG_JAK_Foregrip_04.Part_SG_JAK_Foregrip_04'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Stock/Part_SG_JAK_Stock_04.Part_SG_JAK_Stock_04'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Stock/Part_SG_JAK_Stock_04_A.Part_SG_JAK_Stock_04_A'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Magazine/Part_SG_JAK_Mag_04.Part_SG_JAK_Mag_04'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Scope/Part_SG_JAK_IronSight.Part_SG_JAK_IronSight'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Jakobs/_Shared/_Design/Parts/Material/Part_SG_JAK_Material_04_VeryRare.Part_SG_JAK_Material_04_VeryRare'
    ]
]

Evo1_Jabber=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/StatusEffects/Status_Beastmaster_PetJabbBuff_Evo1'            
        ],
        [
            """
                (
                    (
                        AttributeData=None,
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=(DataTable=None,RowName=None,ValueName=None),BaseValueAttribute=None,BaseValueScale=1.0)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Melee.Att_DamageSourceInstigatorMultiplier_Melee\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SimpleFormulas.DataTable_Beastmaster_SimpleFormulas,RowName=PlayerBuff_PetJabb_Evo1,ValueName=None),BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale',BaseValueScale=0.15)
                    )
                )
            """
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Beefcake.Augment_Pet_Jabbermon_Beefcake:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            """
                (
                    BaseValueConstant=1.0,
                    DataTableValue=(DataTable=None,RowName=None,ValueName=None),
                    BaseValueAttribute=None,
                    AttributeInitializer=None,
                    BaseValueScale=1.0
                )
            """
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Beefcake.Augment_Pet_Jabbermon_Beefcake:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            """
                (
                    BaseValueConstant=1.0,
                    DataTableValue=None,
                    BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,
                    AttributeInitializer=None,
                    BaseValueScale=0.3
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey_Evo1_Beefcake.Default__BPChar_PetMonkey_Evo1_Beefcake_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey.Default__BPChar_PetMonkey_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Beefcake'            
        ],
        [
            "Your [red]Jabber[/red] evolves into a [red]Beefcake[/red], discarding its pistol and equipping a [skillbold]Shotgun[/skillbold]. While accompanied by the [red]Beefcake[/red], your [skillbold]Movement Speed[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Beefcake[/red] to deliver a powerful [skillbold]Melee Attack[/skillbold] that knocks enemies back."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Beefcake.Augment_Pet_Jabbermon_Beefcake:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            "[skillbold]Melee Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Beefcake.Augment_Pet_Jabbermon_Beefcake:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            ""
        ]
    ],
    [
        [
            'RarityData'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Weapons/JabberWeaponBeefcake/Balance_SG_JAK_JabberBeefcake'            
        ],
        [
            '/Game/GameData/Loot/RarityData/RarityData_04_VeryRare.RarityData_04_VeryRare'
        ]
    ],
    [    
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Jabbermon_GrandSlam'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            3.0
        ]
    ]
]

TOR_AR_Gunslinger_BALANCE=[
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/EPartList_AR_TOR.EPartList_AR_TOR'
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Balance/Balance_AR_TOR_TryBolt.Balance_AR_TOR_TryBolt',
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Balance/InvPartSet_AR_TOR_TryBolt.InvPartSet_AR_TOR_TryBolt'
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Body/Part_AR_TOR_Body.Part_AR_TOR_Body',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Body/Part_AR_TOR_Body_A.Part_AR_TOR_Body_A',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Body/Part_AR_TOR_Body_B.Part_AR_TOR_Body_B',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Body/Part_AR_TOR_Body_C.Part_AR_TOR_Body_C'
        ]
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Parts/Part_AR_TOR_Barrel_TryBolt.Part_AR_TOR_Barrel_TryBolt',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Barrel/Barrel_02/Part_AR_TOR_Barrel_03_A.Part_AR_TOR_Barrel_03_A',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Barrel/Barrel_02/Part_AR_TOR_Barrel_03_B.Part_AR_TOR_Barrel_03_B',
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Barrel/Barrel_02/Part_AR_TOR_Barrel_03_C.Part_AR_TOR_Barrel_03_C'
        ]
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Exhaust/Part_AR_TOR_Exhaust_01.Part_AR_TOR_Exhaust_01'        
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/ForeGrip/Part_AR_TOR_ForeGrip_05.Part_AR_TOR_ForeGrip_05'        
    ],
    [ 
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Grip/Part_AR_TOR_Grip_04.Part_AR_TOR_Grip_04'
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Magazine/Part_AR_TOR_Magazine_01.Part_AR_TOR_Magazine_01'
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/Parts/Scope/Part_AR_TOR_Scope_01.Part_AR_TOR_Scope_01'
    ],
    [
        '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Parts/Part_AR_TOR_Material_TryBolt.Part_AR_TOR_Material_TryBolt'
    ]
]

Evo2_Jabber=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/StatusEffects/Status_Beastmaster_PetJabbBuff_Evo2'            
        ],
        [
            """
                (
                    (
                        AttributeData=None,
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=(DataTable=None,RowName=None,ValueName=None),BaseValueAttribute=None,BaseValueScale=1.0)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Weapons/Att_Weapon_ProjectileSpeedScale.Att_Weapon_ProjectileSpeedScale\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.3)
                    )
                )
            """
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Gunslinger.Augment_Pet_Jabbermon_Gunslinger:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            """
                (
                    BaseValueConstant=1.0,
                    DataTableValue=(DataTable=None,RowName=None,ValueName=None),
                    BaseValueAttribute=None,
                    AttributeInitializer=None,
                    BaseValueScale=1.0
                )
            """
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Gunslinger.Augment_Pet_Jabbermon_Gunslinger:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            """
                (
                    BaseValueConstant=1.0,
                    DataTableValue=None,
                    BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,
                    AttributeInitializer=None,
                    BaseValueScale=0.3
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey_Evo2_Gunslinger.Default__BPChar_PetMonkey_Evo2_Gunslinger_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Character/BPChar_PetMonkey_Evo2_Gunslinger.Default__BPChar_PetMonkey_Evo2_Gunslinger_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'BalancedItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Monkey/_Design/Weapons/JabberWeaponGunslinger/ItemPool_BM_JabberWeapon_Gunslinger'            
        ],
        [
            """
            (
                (
                    InventoryBalanceData=/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Balance/Balance_AR_TOR_TryBolt.Balance_AR_TOR_TryBolt,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Balance/Balance_AR_TOR_TryBolt.Balance_AR_TOR_TryBolt\"',
                    Weight=(BaseValueConstant=1.0,BaseValueScale=1.0)
                )
            )
            """
        ]
    ],
    [
        [
            'InventoryAttributeEffects'
        ],
        [
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Parts/Part_AR_TOR_Barrel_TryBolt'            
        ],
        [
            """
            (
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=0.4)
                )
            )
            """
        ]
    ],
    [
        [
            'AutomaticBurstCount.BaseValue'
        ],
        [
            '/Game/Gear/Weapons/AssaultRifles/Torgue/_Shared/_Design/_Unique/TryBolt/Parts/Part_AR_TOR_Barrel_TryBolt.Part_AR_TOR_Barrel_TryBolt:WeaponUseComponent_BPWeaponFireProjectileComponent_Torgue'            
        ],
        [
            0.0
        ]
    ],
    [    
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Jabbermon_RocketLauncher'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            2.5
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Gunslinger'            
        ],
        [
            "Your [red]Jabber[/red] evolves into a [red]Gunslinger[/red], discarding its pistol and equipping an [skillbold]Assault Rifle[/skillbold]. While accompanied by the [red]Gunslinger[/red], your [skillbold]Projectile Speed[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Gunslinger[/red] to equipe a [skillbold]Rocket Launcher[/skillbold] to attack enemies."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Gunslinger.Augment_Pet_Jabbermon_Gunslinger:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            "[skillbold]Projectile Speed:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Jabbermon_Gunslinger.Augment_Pet_Jabbermon_Gunslinger:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            ""
        ]
    ]
]

Self_Repairing_System=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun4/Passive_Beastmaster_HitAndRun_4.Default__Passive_Beastmaster_HitAndRun_4_C'            
        ],
        [
            'You gain [skillbold]Max Health[/skillbold] and [skillbold]Health Regeneration[/skillbold].'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun4/Passive_Beastmaster_HitAndRun_4.Default__Passive_Beastmaster_HitAndRun_4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '[skillbold]Health Regeneration:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun4/Passive_Beastmaster_HitAndRun_4.Default__Passive_Beastmaster_HitAndRun_4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            'false'
        ]
    ],
    [    
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun4'
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            0.06
        ]
    ],
    [    
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun4'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.004
        ]
    ]
]

Ambush_Predator=[
    [
        [
            'AbilityClass'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_HitAndRun.AbilityTree_Branch_HitAndRun:Tiers_OakPlayerAbilityTreeTierData_1.Items_OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Passive_Beastmaster_Ranged5_C'
        ]
    ],
    [
        [
            'ItemFrameName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_HitAndRun.AbilityTree_Branch_HitAndRun:Tiers_OakPlayerAbilityTreeTierData_1.Items_OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            'ambushPredator'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Default__Passive_Beastmaster_Ranged5_C'            
        ],
        [
            "While there are no enemies in melee range, you gain [skillbold]Handling[/skillbold] and [skillbold]Accuracy[/skillbold]."
        ]
    ],
    [
        [
            'RadiusInit'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Default__Passive_Beastmaster_Ranged5_C:Condition_GbxCondition_AreEnemiesWithinRadius'            
        ],
        [
            '(BaseValueConstant=250)'
        ]
    ],
    [
        [
            'bCalculateWithReductionMath'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Default__Passive_Beastmaster_Ranged5_C:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Default__Passive_Beastmaster_Ranged5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Weapons/Att_Weapon_AccuracyImpulse.Att_Weapon_AccuracyImpulse'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Passive_Beastmaster_Ranged5.Default__Passive_Beastmaster_Ranged5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Accuracy:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_AccuracyImpulse.Att_Weapon_AccuracyImpulse,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_Spread.Att_Weapon_Spread,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Accuracy/Att_AccuracyMaxValue.Att_AccuracyMaxValue,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_RecoilHeightScale.Att_Weapon_RecoilHeightScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_RecoilWidthScale.Att_Weapon_RecoilWidthScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_SwayZoomScale.Att_Weapon_SwayZoomScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_SwayScale.Att_Weapon_SwayScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged5/Status_Beastmaster_Ranged5.Status_Beastmaster_Ranged5:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                )
            )
            """
        ]
    ],
    [   #Accuracy and Handling
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged5'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            -0.06
        ]
    ]
]

Eager_To_Impress=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Bond2/Passive_Beastmaster_Bond2.Default__Passive_Beastmaster_Bond2_C'            
        ],
        [
            "Whenever you kill an enemy, [skillbold]Action Skill Cooldown Time[/skillbold] is reduced.<br>Whenever your [red]Pet[/red] kills an enemy, [skillbold]Action Skill Cooldown Time[/skillbold] is reduced even more and [actionskill]Attack Command's Cooldown[/actionskill] is refreshed."
        ]
    ]
]

All_My_BFFs=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun7/Passive_Beastmaster_HitAndRun_7.Default__Passive_Beastmaster_HitAndRun_7_C'            
        ],
        [
            '[skillbold]Allies[/skillbold] share a portion of your [skillbold]Health Regeneration Speed[/skillbold]. Your [red]Pet[/red] shares twice the amount of the bonus.'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun7/Passive_Beastmaster_HitAndRun_7.Default__Passive_Beastmaster_HitAndRun_7_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Shared Health Regeneration:[/skillbold] $VALUE$"
        ]
    ]
]

Round_Up=[
    [
        [
            'AbilityName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C'            
        ],
        [
            'Round Up !'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C'            
        ],
        [
            "The more your magazine is filled, the more [skillbold]Fire Rate[/skillbold] you gain. Your shots [skillbold]Consumme No Ammo[/skillbold] for a short time after reloading."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '[skillbold]Fire Rate:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/GameData/Weapons/Att_Weapon_FireRate.Att_Weapon_FireRate'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            ''
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Passive_Beastmaster_HitAndRun8.Default__Passive_Beastmaster_HitAndRun8_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '[skillbold]Round Up ! Duration:[/skillbold] $VALUE$ second'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Status_Beastmaster_HitAndRun8'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_FireRate.Att_Weapon_FireRate,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Status_Beastmaster_HitAndRun8.Status_Beastmaster_HitAndRun8:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                )
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Status_Beastmaster_HitAndRun8.Status_Beastmaster_HitAndRun8:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0'            
        ],
        [
            """
            (
                BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_HuntSkillPassiveDurationScale.Att_Beastmaster_HuntSkillPassiveDurationScale,
                BaseValueScale=0.06
            )
            """
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Status_Beastmaster_HitAndRun8_Triggered'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_ShotAmmoCost.Att_Weapon_ShotAmmoCost,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun8/Status_Beastmaster_HitAndRun8_Triggered.Status_Beastmaster_HitAndRun8_Triggered:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                )
            )
            """
        ]
    ],
    [   #Ammo Cost
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun8'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            -1.0
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun8'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            1.0
        ]
    ]
]

Lick_The_Wounds=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/_Shared/_Design/Augments/Augment_Pet_Global_Revive'            
        ],
        [
            "When you are in [skillbold]Fight For Your Life[/skillbold], your [red]Pet[/red] will attempt to [skillbold]Revive[/skillbold] you. If it does, it gains [skillbold]Damage[/skillbold] for a short time."
        ]
    ]
]

Turn_Tail_And_Run=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Passive_Beastmaster_HitAndRun_5.Default__Passive_Beastmaster_HitAndRun_5_C'            
        ],
        [
            "While moving you gain [skillbold]Health Regeneration[/skillbold] and [skillbold]Damage Reduction[/skillbold]. While still, you gain [skillbold]Critical Hit Damage[/skillbold] and [skillbold]Fire Rate[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Passive_Beastmaster_HitAndRun_5.Default__Passive_Beastmaster_HitAndRun_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Health Regeneration While Moving:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Passive_Beastmaster_HitAndRun_5.Default__Passive_Beastmaster_HitAndRun_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            "[skillbold]Critical Hit Damage While Still:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'bCalculateWithReductionMath'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Passive_Beastmaster_HitAndRun_5.Default__Passive_Beastmaster_HitAndRun_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Passive_Beastmaster_HitAndRun_5.Default__Passive_Beastmaster_HitAndRun_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier'
        ]
    ],
    [
        [
            'AttributeEffects.AttributeEffects[0].AttributeData'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun5/Status_Beastmaster_HitAndRun5_Still'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier'
        ]
    ],
    [   #Damage Reduction
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun5'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            -0.1
        ]
    ],
    [   #Health regeneration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun5'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            0.006
        ]
    ],
    [   #Critical Hit Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun5'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            0.05
        ]
    ],
    [   #Fire Rate
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun5'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            0.08333333333333333
        ]
    ]
]

The_Fast_And_The_Furryous=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C'            
        ],
        [
            "While above half health, you gain [skillbold]Movement Speed[/skillbold], [skillbold]Swap Speed[/skillbold] and [skillbold]Gun Damage[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            "[skillbold]Swap Speed:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            '/Game/GameData/Attributes/Character/Att_WeaponSwapSpeedScale.Att_WeaponSwapSpeedScale'
        ]
    ],
    [
        [
            'SignStyle'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            'Positive'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Movement Speed:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/Character/Att_GroundSpeedScale.Att_GroundSpeedScale'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Gun Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage'
        ]
    ],
    [
        [
            'AbilityEffects.AbilityEffects[1].TargetResolutionStrategies'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Passive_Beastmaster_HitAndRun10.Default__Passive_Beastmaster_HitAndRun10_C'            
        ],
        [
            '(/Game/PlayerCharacters/_Shared/_Design/Skills/TargetResolution_Self.TargetResolution_Self)'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Status_HitAndRun10_WeaponDamage_DA'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Character/Att_GroundSpeedScale.Att_GroundSpeedScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Status_HitAndRun10_WeaponDamage_DA.Status_HitAndRun10_WeaponDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Status_HitAndRun10_WeaponDamage_DA.Status_HitAndRun10_WeaponDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                )             
            )
            """
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Status_Beastmaster_HitAndRun_10_PetDamage'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Character/Att_WeaponSwapSpeedScale.Att_WeaponSwapSpeedScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Status_Beastmaster_HitAndRun_10_PetDamage.Status_Beastmaster_HitAndRun_10_PetDamage:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                )  
            )
            """
        ]
    ],
    [   #Movement Speed
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'HitAndRun_10'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.0833333333333333
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'HitAndRun_10'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            0.0833333333333333
        ]
    ],
    [   #Swap Speed
        [
            'Value.BaseValueConstant'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun10/Att_BST_HitAndRun10_PetDamage.Att_BST_HitAndRun10_PetDamage:ValueResolver_ConstantAttributeValueResolver'            
        ],
        [
            -0.15
        ]
    ],
]

Hidden_Machine=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun9/Passive_Beastmaster_HitAndRun9_NotBroken.Default__Passive_Beastmaster_HitAndRun9_NotBroken_C'            
        ],
        [
            "You deal more [skillbold]Damage[/skillbold] to enemies that are not targetting you."
        ]
    ]
]

Rage_And_Recover=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun3/Passive_Beastmaster_HitAndRun_3.Default__Passive_Beastmaster_HitAndRun_3_C'            
        ],
        [
            '[skillbold]Kill Skill[/skillbold]. <br>You and your [red]Pet[/red] gain [skillbold]Health Regeneration[/skillbold] based on your missing health.'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun3/Passive_Beastmaster_HitAndRun_3.Default__Passive_Beastmaster_HitAndRun_3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '[skillbold]Health Regeneration:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun3/Passive_Beastmaster_HitAndRun_3.Default__Passive_Beastmaster_HitAndRun_3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ],
    [    #Health Regeneration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun3'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.01
        ]
    ],
    [    #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun3'
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            10.0
        ]
    ]
]

The_Power_Inside=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun11/Passive_Beastmaster_HitAndRun11.Default__Passive_Beastmaster_HitAndRun11_C'            
        ],
        [
            'You and your [red]Pet[/red] gain [skillbold]Damage[/skillbold] when you activate an [actionskill]Action Skill[/actionskill]. This bonus is based on your [skillbold]Health Regeneration[/skillbold].'
        ]
    ],
    [    
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun11/Passive_Beastmaster_HitAndRun11.Default__Passive_Beastmaster_HitAndRun11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '[skillbold]Damage:[/skillbold] $VALUE$ times your [skillbold]Health Regeneration[/skillbold]'
        ]
    ],
    [    
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun11/Passive_Beastmaster_HitAndRun11.Default__Passive_Beastmaster_HitAndRun11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ],
    [    
        [
            'bDisplayAsPercentage'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun11/Passive_Beastmaster_HitAndRun11.Default__Passive_Beastmaster_HitAndRun11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ],
    [    
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun11/Status_Beastmaster_HitAndRun11'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_DamageDealtMultiplier.Att_DamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueAttribute=/Game/GameData/Attributes/Health/Att_HealthPassivePercentRegenerationRate.Att_HealthPassivePercentRegenerationRate,BaseValueScale=5.0),
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_DamageDealtMultiplier.Att_DamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueAttribute=/Game/GameData/Attributes/Health/Att_HealthOnIdleRegenerationRate.Att_HealthOnIdleRegenerationRate,BaseValueScale=5.0),
                )  
            )
            """
        ]
    ],
    [    #Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun_11'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            5.0
        ]
    ],
    [    #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'P_HitAndRun_11'
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            10.0
        ]
    ]
]
