SHIELD_Manufacturer=[
    [ 
        [
            'Anshin_Common'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.0
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            -0.5
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.0
        ]
    ],
    [ 
        [
            'Anshin_Uncommon'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            -0.5*0.8
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.2
        ]
    ],
    [ 
        [
            'Anshin_Rare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            -0.5*0.8*0.8
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.2*1.2
        ]
    ],
    [ 
        [
            'Anshin_VeryRare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.2*1.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            -0.5*0.8*0.8*0.8
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.2*1.2*1.2
        ]
    ],
    [ 
        [
            'Anshin_Legendary'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.2*1.2*1.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            -0.5*0.8*0.8*0.8*0.8
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.2*1.2*1.2*1.2
        ]
    ],
    [ 
        [
            'Pangolin_Common'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.5
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.0
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.5
        ]
    ],
    [ 
        [
            'Pangolin_Uncommon'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.5*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.5*0.8
        ]
    ],
    [ 
        [
            'Pangolin_Rare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.5*1.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.5*0.8*0.8
        ]
    ],
    [ 
        [
            'Pangolin_VeryRare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.5*1.2*1.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.2*1.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.5*0.8*0.8*0.8
        ]
    ],
    [ 
        [
            'Pangolin_Legendary'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            0.5*1.2*1.2*1.2*1.2
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.2*1.2*1.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            0.5*0.8*0.8*0.8*0.8
        ]
    ],
    [ 
        [
            'Hyperion_Common'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            -0.5
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.5
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.5
        ]
    ],
    [ 
        [
            'Hyperion_Uncommon'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            -0.5*0.8
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.5*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.5*1.2
        ]
    ],
    [ 
        [
            'Hyperion_Rare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            -0.5*0.8*0.8
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.5*1.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.5*1.2*1.2
        ]
    ],
    [ 
        [
            'Hyperion_VeryRare'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            -0.5*0.8*0.8*0.8
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.5*1.2*1.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.5*1.2*1.2*1.2
        ]
    ],
    [ 
        [
            'Hyperion_Legendary'
        ],
        [
            'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
            -0.5*0.8*0.8*0.8*0.8
        ],
        [
            'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
            0.5*1.2*1.2*1.2*1.2
        ],
        [
            'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
            -0.5*1.2*1.2*1.2*1.2
        ]
    ]
]

SHIELD_AUG=[ 
    [ 
        [ 
            'Resistance'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.25
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.15
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                -0.2
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                -0.4*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                -0.68*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Nova'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.1
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.08
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                -0.2
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.5
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                1.7*1.2
            ]
        ],
        [ 
            [ 
                'Secondary_1_62_F1E72F2542B441230290B388F4C494D1',
                550
            ],
            [ 
                'Secondary_2_63_5492A1134C687D18D386DAA6A8FF185E',
                550
            ],
            [ 
                'Secondary_3_64_A3C5C0EC446950EEEEC7E9B3776271B7',
                550
            ]
        ]
    ],
    [ 
        [ 
            'Spike'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                0.1
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.05
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.05
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.5
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                1.7*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Roid'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.15
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.05
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                1.0
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.8
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                1.6*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                2.72*1.2
            ]
        ]
    ],
    [ 
        [ 
            'TriggerHappy'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.1
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.05
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.1
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.08
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.16*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.272*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Fleeting'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                0.0
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.15
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.1
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.2*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.34*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Adrenaline'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.05
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.15
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                -0.1
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                -0.2*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                -0.34*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Amp'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.2
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                -0.15
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.4
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.8*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                1.36*1.2
            ]
        ],
        [ 
            [ 
                'Secondary_1_62_F1E72F2542B441230290B388F4C494D1',
                0.3
            ],
            [ 
                'Secondary_2_63_5492A1134C687D18D386DAA6A8FF185E',
                0.3
            ],
            [ 
                'Secondary_3_64_A3C5C0EC446950EEEEC7E9B3776271B7',
                0.3
            ]
        ]
    ],
    [ 
        [ 
            'Reflection'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.08
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.05
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.2
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.4*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.68*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Adaptive'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.05
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.05
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.05
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                -0.2
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                -0.4*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                -0.68*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Absorb'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.2
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.15
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.2
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.4*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.68*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Turtle'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                0.5
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.25
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.0
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.0
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.0
            ]
        ],
        [ 
            [ 
                'Secondary_1_62_F1E72F2542B441230290B388F4C494D1',
                -0.15
            ],
            [ 
                'Secondary_2_63_5492A1134C687D18D386DAA6A8FF185E',
                -0.3
            ],
            [ 
                'Secondary_3_64_A3C5C0EC446950EEEEC7E9B3776271B7',
                -0.45
            ]
        ]
    ],
    [ 
        [ 
            'Health'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.15
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.1
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.1
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.15
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.3*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.51*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Vagabond'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.15
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.2
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                -0.2
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.1
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.2*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.34*1.2
            ]
        ]
    ],
    [ 
        [ 
            'Brimming'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.05
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.2
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                -0.2
            ]
        ],
        [ 
            [ 
                'Primary_1_56_207C26E1450330458D6C38B245C338C5',
                0.08
            ],
            [ 
                'Primary_2_57_B75F9DB543F7963A15ECCBAC5D036A8E',
                0.16*1.2
            ],
            [ 
                'Primary_3_58_12AFE8834560F575F1813591F715BCE1',
                0.272*1.2
            ]
        ]
    ],
    [ 
        [ 
            'RechargeRate'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.08
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.3
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.0
            ]
        ]
    ],
    [ 
        [ 
            'RechargeDelay'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                -0.08
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                0.0
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                -0.3
            ]
        ]
    ],
    [ 
        [ 
            'Capacity'
        ],
        [ 
            [ 
                'Capacity_26_1F88EEE04E890908FB52AE9442E35CE3',
                0.3
            ],
            [ 
                'RechargeRate_27_8A47A06C426C0A244C25068F9B363075',
                -0.08
            ],
            [ 
                'RechargeDelay_28_56D5148C458B7E0E4C3DEB8437889B8E',
                0.08
            ]
        ]
    ]
]

SH_BALANCE_Pangolin_Common=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Pangolin_01_Common.InvBalD_Shield_Pangolin_01_Common',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Pangolin_01_Common.PartSet_Shield_Pangolin_01_Common'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_02_Pangolin.Shield_Part_Body_02_Pangolin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.1
            ]  
        ] 
    ],
    [ 
        [ 
            0
        ],
        [ 
            1
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Pangolin_01_Common.Shield_Part_Material_Pangolin_01_Common'
    ]
]

SH_BALANCE_Pangolin_Uncommon=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Pangolin_02_Uncommon.InvBalD_Shield_Pangolin_02_Uncommon',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Pangolin_02_Uncommon.PartSet_Shield_Pangolin_02_Uncommon'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_02_Pangolin.Shield_Part_Body_02_Pangolin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.2
            ]  
        ] 
    ],
    [ 
        [ 
            1
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Pangolin_02_Uncommon.Shield_Part_Material_Pangolin_02_Uncommon'
    ]
]

SH_BALANCE_Pangolin_Rare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Pangolin_03_Rare.InvBalD_Shield_Pangolin_03_Rare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Pangolin_03_Rare.PartSet_Shield_Pangolin_03_Rare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_02_Pangolin.Shield_Part_Body_02_Pangolin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.3
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Pangolin_03_Rare.Shield_Part_Material_Pangolin_03_Rare'
    ]
]

SH_BALANCE_Pangolin_VeryRare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Pangolin_04_VeryRare.InvBalD_Shield_Pangolin_04_VeryRare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Pangolin_04_VeryRare.PartSet_Shield_Pangolin_04_VeryRare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_02_Pangolin.Shield_Part_Body_02_Pangolin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.4
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            3
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity.Part_Shield_Aug_Capacity',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle.Part_Shield_Aug_Turtle',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect.Part_Shield_Aug_Reflect',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb.Part_Shield_Aug_Absorb'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Pangolin_04_VeryRare.Shield_Part_Material_Pangolin_04_VeryRare'
    ]
]

SH_BALANCE_Hyperion_Common=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Hyperion_01_Common.InvBalD_Shield_Hyperion_01_Common',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Hyperion_01_Common.PartSet_Shield_Hyperion_01_Common'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_03_Hyperion.Shield_Part_Body_03_Hyperion'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.1
            ]  
        ] 
    ],
    [ 
        [ 
            0
        ],
        [ 
            1
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Hyperion_01_Common.Shield_Part_Material_Hyperion_01_Common'
    ]
]

SH_BALANCE_Hyperion_Uncommon=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Hyperion_02_Uncommon.InvBalD_Shield_Hyperion_02_Uncommon',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Hyperion_02_Uncommon.PartSet_Shield_Hyperion_02_Uncommon'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_03_Hyperion.Shield_Part_Body_03_Hyperion'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.2
            ]  
        ] 
    ],
    [ 
        [ 
            1
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Hyperion_02_Uncommon.Shield_Part_Material_Hyperion_02_Uncommon'
    ]
]

SH_BALANCE_Hyperion_Rare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Hyperion_03_Rare.InvBalD_Shield_Hyperion_03_Rare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Hyperion_03_Rare.PartSet_Shield_Hyperion_03_Rare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_03_Hyperion.Shield_Part_Body_03_Hyperion'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.3
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Hyperion_03_Rare.Shield_Part_Material_Hyperion_03_Rare'
    ]
]

SH_BALANCE_Hyperion_VeryRare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Hyperion_04_VeryRare.InvBalD_Shield_Hyperion_04_VeryRare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Hyperion_04_VeryRare.PartSet_Shield_Hyperion_04_VeryRare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_03_Hyperion.Shield_Part_Body_03_Hyperion'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.4
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            3
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp.Part_Shield_Aug_Amp',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid.Part_Shield_Aug_Roid',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova.Part_Shield_Aug_Nova',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike.Part_Shield_Aug_Spike',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay.Part_Shield_Aug_RechargeDelay',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate.Part_Shield_Aug_RechargeRate'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Hyperion_04_VeryRare.Shield_Part_Material_Hyperion_04_VeryRare'
    ]
]

SH_BALANCE_Anshin_Common=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Anshin_01_Common.InvBalD_Shield_Anshin_01_Common',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Anshin_01_Common.PartSet_Shield_Anshin_01_Common'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_01_Anshin.Shield_Part_Body_01_Anshin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.1
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.1
            ]  
        ] 
    ],
    [ 
        [ 
            0
        ],
        [ 
            1
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Anshin_01_Common.Shield_Part_Material_Anshin_01_Common'
    ]
]

SH_BALANCE_Anshin_Uncommon=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Anshin_02_Uncommon.InvBalD_Shield_Anshin_02_Uncommon',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Anshin_02_Uncommon.PartSet_Shield_Anshin_02_Uncommon'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_01_Anshin.Shield_Part_Body_01_Anshin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.2
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.2
            ]  
        ] 
    ],
    [ 
        [ 
            1
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Anshin_02_Uncommon.Shield_Part_Material_Anshin_02_Uncommon'
    ]
]

SH_BALANCE_Anshin_Rare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Anshin_03_Rare.InvBalD_Shield_Anshin_03_Rare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Anshin_03_Rare.PartSet_Shield_Anshin_03_Rare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_01_Anshin.Shield_Part_Body_01_Anshin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.3
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.3
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            2
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Anshin_03_Rare.Shield_Part_Material_Anshin_03_Rare'
    ]
]

SH_BALANCE_Anshin_VeryRare=[ 
    [ 
        '/Game/Gear/Shields/_Design/A_Data/EPartList_Shield.EPartList_Shield'
    ],
    [ 
        '/Game/Gear/Shields/_Design/InvBalance/InvBalD_Shield_Anshin_04_VeryRare.InvBalD_Shield_Anshin_04_VeryRare',
        '/Game/Gear/Shields/_Design/PartSets/PartSet_Shield_Anshin_04_VeryRare.PartSet_Shield_Anshin_04_VeryRare'
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Manufacturer/Shield_Part_Body_01_Anshin.Shield_Part_Body_01_Anshin'
    ],
    [
        [
            1
        ],
        [
            1
        ],
        [
            1
        ],
        [ 
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Normal.Shield_Part_Element_Normal',
                0.5
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Fire.Shield_Part_Element_Fire',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Shock.Shield_Part_Element_Shock',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Corrosive.Shield_Part_Element_Corrosive',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Cryo.Shield_Part_Element_Cryo',
                0.4
            ],
            [
                '/Game/Gear/Shields/_Design/PartSets/Part_Element/Shield_Part_Element_Radiation.Shield_Part_Element_Radiation',
                0.4
            ]  
        ] 
    ],
    [ 
        [ 
            2
        ],
        [ 
            3
        ],
        [ 
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance.Part_Shield_Aug_Resistance',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive.Part_Shield_Aug_Adaptive',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline.Part_Shield_Aug_Adrenaline',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming.Part_Shield_Aug_Brimming',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet.Part_Shield_Aug_Fleet',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy.Part_Shield_Aug_Healthy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy.Part_Shield_Aug_TriggerHappy',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond',
            '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond.Part_Shield_Aug_Vagabond'
        ]
    ],
    [ 
        '/Game/Gear/Shields/_Design/PartSets/Part_Material/Shield_Part_Material_Anshin_04_VeryRare.Shield_Part_Material_Anshin_04_VeryRare'
    ]
]

SH_BALANCE=[ 
    SH_BALANCE_Pangolin_Common,
    SH_BALANCE_Pangolin_Uncommon,
    SH_BALANCE_Pangolin_Rare,
    SH_BALANCE_Pangolin_VeryRare,
    SH_BALANCE_Hyperion_Common,
    SH_BALANCE_Hyperion_Uncommon,
    SH_BALANCE_Hyperion_Rare,
    SH_BALANCE_Hyperion_VeryRare,
    SH_BALANCE_Anshin_Common,
    SH_BALANCE_Anshin_Uncommon,
    SH_BALANCE_Anshin_Rare,
    SH_BALANCE_Anshin_VeryRare
]

SHIELD_Excluders=[ 
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Absorb/Part_Shield_Aug_Absorb',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adaptive/Part_Shield_Aug_Adaptive',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Adrenaline/Part_Shield_Aug_Adrenaline',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Amp/Part_Shield_Aug_Amp',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Brimming/Part_Shield_Aug_Brimming',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Capacity/Part_Shield_Aug_Capacity',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Charges/Booster/Part_Shield_Aug_ShieldCharge',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Charges/FortifyCharge/Part_Shield_Aug_FortifyCharge',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Charges/HealthCharge/Part_Shield_Aug_HealthCharge',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Charges/PowerCharge/Part_Shield_Aug_PowerCharge',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Fleet/Part_Shield_Aug_Fleet',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Health/Part_Shield_Aug_Healthy',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Nova/Part_Shield_Aug_Nova',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/ProjectedShield/Part_Shield_Aug_Projected',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeDelay/Part_Shield_Aug_RechargeDelay',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/RechargeRate/Part_Shield_Aug_RechargeRate',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Reflect/Part_Shield_Aug_Reflect',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Resistance/Part_Shield_Aug_Resistance',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Roid/Part_Shield_Aug_Roid',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Safespace/Part_Shield_Aug_Knockback',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Spike/Part_Shield_Aug_Spike',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/TriggerHappy/Part_Shield_Aug_TriggerHappy',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Turtle/Part_Shield_Aug_Turtle',
    '/Game/Gear/Shields/_Design/PartSets/Part_Augment/Vagabond/Part_Shield_Aug_Vagabond'
]