Rakk_Attack=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/ActionSkill/ActionSkill_RakkAttack.Default__ActionSkill_RakkAttack_C'            
        ],
        [
            'You send forward 3 [actionskill]Rakks[/actionskill] to dive-bomb enemies.'
        ]
    ],
    [
        [
            'ChargeInitializationData'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/ActionSkill/ActionSkill_RakkAttack.Default__ActionSkill_RakkAttack_C'            
        ],
        [
            '(BaseValueConstant=1.0)'
        ]
    ],
    [
        [
            'Text'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/ActionSkill/ActionSkill_RakkAttack.Default__ActionSkill_RakkAttack_C:StatDataItems_UIStatData_Text_1'            
        ],
        [
            ''
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Skag'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.65
        ]
    ],
    [   #Cooldown
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Skag'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            12.0
        ]
    ],
    [   #Number of Rakks
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'Ultimate_Skag'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            3.0
        ]
    ]
]

Rakk_Attack_A1=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/Augments/Augment_Beastmaster_RakkAttack_Mod5'            
        ],
        [
            "Converts your [actionskill]Rakks[/actionskill] to [skillbold]Cryo Damage[/skillbold]."
        ]
    ]
]

Rakk_Attack_A2=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/Augments/Augment_Beastmaster_RakkAttack_Mod1'            
        ],
        [
            "When your [actionskill]Rakks[/actionskill] damage an enemy, a portion of your [skillbold]Health[/skillbold] is restored."
        ]
    ]
]

Rakk_Attack_A3=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/Augments/Augment_Beastmaster_RakkAttack_Mod4'            
        ],
        [
            "You send forward additional [actionskill]Rakks[/actionskill]."
        ]
    ]
]

Rakk_Attack_A4=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkills/Skill1_RakkAttack/Augments/Augment_Beastmaster_RakkAttack_Mod3'            
        ],
        [
            "Your [actionskill]Rakks[/actionskill] have increased [skillbold]Cooldown Rate[/skillbold], and gain an [skillbold]Additional Charge[/skillbold]."
        ]
    ]
]

Base_Spiderant=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/StatusEffects/Status_Beastmaster_PetSpidBuff_Base'            
        ],
        [
            """
                (
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Skill.Att_DamageSourceInstigatorMultiplier_Skill\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.2)
                    )
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant.Default__BPChar_PetSpiderant_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant.Default__BPChar_PetSpiderant_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant'            
        ],
        [
            "You are joined by a loyal [red]Spiderant[/red] companion. While accompanied by the [red]Spiderant[/red], your [skillbold]Action Skill Damage[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Spiderant[/red] to charge into enemies."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant.Augment_Pet_Spiderant:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Action Skill Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant.Augment_Pet_Spiderant:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Skill.Att_DamageSourceInstigatorMultiplier_Skill"
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Spiderant_Charge'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            3.0
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Spiderant_Pound'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            3.5
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Spiderant_BileBomb'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            2.0
        ]
    ]
]

Evo1_Spiderant=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/StatusEffects/Status_Beastmaster_PetSpidBuff_Evo1'            
        ],
        [
            """
                (
                    (
                        AttributeData=None,
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=(DataTable=None,RowName=None,ValueName=None),BaseValueAttribute=None,BaseValueScale=1.0)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/StatusEffects/EffectModifierAttributes/Att_StatusEffect_DamageCauser_CorrosiveDamage.Att_StatusEffect_DamageCauser_CorrosiveDamage\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.25)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/StatusEffects/EffectModifierAttributes/Att_StatusEffect_DamageCauser_FireDamage.Att_StatusEffect_DamageCauser_FireDamage\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.25)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/StatusEffects/EffectModifierAttributes/Att_StatusEffect_DamageCauser_RadiationDamage.Att_StatusEffect_DamageCauser_RadiationDamage\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.25)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/StatusEffects/EffectModifierAttributes/Att_StatusEffect_DamageCauser_ShockDamage.Att_StatusEffect_DamageCauser_ShockDamage\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.25)
                    )
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant_Evo1_Fire.Default__BPChar_PetSpiderant_Evo1_Fire_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant_Evo1_Fire.Default__BPChar_PetSpiderant_Evo1_Fire_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_Badass'            
        ],
        [
            "Your [red]Spiderant[/red] evolves into a [red]Scorcher[/red], occasionally dealing Incendiary Damage to all enemies nearby. While accompanied by the [red]Scorcher[/red], your [skillbold]Elemental Damage Over Time[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Scorcher[/red] to charge into enemies."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_Badass.Augment_Pet_Spiderant_Badass:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            ''
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_Badass.Augment_Pet_Spiderant_Badass:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Elemental Damage Over Time:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_Badass.Augment_Pet_Spiderant_Badass:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/GameData/StatusEffects/EffectModifierAttributes/Att_StatusEffect_DamageCauser_FireDamage.Att_StatusEffect_DamageCauser_FireDamage'
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Spiderant_FireAura'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.7
        ]
    ]
]

Evo2_Spiderant=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/StatusEffects/Status_Beastmaster_PetSpidBuff_Evo2'            
        ],
        [
            """
                (
                    (
                        AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.15)
                    )
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant_Evo2_King.Default__BPChar_PetSpiderant_Evo2_King_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/Pet/Spiderant/_Design/Character/BPChar_PetSpiderant_Evo2_King.Default__BPChar_PetSpiderant_Evo2_King_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_King'            
        ],
        [
            "Your [red]Spiderant[/red] evolves into a [red]Countess[/red]. While accompanied by the [red]Countess[/red], your [skillbold]Critical Hit Damage[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]Scorcher[/red] to burrow underground and then emerge dealing [skillbold]Corrosive Damage[/skillbold] in an area."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_King.Augment_Pet_Spiderant_King:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            ''
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_King.Augment_Pet_Spiderant_King:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '[skillbold]Critical Hit Damage:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/Augments/Augment_Pet_Spiderant_King.Augment_Pet_Spiderant_King:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier'
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'            
        ],
        [
            'Spiderant_Burrow'
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            5.0
        ]
    ]
]

Grim_Harvest=[
    [
        [
            'AbilityClass'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData_1.OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged8/Passive_Beastmaster_Ranged8.Passive_Beastmaster_Ranged8_C'
        ]
    ],
    [
        [
            'ItemFrameName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData_1.OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            'grimHarvest'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged8/Passive_Beastmaster_Ranged8.Default__Passive_Beastmaster_Ranged8_C'            
        ],
        [
            "You gain [skillbold]Gun Damage[/skillbold] and [skillbold]Action Skill Damage[/skillbold]. Your [red]Pet[/red] gains [skillbold]Damage[/skillbold]."
        ]
    ],
    [
        [
            'Value'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged8/Att_BST_Ranged8_PetDamage.Att_BST_Ranged8_PetDamage:ValueResolver_ConstantAttributeValueResolver'            
        ],
        [
            '(BaseValueConstant=0.04)'
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged8'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [ 
            0.03
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged8'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [ 
            0.04
        ]
    ]
]

Leave_No_Trace=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged1/Passive_Beastmaster_Ranged1.Default__Passive_Beastmaster_Ranged1_C'            
        ],
        [
            "Landing a [skillbold]Critical Hit[/skillbold] has a chance to add one ammo to your magazine. <br>This ability has a short internal cooldown."
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged1/Passive_Beastmaster_Ranged1.Default__Passive_Beastmaster_Ranged1_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ]
]

Second_Intention=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C'            
        ],
        [
            '[skillbold]Kill Skill[/skillbold]. <br>You gain [skillbold]Reload Speed[/skillbold]. <br>Scoring a [skillbold]Critical Kill[/skillbold] doubles the effect.'
        ]
    ],
    [
        [
            'StatDataItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C'            
        ],
        [
            """
            (
                UIStatData_OakPassiveAbilityAttribute'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute',
                UIStatData_OakPassiveAbilityAttributeInitializer'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer',
                UIStatData_OakPassiveAbilityAttributeInitializer'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'
            )
            """
        ]
    ],
    [
        [
            'bCalculateWithReductionMath'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '[skillbold]Second Intention Duration:[/skillbold] $VALUE$ seconds'
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SimpleFormulas.DataTable_Beastmaster_SimpleFormulas,RowName=Ranged2_Duration,ValueName=None))'
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Passive_Beastmaster_Ranged2.Default__Passive_Beastmaster_Ranged2_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_Ranged2,ValueName=Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453))'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Status_Beastmaster_Ranged2_ReloadSpeed_DA'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_ReloadTime.Att_Weapon_ReloadTime,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Status_Beastmaster_Ranged2_ReloadSpeed_DA.Status_Beastmaster_Ranged2_ReloadSpeed_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_TapedReloadTime.Att_Weapon_TapedReloadTime,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Status_Beastmaster_Ranged2_ReloadSpeed_DA.Status_Beastmaster_Ranged2_ReloadSpeed_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                )
            )
            """
        ]
    ],
    [    
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged2/Status_Beastmaster_Ranged2_ReloadSpeed_DA.Status_Beastmaster_Ranged2_ReloadSpeed_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_Ranged2,ValueName=Scalar_5_230D633C4A306BF04AB690B7CD89D6AA),
                BaseValueScale=1.0
            )
            """
        ]
    ],
    [    
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SimpleFormulas.DataTable_Beastmaster_SimpleFormulas'
        ],
        [
            'Ranged2_Duration'            
        ],
        [
            'Level'
        ],
        [
            '(BaseValueConstant=1.0,BaseValueAttribute=None,BaseValueScale=1.0)'
        ]
    ],
    [   #Reload Speed
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged2'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            -0.04
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged2'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            10.0
        ]
    ]
]

On_The_Hunt=[
    [
        [
            'AbilityClass'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData.Items_OakPlayerAbilityTreeItemData_Ability'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Passive_Beastmaster_Ranged3_C'
        ]
    ],
    [
        [
            'ItemFrameName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData.Items_OakPlayerAbilityTreeItemData_Ability'            
        ],
        [
            'interplanetary'
        ]
    ],
    [
        [
            'AbilityName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            'On The Hunt'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            '[skillbold]Kill Skill[/skillbold]. <br>You gain a stack of [skillbold]On The Hunt[/skillbold]. <br>For each stack of [skillbold]On The Hunt[/skillbold], you and your [red]Pet[/red] gain [skillbold]Damage[/skillbold]. <br>Additionally you gain [skillbold]Critical Hit Damage[/skillbold] when killing a [skillbold]Badass Enemy[/skillbold].'
        ]
    ],
    [
        [
            'Tags_Humanoid'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="Population.Badass"
                    ),
                    (                    
                        TagName="Population.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.NamedEnemy"
                    )
                ),
                ParentTags=
                (
                    (
                        TagName="Population"
                    ),
                    (
                        TagName="FriendEvent"
                    )
                )
            )
            """
        ]
    ],
    [
        [
            'Tags_Robot'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="None"
                    )
                )
            )
            """
        ]
    ],
    [
        [
            'Tags_Beast'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="None"
                    )
                )
            )
            """
        ]
    ],
    [
        [
            'StatDataItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            """
            (
                UIStatData_OakPassiveAbilityAttribute'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute',
                UIStatData_OakPassiveAbilityAttribute'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1',
                UIStatData_OakPassiveAbilityAttribute'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0',
                UIStatData_OakPassiveAbilityAttributeInitializer'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer',
                UIStatData_OakPassiveAbilityAttributeInitializer'/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'
            )
            """
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '[skillbold]Damage:[/skillbold] $VALUE$ per stack'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_DamageDealtMultiplier.Att_DamageDealtMultiplier'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            '[skillbold]Pet Damage:[/skillbold] $VALUE$ per stack'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '[skillbold]Critical Hit Damage:[/skillbold] $VALUE$ per stack'
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '[skillbold]On The Hunt Duration:[/skillbold] $VALUE$ seconds'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            '[skillbold]On The Hunt Max Stacks:[/skillbold] $VALUE$ '
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_Ranged3,ValueName=Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1))'
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_Ranged3,ValueName=Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453))'
        ]
    ],
    [
        [
            'bUseFormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'bUseFormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            'true'
        ]
    ],
    [
        [
            'BasePriority'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            0.2
        ]
    ],
    [
        [
            'BasePriority'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            0.1
        ]
    ],
    [
        [
            'SectionName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            'Primary'
        ]
    ],
    [
        [
            'SectionName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer_0'            
        ],
        [
            'Primary'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_BulletDamage_DA'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_DamageDealtMultiplier.Att_DamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_BulletDamage_DA.Status_Beastmaster_Ranged3_BulletDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_BulletDamage_DA.Status_Beastmaster_Ranged3_BulletDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData_2"'
                )
            )
            """
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_Presentation'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_DamageDealtMultiplier.Att_DamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_Presentation.Status_Beastmaster_Ranged3_Presentation:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_Presentation.Status_Beastmaster_Ranged3_Presentation:Mutator_OakPassiveAbilityAttributeEffectMutatorData_2"'
                )
            )
            """
        ]
    ],
    [    
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_BulletDamage_DA.Status_Beastmaster_Ranged3_BulletDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                BaseValueConstant=0.024,
                DataTableValue=(Datatable=None,RowName=None,ValueName=None)
                BaseValueScale=1.0
            )
            """
        ]
    ],
    [    
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_BulletDamage_DA.Status_Beastmaster_Ranged3_BulletDamage_DA:Mutator_OakPassiveAbilityAttributeEffectMutatorData_2'            
        ],
        [
            """
            (
                BaseValueConstant=0.03,
                DataTableValue=(Datatable=None,RowName=None,ValueName=None)
                BaseValueScale=1.0
            )
            """
        ]
    ],
    [    
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_Presentation.Status_Beastmaster_Ranged3_Presentation:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                BaseValueConstant=0.024,
                DataTableValue=(Datatable=None,RowName=None,ValueName=None)
                BaseValueScale=1.0
            )
            """
        ]
    ],
    [    
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Status_Beastmaster_Ranged3_Presentation.Status_Beastmaster_Ranged3_Presentation:Mutator_OakPassiveAbilityAttributeEffectMutatorData_2'            
        ],
        [
            """
            (
                BaseValueConstant=0.03,
                DataTableValue=(Datatable=None,RowName=None,ValueName=None)
                BaseValueScale=1.0
            )
            """
        ]
    ],
    [    
        [
            'TriggeredEffect.Duration.DataTableValue'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            '(Datatable=None)'
        ]
    ],
    [    
        [
            'PetEffectDuration'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Passive_Beastmaster_Ranged3.Default__Passive_Beastmaster_Ranged3_C'            
        ],
        [
            '(Datatable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_Ranged3,ValueName=Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1)'
        ]
    ],
    [   #Max Stacks
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged3'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            3.0
        ]
    ],
    [   #Pet Damage 
        [
            'Value.BaseValueConstant'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged3/Att_BST_Ranged3_PetDamage.Att_BST_Ranged3_PetDamage:ValueResolver_ConstantAttributeValueResolver'            
        ],
        [
            0.03
        ]
    ]
]

Head_Count=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged11/Passive_Beastmaster_Ranged11.Default__Passive_Beastmaster_Ranged11_C'            
        ],
        [
            "Whenever you score a [skillbold]Critical Hit[/skillbold], there is a chance your [skillbold]Action Skill Cooldown[/skillbold] is reduced."
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged11/Passive_Beastmaster_Ranged11.Default__Passive_Beastmaster_Ranged11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            'false'
        ]
    ]
]

Furious_Attack=[
    [
        [
            'AbilityClass'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData.OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Passive_Beastmaster_HitAndRun_1.Passive_Beastmaster_HitAndRun_1_C'
        ]
    ],
    [
        [
            'ItemFrameName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData.OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            'furiousAttack'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Passive_Beastmaster_HitAndRun_1.Default__Passive_Beastmaster_HitAndRun_1_C'            
        ],
        [
            'After shooting an enemy, you gain a stack of [skillbold]Furious Attack[/skillbold]. <br>For each stack of [skillbold]Furious Attack[/skillbold], you gain [skillbold]Action Skill Damage[/skillbold] and [skillbold]Action Skill Cooldown[/skillbold]. <br>Your [red]Pet[/red] also gains [skillbold]Damage[/skillbold].'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Passive_Beastmaster_HitAndRun_1.Default__Passive_Beastmaster_HitAndRun_1_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Action Skill Cooldown:[/skillbold] $VALUE$ per stack"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Passive_Beastmaster_HitAndRun_1.Default__Passive_Beastmaster_HitAndRun_1_C:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Action Skill Damage:[/skillbold] $VALUE$ per stack"
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Skill.Att_DamageSourceInstigatorMultiplier_Skill,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueConstant=0,BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill1.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill1,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill2.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill2,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill3.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill3,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_DLC/Ixora/Balance/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill4.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill4,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                )
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_HitAndRun1,ValueName=Scalar_5_230D633C4A306BF04AB690B7CD89D6AA)
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Status_Beastmaster_HitAndRun_1.Status_Beastmaster_HitAndRun_1:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance.DataTable_Beastmaster_SkillBalance,RowName=P_HitAndRun1,ValueName=Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9)
            )
            """
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/HitAndRun1/Passive_Beastmaster_HitAndRun_1.Default__Passive_Beastmaster_HitAndRun_1_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Pet Damage[/skillbold]: $VALUE$ per stack"
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun1'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.008
        ]
    ],
    [   #Cooldown
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun1'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            -0.0062
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_HitAndRun1'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            10.0
        ]
    ]
]

Two_Fang=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged10/Passive_Beastmaster_Ranged10_NEW.Default__Passive_Beastmaster_Ranged10_NEW_C'            
        ],
        [
            "You have a chance to fire an [skillbold]Additional Projectile[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged10/Passive_Beastmaster_Ranged10_NEW.Default__Passive_Beastmaster_Ranged10_NEW_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Additional Projectile Chance:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged10/Passive_Beastmaster_Ranged10_NEW.Default__Passive_Beastmaster_Ranged10_NEW_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "false"
        ]
    ],
    [   #Chance
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged10'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.06
        ]
    ]
]

Big_Game=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Passive_Beastmaster_Ranged7.Default__Passive_Beastmaster_Ranged7_C'            
        ],
        [
            "You gain a portion of your [skillbold]Critical Hit Damage[/skillbold] as [skillbold]Base Action Skill Damage[/skillbold]. <br>You also slightly gain [skillbold]Critical Hit Damage[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Passive_Beastmaster_Ranged7.Default__Passive_Beastmaster_Ranged7_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Critical Hit Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Passive_Beastmaster_Ranged7.Default__Passive_Beastmaster_Ranged7_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Base Action Skill Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Status_Beastmaster_Ranged7'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Skill.Att_DamageSourceInstigatorMultiplier_Skill,
                    ModifierType=PreAdd,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Status_Beastmaster_Ranged7.Status_Beastmaster_Ranged7:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Status_Beastmaster_Ranged7.Status_Beastmaster_Ranged7:Mutator_OakPassiveAbilityAttributeEffectMutatorData_2"'
                )
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Status_Beastmaster_Ranged7.Status_Beastmaster_Ranged7:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=None),
                BaseValueAttribute=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                BaseValueScale=0.03
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged7/Status_Beastmaster_Ranged7_Duration_P.Status_Beastmaster_Ranged7_Duration_P:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=None),
                BaseValueAttribute=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                BaseValueScale=0.03
            )
            """
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged7'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [ 
            0.03
        ]
    ],
    [
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged7'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [ 
            0.0333333333
        ]
    ]
]

The_Most_Dangerous_Game=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C'            
        ],
        [
            "[skillbold]Kill Skill[/skillbold]. <br>Whenever you kill a [skillbold]Badass Enemy[/skillbold] or a [skillbold]Boss[/skillbold], you gain [skillbold]Critical Hit Damage[/skillbold], [skillbold]Accuracy[/skillbold], and [skillbold]Movement Speed[/skillbold] and your [red]Pet[/red] gains [skillbold]Damage[/skillbold]. <br>Additionally, you receive a [skillbold]Cash Reward[/skillbold] from the Intergalactic Bureau of Bounty Hunting."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Pet Damage:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Accuracy:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'SignStyle'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "EUIStatValueSignStyle::Positive"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Movement Speed:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'bCalculateWithReductionMath'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Passive_Beastmaster_Ranged6.Default__Passive_Beastmaster_Ranged6_C:UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_AccuracyImpulse.Att_Weapon_AccuracyImpulse,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_Spread.Att_Weapon_Spread,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Accuracy/Att_AccuracyMaxValue.Att_AccuracyMaxValue,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_RecoilHeightScale.Att_Weapon_RecoilHeightScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Weapons/Att_Weapon_RecoilWidthScale.Att_Weapon_RecoilWidthScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Character/Att_GroundSpeedScale.Att_GroundSpeedScale,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1"'
                )
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=None),
                BaseValueScale=0.083333333333
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=None),
                BaseValueScale=-0.15
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Status_Beastmaster_Ranged6.Status_Beastmaster_Ranged6:Mutator_OakPassiveAbilityAttributeEffectMutatorData_1'            
        ],
        [
            """
            (
                DataTableValue=(DataTable=None),
                BaseValueScale=0.083333333333
            )
            """
        ]
    ],
    [
        [
            'Value'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged6/Att_BST_Ranged6_PetDamage.Att_BST_Ranged6_PetDamage:ValueResolver_ConstantAttributeValueResolver'            
        ],
        [
            '(BaseValueConstant=0.1333333333)'
        ]
    ],
    [   #Critical Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part2'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.083333333333
        ]
    ],
    [   #Move Speed
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part1'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            0.083333333333
        ]
    ],
    [   #Move Speed
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part1'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            0.083333333333
        ]
    ],
    [   #Accuracy
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part1'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            -0.15
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part1'            
        ],
        [
            'Cooldown_8_237733FC43C8C6F2B3A6558D8A0FB0C1'
        ],
        [
            10.0
        ]
    ],
    [   #Cash
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged6_Part2'            
        ],
        [
            'Secondary_21_5ED678CA4FB7C9C602D841A55EDD67B9'
        ],
        [
            45.0
        ]
    ]
]

Galactic_Shadow=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged9/Passive_Beastmaster_Ranged9.Default__Passive_Beastmaster_Ranged9_C'            
        ],
        [
            "You gain [skillbold]Critical Hit Damage[/skillbold] and enemies are less likely to attack you."
        ]
    ]
]

Hunters_Eye=[
    [
        [
            'AbilityClass'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData_4.Items_OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Passive_Beastmaster_Ranged4_C'
        ]
    ],
    [
        [
            'ItemFrameName'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Character/ActionSkill/SkillTree/AbilityTree_Branch_RangedSupport.AbilityTree_Branch_RangedSupport:Tiers_OakPlayerAbilityTreeTierData_4.Items_OakPlayerAbilityTreeItemData_Ability_0'            
        ],
        [
            'huntersEye'
        ]
    ],
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Default__Passive_Beastmaster_Ranged4_C'            
        ],
        [
            "You gain [skillbold]Critical Hit Damage[/skillbold],  [skillbold]Armor Damage[/skillbold] and [skillbold]Damage reduction[/skillbold] when fighting [skillbold]Badass Enemies[/skillbold] and [skillbold]Bosses[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Default__Passive_Beastmaster_Ranged4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '[skillbold]Critical Hit Damage:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Default__Passive_Beastmaster_Ranged4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '[skillbold]Damage Reduction:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'bCalculateWithReductionMath'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Default__Passive_Beastmaster_Ranged4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/Passive_Beastmaster_Ranged4.Default__Passive_Beastmaster_Ranged4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_1'            
        ],
        [
            '[skillbold]Armor Damage:[/skillbold] $VALUE$'
        ]
    ],
    [
        [
            'GameplayTags'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/DamageMod_Ranged4_DmgTakenVsCreature.DamageMod_Ranged4_DmgTakenVsCreature:AttackerCondition_GbxCondition_HasGameplayTags'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="Population.Badass"
                    ),
                    (                    
                        TagName="Population.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.NamedEnemy"
                    )
                ),
                ParentTags=
                (
                    (
                        TagName="Population"
                    ),
                    (
                        TagName="FriendEvent"
                    )
                )
            )
            """
        ]
    ],
    [
        [
            'GameplayTags'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/DamageMod_Ranged4_DmgDealtVsRobots.DamageMod_Ranged4_DmgDealtVsRobots:DefenderCondition_GbxCondition_HasGameplayTags'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="Population.Badass"
                    ),
                    (                    
                        TagName="Population.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.NamedEnemy"
                    )
                ),
                ParentTags=
                (
                    (
                        TagName="Population"
                    ),
                    (
                        TagName="FriendEvent"
                    )
                )
            )
            """
        ]
    ],
    [
        [
            'GameplayTags'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged4/DamageMod_Ranged4_CritDmgVsHuman.DamageMod_Ranged4_CritDmgVsHuman:DefenderCondition_GbxCondition_HasGameplayTags'            
        ],
        [
            """
            (
                GameplayTags=
                (
                    (
                        TagName="Population.Badass"
                    ),
                    (                    
                        TagName="Population.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.Boss"
                    ),
                    (                    
                        TagName="FriendEvent.NamedEnemy"
                    )
                ),
                ParentTags=
                (
                    (
                        TagName="Population"
                    ),
                    (
                        TagName="FriendEvent"
                    )
                )
            )
            """
        ]
    ],
    [   #Damage Reduction
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged4'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            -0.06
        ]
    ],
    [   #Critical Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged4'            
        ],
        [
            'Scalar_5_230D633C4A306BF04AB690B7CD89D6AA'
        ],
        [
            0.05
        ]
    ],
    [   #Armor Damage
        [
            '/Game/PlayerCharacters/_Shared/_Design/Balance/Beastmaster/DataTable_Beastmaster_SkillBalance'
        ],
        [
            'P_Ranged4'            
        ],
        [
            'Tertiary_20_8B581C1746A7BAAB3F3F7BA08BD29453'
        ],
        [
            0.08
        ]
    ]
]

Megavore=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_Shared/_Design/Passives/Ranged_Capstone/Passive_Beastmaster_Ranged_Capstone.Default__Passive_Beastmaster_Ranged_Capstone_C'            
        ],
        [
            "You gain a chance to score a [skillbold]Critical Hit[/skillbold] with [skillbold]Weapons[/skillbold] on any part of the enemies."
        ]
    ]
]
