Gravity_Snare=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/ActionSkill_Beastmaster_DLCSkill.Default__ActionSkill_Beastmaster_DLCSkill_C'            
        ],
        [
            "You toss out a [actionskill]Trap[/actionskill] that [skillbold]Knocks Up[/skillbold] and [skillbold]Temporarily Stuns[/skillbold] nearby enemies. After being deployed, the [actionskill]Trap[/actionskill] periodically continues to [skillbold]Knock Up[/skillbold] and [skillbold]Stun[/skillbold] enemies for the duration. While standing near the [actionskill]Trap[/actionskill], pressing {OakPC_Use} will pick up the [actionskill]Trap[/actionskill], ending the action skill early and [skillbold]refunding a portion of the remaining duration[/skillbold]."
        ]
    ],
    [   #Cooldown
        [
            '/Game/PlayerCharacters/_Shared/_DLC/Ixora/Tables/Table_DLCSkillTreeActionSkillData'
        ],
        [
            'AntiGravityTrap'            
        ],
        [
            'Cooldown_20_735A4D0A498632382644F385DC1382EB'
        ],
        [
            10.0
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/_Shared/_DLC/Ixora/Tables/Table_DLCSkillTreeActionSkillData'
        ],
        [
            'AntiGravityTrap'            
        ],
        [
            'Duration_19_8C8F08E84B625B65004C50A94B2321B1'
        ],
        [
            10.0
        ]
    ],
    [   #Knock Up
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Trap_PulseTime'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            2.0
        ]
    ]
]

Gravity_Snare_A1=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Beastmaster_DLCSkill_Mod5'            
        ],
        [
            "Whenever a trapped enemy is [skillbold]Knocked Up[/skillbold], they drop [skillbold]Ammo[/skillbold], [skillbold]Health Boosters[/skillbold], and [skillbold]Shield Boosters[/skillbold]."
        ]
    ],
    [ 
        [
            'BalancedItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Defs/ItemPool_Beastmaster_Mod5'            
        ],
        [
            """
            (
                (
                    InventoryBalanceData=/Game/Pickups/Health/DA_InventoryBalance_Health.DA_InventoryBalance_Health,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/Pickups/Health/DA_InventoryBalance_Health.DA_InventoryBalance_Health\"',
                    Weight=(BaseValueConstant=1.0,BaseValueScale=1.0)
                ),
                (
                    InventoryBalanceData=/Game/Pickups/Ammo/DA_InventoryBalance_Ammo_AllAmmo.DA_InventoryBalance_Ammo_AllAmmo,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/Pickups/Ammo/DA_InventoryBalance_Ammo_AllAmmo.DA_InventoryBalance_Ammo_AllAmmo\"',
                    Weight=(BaseValueConstant=0.5,BaseValueScale=1.0)
                ),
                (
                    InventoryBalanceData=/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Defs/InvBal_Beastmaster_Mod5ShieldBooster.InvBal_Beastmaster_Mod5ShieldBooster,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Defs/InvBal_Beastmaster_Mod5ShieldBooster.InvBal_Beastmaster_Mod5ShieldBooster\"',
                    Weight=(BaseValueConstant=1.0,BaseValueScale=1.0)
                )
            )
            """
        ]
    ]
]

Gravity_Snare_A2=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Beastmaster_DLCSkill_Mod2'            
        ],
        [
            "Your [actionskill]Trap[/actionskill] gains [skillbold]Duration[/skillbold] and [skillbold]Radius[/skillbold]."
        ]
    ]
]

Gravity_Snare_A3=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Beastmaster_DLCSkill_Mod3'            
        ],
        [
            "If you were to go into [skillbold]Fight For Your Life[/skillbold] while your [actionskill]Trap[/actionskill] is readied, you automatically throw a [actionskill]Trap[/actionskill] at the enemy that downed you."
        ]
    ]
]

Gravity_Snare_A4=[
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Beastmaster_DLCSkill_Mod4'            
        ],
        [
            "Your [actionskill]Trap[/actionskill] no longer [skillbold]Knocks Up[/skillbold] or [skillbold]Stuns[/skillbold] enemies. Instead, it [skillbold]Confuses[/skillbold] nearby enemies, causing them to attack their allies for a short time. Once deployed, the [actionskill]Trap[/actionskill] continues to periodically [skillbold]Confuse[/skillbold] enemies for the duration."
        ]
    ]
]

Base_Loader=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/StatusEffects/Status_Beastmaster_PetLoaderBuff_Evo1'            
        ],
        [
            """
                (
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageReceiverMultiplier_Corrosive.Att_DamageReceiverMultiplier_Corrosive\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=-0.2)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageReceiverMultiplier_Cryo.Att_DamageReceiverMultiplier_Cryo\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=-0.2)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageReceiverMultiplier_Fire.Att_DamageReceiverMultiplier_Fire\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=-0.2)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageReceiverMultiplier_Radiation.Att_DamageReceiverMultiplier_Radiation\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=-0.2)
                    ),
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageReceiverMultiplier_Shock.Att_DamageReceiverMultiplier_Shock\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=-0.2)
                    )
                )
            """
        ]
    ],
    [
        [
            'BalancedItems'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/ItemPool_PetLoader_ION'            
        ],
        [
            """
            (
                (
                    InventoryBalanceData=/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Fork/Balance/Balance_SM_HYP_Fork.Balance_SM_HYP_Fork,
                    ResolvedInventoryBalanceData=InventoryBalanceData'\"/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Fork/Balance/Balance_SM_HYP_Fork.Balance_SM_HYP_Fork\"',
                    Weight=(BaseValueConstant=1.0,BaseValueScale=1.0)
                )
            )
            """
        ]
    ],
    [
        [
            'InventoryAttributeEffects'
        ],
        [
            '/Game/Gear/Weapons/SMGs/Hyperion/_Shared/_Design/_Unique/Fork/Parts/Part_SM_HYP_Barrel_Fork'            
        ],
        [
            """
            (
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=2.2)
                ),
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Spread.Att_Weapon_Spread"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=0.6)
                )
            )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_ION.Default__BPChar_PetLoader_ION_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_ION.Default__BPChar_PetLoader_ION_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader_Evo1'            
        ],
        [
            "You are joined by a loyal [red]ION Loader[/red] companion armed with a [skillbold]Shock SMG[/skillbold] and [skillbold]Homing Shock Orbs[/skillbold] that can be shot to trigger a [skillbold]Shock Nova[/skillbold]. While accompanied by the [red]ION Loader[/red], your [skillbold]Elemental Damage Resistance[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]ION Loader[/red] to fire a powerful [skillbold]Eye Laser[/skillbold] at the enemy."
        ]
    ],
    [
        [
            'SignStyle'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader_Evo1.Augment_Pet_Loader_Evo1:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "EUIStatValueSignStyle::Positive"        
        ]
    ],
    [   #Eye Beam
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_EyeBeam'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.8
        ]
    ],
    [   #Big Orb
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_ShockOrb_Large_Damage'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            2.2
        ]
    ],
    [   #Small Orb
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_ShockOrb_Small_Damage'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            1.1
        ]
    ]
]

HYP_SG_BUL_BALANCE=[
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/EPartList_Hyperion_Shotgun.EPartList_Hyperion_Shotgun'
    ],
    [
        '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/Balance_SG_HYP_PetLoaderWeapon.Balance_SG_HYP_PetLoaderWeapon',
        '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/InvPartSet_SG_Hyp_PetLoaderWeapon.InvPartSet_SG_Hyp_PetLoaderWeapon'
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01.Part_SG_Hyp_Body_01',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_A.Part_SG_Hyp_Body_01_A',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_B.Part_SG_Hyp_Body_01_B',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_C.Part_SG_Hyp_Body_01_C'
        ]
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Parts/Part_SG_Hyp_Barrel_Phebert.Part_SG_Hyp_Barrel_Phebert',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_A.Part_SG_Hyp_Barrel_03_A',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_B.Part_SG_Hyp_Barrel_03_B',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_C.Part_SG_Hyp_Barrel_03_C'
        ]
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Foregrip/Part_SG_Hyp_Foregrip_03.Part_SG_Hyp_Foregrip_03'        
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Grip/Part_SG_Hyp_Grip_02.Part_SG_Hyp_Grip_02'        
    ],
    [ 
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Mag/Part_SG_Hyp_Mag_02.Part_SG_Hyp_Mag_02'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Shield/Part_SG_Hyp_Shield_04.Part_SG_Hyp_Shield_04'
    ],
    [
        'Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Parts/Part_SG_Hyp_Material_Phebert.Part_SG_Hyp_Material_Phebert'
    ]
]

Evo1_Loader=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/StatusEffects/Status_Beastmaster_PetLoaderBuff_Base'            
        ],
        [
            """
                (
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/Shield/Att_ShieldMaxValue.Att_ShieldMaxValue\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.15)
                    )
                )
            """
        ]
    ],
    [
        [
            'RarityData'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/Balance_SG_HYP_PetLoaderWeapon'            
        ],
        [
            '/Game/GameData/Loot/RarityData/RarityData_04_VeryRare.RarityData_04_VeryRare'
        ]
    ],
    [
        [
            'InventoryAttributeEffects'
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Parts/Part_SG_Hyp_Barrel_Phebert'            
        ],
        [
            """
            (
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Damage.Att_Weapon_Damage"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=5.0)
                ),
                (
                    AttributeToModify=GbxAttributeData'"/Game/GameData/Weapons/Att_Weapon_Spread.Att_Weapon_Spread"',
                    ModifierType=ScaleSimple,
                    ModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=None,AttributeInitializer=None,BaseValueScale=0.2)
                )
            )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_BUL.Default__BPChar_PetLoader_BUL_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_BUL.Default__BPChar_PetLoader_BUL_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader'            
        ],
        [
            "Your [red]ION Loader[/red] upgrades into a [skillbold]BUL Loader[/skillbold] equiped with a [skillbold]Fire Shotgun[/skillbold]. While accompanied by the [red]BUL Loader[/red], your [skillbold]Maximum Shield[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]BUL Loader[/red] to turn into a [skillbold]Bulldozer[/skillbold] and charge at enemies."
        ]
    ],
    [   #Damage Block
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_BUL_DamageBlock'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.4
        ]
    ],
    [   #Melee Attack
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_RoundhouseDamage'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            2.5
        ]
    ],
    [   #Charge
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_ChargeDamage'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            2.5
        ]
    ]
]

HYP_SG_WAR_BALANCE=[
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/EPartList_Hyperion_Shotgun.EPartList_Hyperion_Shotgun'
    ],
    [
        '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/Balance_SG_HYP_PetLoaderWeapon_Fire.Balance_SG_HYP_PetLoaderWeapon_Fire',
        '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Weapons/InvPartSet_SG_Hyp_PetLoaderWeapon_Fire.InvPartSet_SG_Hyp_PetLoaderWeapon_Fire'
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01.Part_SG_Hyp_Body_01',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_A.Part_SG_Hyp_Body_01_A',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_B.Part_SG_Hyp_Body_01_B',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Body/Part_SG_Hyp_Body_01_C.Part_SG_Hyp_Body_01_C'
        ]
    ],
    [
        [
            4
        ],
        [
            4
        ],
        [
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Parts/Part_SG_Hyp_Barrel_Phebert.Part_SG_Hyp_Barrel_Phebert',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_A.Part_SG_Hyp_Barrel_03_A',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_B.Part_SG_Hyp_Barrel_03_B',
            '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Barrel/Barrel_03/Part_SG_Hyp_Barrel_03_C.Part_SG_Hyp_Barrel_03_C'
        ]
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Foregrip/Part_SG_Hyp_Foregrip_03.Part_SG_Hyp_Foregrip_03'        
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Grip/Part_SG_Hyp_Grip_02.Part_SG_Hyp_Grip_02'        
    ],
    [ 
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Mag/Part_SG_Hyp_Mag_02.Part_SG_Hyp_Mag_02'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Shield/Part_SG_Hyp_Shield_04.Part_SG_Hyp_Shield_04'
    ],
    [
        '/Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/Parts/Elemental/Part_SG_Hyp_Ele_Fire.Part_SG_Hyp_Ele_Fire'
    ],
    [
        'Game/Gear/Weapons/Shotguns/Hyperion/_Shared/_Design/_Unique/Phebert/Parts/Part_SG_Hyp_Material_Phebert.Part_SG_Hyp_Material_Phebert'
    ]
]

Evo2_Loader=[
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/StatusEffects/Status_Beastmaster_PetLoaderBuff_Evo2'            
        ],
        [
            """
                (
                    (
                        AttributeData=GbxAttributeData'\"/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Grenade.Att_DamageSourceInstigatorMultiplier_Grenade\"',
                        ModifierType=EGbxAttributeModifierType::Scale,
                        BaseModifierValue=(BaseValueConstant=1.0,DataTableValue=None,BaseValueAttribute=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_Beastmaster_PetBuffPassiveScale.Att_Beastmaster_PetBuffPassiveScale,BaseValueScale=0.3)
                    )
                )
            """
        ]
    ],
    [
        [
            'MaxSprintSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_WAR.Default__BPChar_PetLoader_WAR_C:CharMoveComp'            
        ],
        [
            '(Value=900.0,BaseValue=900.0)'
        ]
    ],
    [
        [
            'MaxWalkSpeed'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Pet/Loader/_Design/Character/BPChar_PetLoader_WAR.Default__BPChar_PetLoader_WAR_C:CharMoveComp'            
        ],
        [
            '(Value=650.0,BaseValue=650.0)'
        ]
    ],
    [
        [
            'Description'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader_Evo2'            
        ],
        [
            "Your [red]ION Loader[/red] upgrades into a [skillbold]WAR Loader[/skillbold] equiped with a [skillbold]Fire Shotgun[/skillbold] and [skillbold]Your Grenades[/skillbold]. While accompanied by the [red]WAR Loader[/red], your [skillbold]Grenade Damage[/skillbold] is increased.<br><br>Hold {OakPC_ActionSkill} to issue an [skillbold]Attack Command[/skillbold], which will cause the [red]WAR Loader[/red] to unleash a [skillbold]barrage of missiles[/skillbold] at the target."
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader_Evo2.Augment_Pet_Loader_Evo2:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/DamageMultipliers/Att_DamageSourceInstigatorMultiplier_Grenade.Att_DamageSourceInstigatorMultiplier_Grenade'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/ActionSkill/Augments/Augment_Pet_Loader_Evo2.Augment_Pet_Loader_Evo2:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '[skillbold]Grenade Damage:[/skillbold] $VALUE$'
        ]
    ],
    [   #Missile Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'Loader_Missile_Damage'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            1.8
        ]
    ]
]

Gotta_Go_Fast=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_16/Passive_Beastmaster_DLCSkill_16.Default__Passive_Beastmaster_DLCSkill_16_C'            
        ],
        [
            'Your [red]Pet[/red] gains [skillbold]Movement Speed[/skillbold] and [skillbold]Damage[/skillbold].'
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'DLCSkill16_DamageScale'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.06
        ]
    ]
]

Success_Imminent=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_02/Passive_Beastmaster_DLCSkill_2.Default__Passive_Beastmaster_DLCSkill_2_C'            
        ],
        [
            "Whenever your or your [red]Pet[/red]'s shield breaks or is filled, you and your [red]Pet[/red] create a [skillbold]Radiation Nova[/skillbold]."
        ]
    ],
    [
        [
            'Buffs.Buffs[0].PassiveAbilityClassPtr'
        ],
        [
            '/Game/PatchDLC/Ixora/Gear/ClassMods/_Design/BSM/Skills/CM_Part_Skill_BSM_DLCSkill_18.CM_Part_Skill_BSM_DLCSkill_18:AspectList_OakPassiveAbilityBuffAspectData'            
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_02/Passive_Beastmaster_DLCSkill_2.Passive_Beastmaster_DLCSkill_2_C'
        ]
    ],
    [
        [
            'Buffs.Buffs[0].ItemFrameName'
        ],
        [
            '/Game/PatchDLC/Ixora/Gear/ClassMods/_Design/BSM/Skills/CM_Part_Skill_BSM_DLCSkill_18.CM_Part_Skill_BSM_DLCSkill_18:AspectList_OakPassiveAbilityBuffAspectData'            
        ],
        [
            'SuccessImminent'
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCSimpleFormulas'            
        ],
        [
            'DLCSkill2_NovaDamageCalc'
        ],
        [
            'Multiplier'
        ],
        [
            """
            (
                BaseValueConstant=0.0,
                BaseValueAttribute=/Game/Gear/Shields/_Design/Balance/Attributes/Att_ShieldBalance_Capacity.Att_ShieldBalance_Capacity,
                BaseValueScale=0.2
            )
            """
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCSimpleFormulas'            
        ],
        [
            'DLCSkill2_NovaDamageCalc'
        ],
        [
            'Level'
        ],
        [
            """
            (
                BaseValueConstant=1.0,
                BaseValueAttribute=None,
                BaseValueScale=1.0
            )
            """
        ]
    ]
]

Agility_Training=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_03/Passive_Beastmaster_DLCSkill_3.Default__Passive_Beastmaster_DLCSkill_3_C'            
        ],
        [
            "Your and your [red]Pet[/red] gain [skillbold]Reload Speed[/skillbold]."
        ]
    ],
    [   #Reload Speed
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'
        ],
        [
            'DLCSkill3_ReloadSpeed'            
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            -0.07
        ]
    ]
]

Better_Toys=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/Passive_Beastmaster_DLCSkill_4.Default__Passive_Beastmaster_DLCSkill_4_C'            
        ],
        [
            "You and your [red]Pet[/red] gain [skillbold]Shield Recharge Delay[/skillbold] and [skillbold]Maximum Shield[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/Passive_Beastmaster_DLCSkill_4.Default__Passive_Beastmaster_DLCSkill_4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Maximum Shield:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/Passive_Beastmaster_DLCSkill_4.Default__Passive_Beastmaster_DLCSkill_4_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/Shield/Att_ShieldMaxValue.Att_ShieldMaxValue'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/StatusEffect_Beastmaster_DLCSkill_4'
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Shield/Att_ShieldMaxValue.Att_ShieldMaxValue,
                    ModifierType=EGbxAttributeModifierType::Scale,
                    BaseModifierValue=(BaseValueConstant=0.0,BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/StatusEffect_Beastmaster_DLCSkill_4.StatusEffect_Beastmaster_DLCSkill_4:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/GameData/Attributes/Shield/Att_ShieldOnIdleRegenerationDelay.Att_ShieldOnIdleRegenerationDelay,
                    ModifierType=EGbxAttributeModifierType::Scale,
                    BaseModifierValue=(BaseValueConstant=0.0,BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_04/StatusEffect_Beastmaster_DLCSkill_4.StatusEffect_Beastmaster_DLCSkill_4:Mutator_OakPassiveAbilityAttributeEffectMutatorData_0"'
                )
            )     
            """
        ]
    ],
    [   #Recharge Delay
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill4_ShieldRegenDelay'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            -0.1
        ]
    ],
    [   #Shield Capacity
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill4_ShieldRegenRate'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.083333333333
        ]
    ],
]

Combat_Veterinarian=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_05/Passive_Beastmaster_DLCSkill_5.Default__Passive_Beastmaster_DLCSkill_5_C'            
        ],
        [
            "Shooting the same enemy your [red]Pet[/red] is attacking heals it for a portion of the damage dealt."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_05/Passive_Beastmaster_DLCSkill_5.Default__Passive_Beastmaster_DLCSkill_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            "[skillbold]Life Steal:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_05/Passive_Beastmaster_DLCSkill_5.Default__Passive_Beastmaster_DLCSkill_5_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            'false'
        ]
    ]
]

Throatripper=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_13/Passive_Beastmaster_DLCSkill_13.Default__Passive_Beastmaster_DLCSkill_13_C'            
        ],
        [
            "Your [red]Pet[/red]'s attacks gain a chance to score a [skillbold]Critical Hit[/skillbold], dealing increased damage."
        ]
    ],
    [   #Chance
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill13_CritChance'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.0833333333333
        ]
    ]
]

Lethal_Force_Authorized=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_07/Passive_Beastmaster_DLCSkill_7.Default__Passive_Beastmaster_DLCSkill_7_C'            
        ],
        [
            "Whenever your [red]Loader Bot[/red] would go into [skillbold]Fight For Your Life[/skillbold], it turns into an [skillbold]EXP Loader[/skillbold] instead and seeks out a nearby enemy before self-destructing, dealing [skillbold]Massive Damage[/skillbold].<br><br>Your [red]Pet[/red]'s [skillbold]Respawn Time[/skillbold] is reduced"
        ]
    ],
    [   #Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCSimpleFormulas'            
        ],
        [
            'Ability_Loader_EXPLode'
        ],
        [
            'Multiplier'
        ],
        [
            '(BaseValueConstant=4.0)'
        ]
    ],
    [   #Respawn Time
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill7_RespawnScale'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.2
        ]
    ]
]

Take_This=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_08/Passive_Beastmaster_DLCSkill_8.Default__Passive_Beastmaster_DLCSkill_8_C'            
        ],
        [
            "Your [red]Pet[/red] gains a copy of your shield."
        ]
    ]
]

Monkey_Do=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/Passive_Beastmaster_DLCSkill_9.Default__Passive_Beastmaster_DLCSkill_9_C'            
        ],
        [
            "Your [red]Pet[/red] gains [skillbold]Critical Hit Damage[/skillbold].<br><br>Whenever your [red]Pet[/red] scores a [skillbold]Critical Hit[/skillbold], your next shot is a [skillbold]Critical Hit[/skillbold]."
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/Passive_Beastmaster_DLCSkill_9.Default__Passive_Beastmaster_DLCSkill_9_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/Passive_Beastmaster_DLCSkill_9.Default__Passive_Beastmaster_DLCSkill_9_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            ""
        ]
    ],
    [
        [
            'Initializer'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/Passive_Beastmaster_DLCSkill_9.Default__Passive_Beastmaster_DLCSkill_9_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues.Table_Beastmaster_DLCPassiveConstantValues,RowName=DLCSkill9_PlayerDamage,ValueName=Base_17_28B25EC8493D1EB6C2138A962F659BCD))'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/StatusEffect_Beastmaster_DLCSkill_9'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Damage/Att_CriticalDamageDealtMultiplier.Att_CriticalDamageDealtMultiplier,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/StatusEffect_Beastmaster_DLCSkill_9.StatusEffect_Beastmaster_DLCSkill_9:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                )
            )
            """
        ]
    ],
    [
        [
            'PerGradeUpgrade'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/StatusEffect_Beastmaster_DLCSkill_9.StatusEffect_Beastmaster_DLCSkill_9:Mutator_OakPassiveAbilityAttributeEffectMutatorData'            
        ],
        [
            '(DataTableValue=(DataTable=/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues.Table_Beastmaster_DLCPassiveConstantValues,RowName=DLCSkill9_PetCritDamage,ValueName=Base_17_28B25EC8493D1EB6C2138A962F659BCD))'
        ]
    ],
    [
        [
            'DamageType'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            'None'
        ]
    ],
    [
        [
            'ModifierType'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            "EWeaponShotModifierType::GameType1"
        ]
    ],
    [
        [
            'bModifyDamage'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            'false'
        ]
    ],
    [
        [
            'DamageModifier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            '(DataTableValue=(DataTable=None,RowName=None,ValueName=None),AttributeInitializer=None)'
        ]
    ],
    [
        [
            'CriticalHitModifier'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            "ECriticalHitDamageOverride::ForceCrit"
        ]
    ],
    [
        [
            'bDistributeBetweenProjectiles'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_09/WeaponMod_Beastmaster_DLCSkill_9'            
        ],
        [
            'false'
        ]
    ],
    [   #Crit Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill9_PetCritDamage'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.15
        ]
    ],
    [   #Player Damage
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill9_PlayerDamage'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            0.5
        ]
    ]
]

Wooly_Armor=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_17/Passive_Beastmaster_DLCSkill_17.Default__Passive_Beastmaster_DLCSkill_17_C'            
        ],
        [
            "While your shields are full, your [red]Pet[/red] gains massive [skillbold]Shield Recharge Delay[/skillbold]."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_17/Passive_Beastmaster_DLCSkill_17.Default__Passive_Beastmaster_DLCSkill_17_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Shield Recharge Delay:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_17/Passive_Beastmaster_DLCSkill_17.Default__Passive_Beastmaster_DLCSkill_17_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            '/Game/GameData/Attributes/Shield/Att_ShieldOnIdleRegenerationDelay.Att_ShieldOnIdleRegenerationDelay'
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_17/StatusEffect_Beastmaster_DLCSkill_17'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/GameData/Attributes/Shield/Att_ShieldOnIdleRegenerationDelay.Att_ShieldOnIdleRegenerationDelay,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_17/StatusEffect_Beastmaster_DLCSkill_17.StatusEffect_Beastmaster_DLCSkill_17:OakPassiveAbilityAttributeEffectMutatorData_10"'
                )
            )
            """
        ]
    ],
    [   #Recharge Delay
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill17_DamageReduction'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            -0.8
        ]
    ]
]

Not_Even_A_Challenge=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/Passive_Beastmaster_DLCSkill_11.Default__Passive_Beastmaster_DLCSkill_11_C'            
        ],
        [
            "Whenever your [red]Pet[/red] kills an enemy, you gain [skillbold]Action Skill Duration[/skillbold] and [skillbold]Action Skill Cooldown Rate[/skillbold]. This effect has a stack limit."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/Passive_Beastmaster_DLCSkill_11.Default__Passive_Beastmaster_DLCSkill_11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute'            
        ],
        [
            "[skillbold]Cooldown Rate:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/Passive_Beastmaster_DLCSkill_11.Default__Passive_Beastmaster_DLCSkill_11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            "[skillbold]Action Skill Duration:[/skillbold] $VALUE$"
        ]
    ],
    [
        [
            'Attribute'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/Passive_Beastmaster_DLCSkill_11.Default__Passive_Beastmaster_DLCSkill_11_C:StatDataItems_UIStatData_OakPassiveAbilityAttribute_0'            
        ],
        [
            '/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillDuration_Skill2.Att_ActionSkill_Beastmaster_SkillDuration_Skill2'
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/Passive_Beastmaster_DLCSkill_11.Default__Passive_Beastmaster_DLCSkill_11_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            "[skillbold]Duration:[/skillbold] $VALUE$ seconds"
        ]
    ],
    [
        [
            'AttributeEffects'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11'            
        ],
        [
            """
            (
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillDuration_Skill2.Att_ActionSkill_Beastmaster_SkillDuration_Skill2,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData_3"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillDuration_Skill3.Att_ActionSkill_Beastmaster_SkillDuration_Skill3,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData_3"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_DLC/Ixora/Balance/Beastmaster/Att_ActionSkill_Beastmaster_SkillDuration_Skill4.Att_ActionSkill_Beastmaster_SkillDuration_Skill4,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData_3"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill1.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill1,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill2.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill2,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_Design/Attributes/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill3.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill3,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                ),
                (
                    AttributeData=/Game/PlayerCharacters/_Shared/_DLC/Ixora/Balance/Beastmaster/Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill4.Att_ActionSkill_Beastmaster_SkillCooldownRate_Skill4,
                    ModifierType=Scale,
                    BaseModifierValue=(BaseValueScale=1.0),
                    Mutator=OakPassiveAbilityAttributeEffectMutatorData'"/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_11/StatusEffect_Beastmaster_DLCSkill_11.StatusEffect_Beastmaster_DLCSkill_11:Mutator_OakPassiveAbilityAttributeEffectMutatorData"'
                )
            )
            """
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill11_ActiveTime'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            10.0
        ]
    ],
    [   #Duration Bonus
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill17_DamageReduction'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            -0.8
        ]
    ]
]

Fuzzy_Math=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_12/Passive_Beastmaster_DLCSkill_12.Default__Passive_Beastmaster_DLCSkill_12_C'            
        ],
        [
            "Whenever you or your [red]Pet[/red] score a [skillbold]Critical Hit[/skillbold], a portion of both your [skillbold]Shields[/skillbold] is restored."
        ]
    ],
    [
        [
            'FormatText'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_12/Passive_Beastmaster_DLCSkill_12.Default__Passive_Beastmaster_DLCSkill_12_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            "[skillbold]Shield Restored:[/skillbold] $VALUE$ "
        ]
    ],
    [
        [
            'bDisplayPlusSign'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_12/Passive_Beastmaster_DLCSkill_12.Default__Passive_Beastmaster_DLCSkill_12_C:StatDataItems_UIStatData_OakPassiveAbilityAttributeInitializer'            
        ],
        [
            'false'
        ]
    ]
]

Keep_Them_Safe=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_15/Passive_Beastmaster_DLCSkill_15.Default__Passive_Beastmaster_DLCSkill_15_C'            
        ],
        [
            "Using the [actionskill]Attack Command[/actionskill] when your or your [red]Pet[/red]'s shield is less than half full restores a portion of both your [skillbold]Shields[/skillbold]."
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill15_CooldownTime'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            6.0
        ]
    ]
]

Capacitance=[
    [
        [
            'AbilityDescription'
        ],
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/DLCSkill_18/Passive_Beastmaster_DLCSkill_18.Default__Passive_Beastmaster_DLCSkill_18_C'            
        ],
        [
            "After you activate an [actionskill]Action Skill[/actionskill], you gain massive [skillbold]Maximum Shield[/skillbold] and it immediately starts to recharge."
        ]
    ],
    [   #Duration
        [
            '/Game/PlayerCharacters/Beastmaster/_DLC/Ixora/Passives/Table_Beastmaster_DLCPassiveConstantValues'            
        ],
        [
            'DLCSkill18_Duration'
        ],
        [
            'Base_17_28B25EC8493D1EB6C2138A962F659BCD'
        ],
        [
            10.0
        ]
    ]
]